### ISSUE TITLE
Flight Planner: allow specifying altitude type as relative, absolute or terrain

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1022]
Copter-3.4 will include support for mission items with altitudes specified as relative (what we currently support), absolute alt above sea level and altitude above terrain.

![mp_addframesupport](https://cloud.githubusercontent.com/assets/1498098/10274017/c7acfe12-6b73-11e5-8380-4aa5295b2fef.png)

I think we should add a drop-down perhaps which allows selecting the frame which is saved to the third column of the .txt files.
0 = absolute alt above sea level
3 = relative alt above home
10 = alt above terrain

**Comment by meee1** [comment]
currently mp forces the entire mission to a specific type. its not selectable per wp.

**Comment by rmackay9** [comment]
I'm unsure whether we need a per-command setting or whether setting it for an entire mission is enough.  I suspect it won't be long after terrain following is implemented that people will ask that they be allowed to mix alt types but I'm happy to at least wait until that request comes in.

In the vehicle code we will implement it so they can be mixed.

**Comment by iskess** [comment]
I requested the ability to select altitude reference for each WP a year ago #566, (see post 2 and 3). Tridge provided this functionality in Mavproxy.

**Comment by meee1** [comment]
and I still don't plan on changing it at this point in time, as I believe it will create user confusion.

**Comment by naktinis** [comment]
Can we consider this closed after 3547b4ae2139589b25192b16a04acbe6fe996aab? Issue description does not explicitly ask for per-command altitude reference.

**Comment by meee1** [comment]
@naktinis sounds fair to me. that  and randy has tested this
