### ISSUE TITLE
Laser altimeter geotaging csv

### ISSUE THREAD

**Issue by raptortrias** [ArduPilot/MissionPlanner#1126]
Is it possible to add functionality to create a csv file with sonnarrange [used with laser altimeters] while geotagging images in mission planner. This way the above ground data can be imported in software like agisoft to increase model accuracy.

 Thanks

**Comment by meee1** [comment]
do you have a log of sample data I could use to test?

**Comment by raptortrias** [comment]
This log file deosn't have any trig cam messages, but the lidar was activated. The lidar altitude is at CTUN Salt  . Ideally during georeferencing we could get the sonar alitude in a csv for every image together with GPS coordinate
[10_02_log.zip](https://github.com/diydrones/MissionPlanner/files/126623/10_02_log.zip)

**Comment by raptortrias** [comment]
Michael,

 If we replace RelAlt with Salt in the geotagging code, would this work for exporting the GPS altitude as well as the above ground altitude during geotagging?

 Thanks

**Comment by raptortrias** [comment]
Michael,

 I don't have any other log files as the system is with the customer now, but if it would have been possible to modify the script so that it can pull the Salt (sonar altitude) during geotagging it would be great.

the location.txt would be the best place to have this.

 Thanks

**Comment by nicksargeant** [comment]
Hi Michael, 
I too very much need this functionality but it appears to only work for Copter logs because rangefinder distance is stored as CTUN.SAlt on Copter and RFND.Dist1 on Plane. Any chance on a patch?
Kind regards,
Nick

**Comment by meee1** [comment]
Added @nicksargeant

**Comment by raptortrias** [comment]
@meee1  thanks very much
