### ISSUE TITLE
Show PWM value of AUX OUT port 1 in Mission Planner 

### ISSUE THREAD

**Issue by CrazyPopLin** [ArduPilot/MissionPlanner#1154]
I am using AUX out 1 port as servo connect,onboard send command to control the servo and it works.  I just wondering if the PWM value of this port can be shown up in Mission Planner. I am looking for the one named **ch9in**, but nothing happened. 
Could anyone give me some suggestions, thanks.

**Comment by meee1** [comment]
ch9in refers to readio input 9, is that what you wanted?

**Comment by CrazyPopLin** [comment]
thx @meee1 ,I want to know if there is some parameter in Mission planner to represent the first AUX OUT 1 port.
