### ISSUE TITLE
Displaying geo-fence limits on map

### ISSUE THREAD

**Issue by Rupicapra-rupicapra** [ArduPilot/MissionPlanner#1165]
Hello,
I would like to request a feature: adding an option to display the geo-fence limits around home location, based on the defined radius, on maps (in Flight Plan tab and Status tab). It would be helpful when creating a flight plan, to ensure that the defined waypoints are not out of that fence.
What do you think about this ?

Thanks a lot,
Rupi

**Comment by meee1** [comment]
for plane or copter?

**Comment by Rupicapra-rupicapra** [comment]
For copter.

**Comment by onurboy** [comment]
Michael,
It's a good feature. Have you implemented it in latest beta?
Thanks.

Onur.

**Comment by rmackay9** [comment]
This is a duplicate of https://github.com/ArduPilot/MissionPlanner/issues/456 so closing
