### ISSUE TITLE
SITL doesn´t star JBSIM graphical simulator

### ISSUE THREAD

**Issue by Fortesque0** [ArduPilot/MissionPlanner#1177]
Hello:
I change options, but allways starts xplane link
![link](https://cloud.githubusercontent.com/assets/17238988/13606890/1d57e31e-e54e-11e5-8440-ac13f32784ed.png)
Thanks in advance

**Comment by meee1** [comment]
that is a display issue only. it will say that on all sim types.

**Comment by Fortesque0** [comment]
Hello Michael:

I can´t make JSBSim to work (For have a graphical 3d simulated copter/plane). I am looking on to console and there is an error report
![simulador fallo](https://cloud.githubusercontent.com/assets/17238988/13650017/efd8bbd6-e640-11e5-81ac-653bb6defcdb.PNG)
Could this be the reasson?
Thanks

**Comment by meee1** [comment]
need to take a step back. jsbsim in not a 3d simulator, it is a physics engine. what is it your expecting

**Comment by Fortesque0** [comment]
Sorry, i was confused. The simulator that was integrated on previous versions was Flight Gear, so, why doens´t starts if i have selected , and why i can select  jsbsim (i suposse that jsbsim its the engine for sitl)
Thanks

**Comment by Fortesque0** [comment]
Finally I managed to run the Flightgear with the SITL. Honestly, it is not collected anywhere to properly configure the most current version.
The manuals in Wiki are outdated and useless to make changes if not properly documented in the Wiki.
I offer volunteer to help update the wiki. That any project manager contact me if you are interested in my offer.
 regards

**Comment by Fortesque0** [comment]
Could be possible to write correct instructions on wiki for 3d simulator running on windows?

**Comment by Fortesque0** [comment]
Hello,
Any updates for this?
