### ISSUE TITLE
Storm 32 gimbal can't change modes

### ISSUE THREAD

**Issue by Jman841** [ArduPilot/MissionPlanner#1199]
When using the Mavlink connection on a Storm32 gimbal. If you choose "Point Camera Here" in the map, You can't change back to RC Targeting when using the joystick.

**Comment by meee1** [comment]
I'm not sure this is a MP issue.
are you changing the mount back to rc targeting?

**Comment by Jman841** [comment]
That is the issue. Once it changes to the GPS pointing or I choose RC Targeting and select "Set Mount" but it does not do anything.

Also, with the latest version of Mission Planner, I can not even select modes and the mode shown in the GUI with Arducopter is "Unknown". I believe this is a separate issue though.

**Comment by meee1** [comment]
are you selecting the gimbal before you do the set mount from the menu up the top right?

**Comment by gediminasgu** [comment]
As I see from ardupilot code https://github.com/ArduPilot/ardupilot/blob/b8011fd46cc97b0e8161b35744328c1319beb0f0/APMrover2/commands_logic.cpp#L98
The mode will be reset to default (where default is ``restores the mode to it's default mode held in the MNT_DEFLT_MODE parameter``) if you will send lat/lng/alt as 0/0/0. And you can do that choosing from menu "Point camera to coords" and entering "0;0;0".

**Comment by rmackay9** [comment]
this is a really old issue so closing.  I'm sure it is possible to set the Mount's mode with MP these days.
