### ISSUE TITLE
Problems with Auto WP / Survey (Grid)

### ISSUE THREAD

**Issue by Seidenschwang** [ArduPilot/MissionPlanner#1214]
Hi there,

I'm trying to create a mission for my hexacopter based on a polygon. Therefore I'm using the function "Auto WP" -> "Survey (Grid)".
![2016-04-03 17_44_18-survey grid](https://cloud.githubusercontent.com/assets/17014641/14233279/129757a4-f9c4-11e5-89a0-f0ddff7111c7.png)

But the following features doesn't work :-(:

- **"Grid Options"->"Copter Options"**: "Delay at WP" doesn't have any effects
![2016-04-03 17_36_00-mission planner 1 3 37 build 1 1 5917 13431](https://cloud.githubusercontent.com/assets/17014641/14233217/b10c9a86-f9c2-11e5-8745-b8b1c2c1b193.png)

- **"Camera Config"->"Trigger Method"**: DO_DIGICAM_CONTROL doesn't use the ShutterCommand: 
![2016-04-03 17_38_29-mission planner 1 3 37 build 1 1 5917 13431](https://cloud.githubusercontent.com/assets/17014641/14233231/39a9bfe0-f9c3-11e5-9d42-9a4a5059cb77.png)

- **"Grid Options"->"Copter Options":** Heading Hold doesn't affect the footprints (Mission seems to be allright (Condition yaw) )
![2016-04-03 17_53_29-survey grid](https://cloud.githubusercontent.com/assets/17014641/14233314/37b15d04-f9c5-11e5-9b05-656c06ee92c4.png)

Do you have any idea about solving the problems?

(MissionPlanner: 1.3.37 / ArduCopter: 3.3.3-RC2)

**Comment by meee1** [comment]
Thanks for the bug report. its much easy when you give me all the details, which you did a good job at!!

ive fixed all the issues you mention here.

**Comment by meee1** [comment]
ive uploaded a new beta mp with the fixes

**Comment by Seidenschwang** [comment]
Wow, that was pretty fast!

Thank you
