### ISSUE TITLE
BUG: Quick tab option "timesincelastshot" is rounded to whole number

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#1216]
The Quick tab have an option called "timesincelastshot" that shows the time between camera triggers. It has 2 digits behind the decimal place that always show zero.

**Comment by meee1** [comment]
I don't think this is a MP bug, but the data coming from the plane. that tlog would help tell this.

**Comment by iskess** [comment]
https://www.dropbox.com/s/cp8xowvdb01gkhe/2016-04-05%2010-18-39%20quarry.tlog?dl=0

**Comment by meee1** [comment]
fixed
