### ISSUE TITLE
BUG: During tlog playback, pressing pause removes flight plan

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#1218]
Using beta 1.3.37.1, if I press pause during tlog playback, all waypoints and flight lines are cleared from the screen. Also, the HUD re-centers and all data is removed. Pause is useful during playback to freeze the data for analysis. As a work around I now 1/10 speed instead of pause so I have more time to see the data without loosing it.

**Comment by meee1** [comment]
fixed
