### ISSUE TITLE
Audio Cue Mission Planner

### ISSUE THREAD

**Issue by IronDome2** [ArduPilot/MissionPlanner#1227]
Hi All

I'm not sure how many people will agree with me, but find the Mission Planner cues not natural sound. Is it possible to change the cue and add more such as reading various parameters such as Aircraft range etc, warning etc.
 I have a copy of recorded audios that i could use, but I just don't know how to program.
Thanks in Advance

**Comment by meee1** [comment]
the cue uses the default system speech voice. so if you change that it should change.
also mp has an option to write a custom cue string, you can have it say anything you want on a 30 second interval

**Comment by IronDome2** [comment]
Thanks
I will have to try that.
