### ISSUE TITLE
Beta cannot download Params 

### ISSUE THREAD

**Issue by ThorstenDP** [ArduPilot/MissionPlanner#1231]
Hi all,

the current as well as the previous beta of Mission Planner connects to the PixRacer but the seems to be in some infinite loop while "Getting Params..." 
The official release works.
Tested on a PixRacer and an AUAV-X2.

Cheers,
Thorsten

**Comment by meee1** [comment]
this should be resolved

**Comment by ThorstenDP** [comment]
Yes!
Thanks a lot!
