### ISSUE TITLE
New feature: extract waypoint mission from .bin log

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/MissionPlanner#1234]
New feature: extract waypoint mission from .bin log

**Comment by meee1** [comment]
sounds good to me, happy for it to form part of the kml creation? just to minimise ui clutter.

**Comment by meee1** [comment]
there is one field missing that I require. which is frame. ie rel/abs/terrain. this is not saved to the log.

**Comment by meee1** [comment]
at the moment all wps are output as realative.

**Comment by meee1** [comment]
closing.

**Comment by magicrub** [comment]
Thanks!
