### ISSUE TITLE
Turn off serial number narration

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/MissionPlanner#1236]
A number of people have asked to please remove or to be able to turn off the reading of the long serial number of a Pixhawk, et al after connection via telemetry.
It seems that this is just a bunch of numbers that have no relevance to 99.9% of users and reading the whole lot out can be a little irritating.
ref: diydrones.com/forum/topics/mavlink-announcment?commentId=705844

**Comment by meee1** [comment]
this has already been addressed in the current beta.

**Comment by GrahamDyer** [comment]
Much appreciated

**Comment by meee1** [comment]
#1222
