### ISSUE TITLE
Waypoint altitude calculation in terrain + verify height is counter-intuitive

### ISSUE THREAD

**Issue by naktinis** [ArduPilot/MissionPlanner#1239]
When adding waypoints in terrain mode using point-and-click with verify height turned on I expect each new point's altitude to be set to "Default Alt".

**Here's my scenario:**

- Select "Terrain" mode
- Set "Default Alt" to 100
- Check "Verify Height"
- Point and click on the map

**Expected:**

"Verify Height" should have no effect on "Alt" values (they should be 100 everywhere), because they already mean "above terrain". Since I'm in "Terrain" mode, "Alt" will already be adjusted by the autopilot to follow the surface, I don't need mission planner to add an offset relative to home.

**Actual result:**

"Verify Height" modifies altitude on clicked points relative to home altitude as if I was in "Relative" mode.

**Comment by meee1** [comment]
done. thanks
