### ISSUE TITLE
Report Onboard compass failure

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1246]
In Copter-3.4 there's a new onboard compass calibrator.
When the compass calibration fails, there's no clear indication in mission planner that it's failed.
Here's a tlog, .bin and image showing what mission planner shows during a failed compass calibration.
[failed-compass-cal.zip](https://github.com/ArduPilot/MissionPlanner/files/254188/failed-compass-cal.zip)

**Comment by rmackay9** [comment]
It also doesn't seem to show success..

**Comment by meee1** [comment]
![image](https://cloud.githubusercontent.com/assets/511568/15115004/50b864c4-162f-11e6-8bd3-1e0f1c34b83f.png)
acording to the log both compass's reach 99 percent. so did it fail?

**Comment by meee1** [comment]
after looking a bit more, the calibration finished successfully, even though the offsets the calibration detected where 0. not sure how that can happen.

**Comment by WickedShell** [comment]
Not a MP issue. You can see the referenced ArduPilot PR for a initial patch that addresses it.
