### ISSUE TITLE
Route track in VB.NET windows application

### ISSUE THREAD

**Issue by SCORPIO12** [ArduPilot/MissionPlanner#1252]
there is a customer who travel regular in the same route . and when i track his/her car through car reg-no then in the map i displayed that route in blue lines 
check image
http://oi65.tinypic.com/2vn3xqo.jpg[^]

now i want to show another fixed line around this blue line ... when car pass against this route then i want to show message

there is a button show track (label) and there is two fields from: tO:
date is selected from these two fields then when i click on show track then map is displayed

now i want to draw another 2 lines.. one line is in right and other in left with -500 lag and -500 lat 

like this

lat line main line lag line

| | |

this is the main function blue line draw on map
```
Public Sub DrawTrack(ByVal d As DataView)
'List latlng = new List();
Dim latlng As New List(Of PointLatLng)

For Each dataRow As DataRowView In d
If Convert.ToDouble(dataRow("Latitude")) > 0 And Convert.ToDouble(dataRow("Longitude")) > 0 Then
latlng.Add(New PointLatLng(Convert.ToDouble(dataRow("Latitude")), Convert.ToDouble(dataRow("Longitude"))))
End If
Next

Dim pen As New Pen(Color.Red)
pen.Brush = Brushes.Blue
pen.Color = Color.Green
pen.Width = 2

Dim track As New GMapRoute(latlng, "Track")
track.Stroke = pen

o.Routes.Add(track)

'o.Routes.Add(New GMapRoute(latlng, "hello"))
MainMap.Overlays.Add(o)
End Sub
```

**Comment by meee1** [comment]
this is not MP related
