### ISSUE TITLE
Sysid selector (ctrl-x) removed?

### ISSUE THREAD

**Issue by ggregory8** [ArduPilot/MissionPlanner#1258]
Hi,

It looks like the ctrl-x shortcut has been removed to select which vehicle/unit (in a system with multiple sysid) we will display data and parameters for.

Has this been replaced by something else?

How do we select which sysid to use?

Thanks.

**Comment by meee1** [comment]
it was replaced with the drop down up the top, the one under the baud rate.

**Comment by iskess** [comment]
What replaced the hidden secret menu that forced MP into copter or plane mode? Sometimes I find myself in the wrong mode and I am not nearby an aircraft to connect to. For example, I'm trying to create a plane flight plane but I'm in copter mode and the commands are different.

**Comment by meee1** [comment]
currently there is no secret.

try connecting to sitl first though, as that will make it change

**Comment by meee1** [comment]
closing as functionality was moved.
