### ISSUE TITLE
Add single copter icons

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1261]
[singlecopters-bigger.zip](https://github.com/ArduPilot/MissionPlanner/files/283979/singlecopters-bigger.zip)

We've recently started supporting single copters a little more.  We've got a SITL simulator for them now and Leonard's put work into the controls.

It would be nice if Mission Planner showed the single copter icon if the MAV_TYPE is MAV_TYPE_COAXIAL

**Comment by meee1** [comment]
added. thanks

**Comment by rmackay9** [comment]
cool, thanks!!
