### ISSUE TITLE
motortest for QuadPlanes

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#1263]
motortest needs to be available for QuadPlanes, either unconditional for plane, or just when the Q_ENABLE parameter is non-zero

**Comment by magicrub** [comment]
+1

**Comment by SSUAV** [comment]
+1

**Comment by meee1** [comment]
this should be working. just need one of you guys to test

**Comment by meee1** [comment]
closing, feel free to reopen if needed
