### ISSUE TITLE
Latest MP beta updater fails

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1264]
Hi

latest beta of MP running on win7, offers to update, but then all attempts to update fail. Previously, beta updates would run ok, so this is the first time this happens.

<img width="677" alt="screen shot 2016-05-27 at 11 10 23" src="https://cloud.githubusercontent.com/assets/3130363/15605142/fa3d535e-23fb-11e6-8527-fad4d0fc6215.png">

**Comment by meee1** [comment]
Please restart windows, and try again.

 

The file is most likerly in use

**Comment by lvale** [comment]
Sorted it, thanks. Previous updates didn't require Win reboots.
