### ISSUE TITLE
Tracker Gains need more decimals

### ISSUE THREAD

**Issue by stefanlynka** [ArduPilot/MissionPlanner#1273]
When connected to the mission planner's extended tuning screen for the antenna tracker, the YawGain and Pitch Gain areas only display 1 (or sometimes 2) decimal places of accuracy.  Ideally, like Copter, we should have 3 decimals  for P, I and D.  Thanks!

**Comment by meee1** [comment]
currently these are defined by the tracker code.
here https://github.com/ArduPilot/ardupilot/blob/master/AntennaTracker/Parameters.cpp#L307
please create an issue on the ardupilot repo to update the standard Increments value
