### ISSUE TITLE
Tracker Extended Tuning: flip or rotate sliders

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1278]
Can we flip the horizontal yaw slider and rotate the pitch slider 90degrees clockwise?  If we do this then the slider movement will match the actual movement of the tracker.
![tracker_extendedtuning_sliderfix](https://cloud.githubusercontent.com/assets/1498098/15857098/78ad18f4-2cf4-11e6-84fa-6de0b6a597c6.png)

**Comment by meee1** [comment]
assume is good

**Comment by rmackay9** [comment]
Thanks for this too!
