### ISSUE TITLE
Mission Planner accepts incorrectly formatted floating point numbers

### ISSUE THREAD

**Issue by hsteinhaus** [ArduPilot/MissionPlanner#128]
Using a german locale setting on my box, I am able to enter numbers like "0.31" . After writing the parameter value and reading it back from APM, the entered number reads "31". - quite dangerous value for RLL2SRV_P ;-)

Whats the problem behind? In Germany, the decinal separator is ",". The .NET environment seems to know that and expects input like that. Mission Planner does not check the entered number against this implicit expectation, and drops the ".".

Possible solution 1: disable locale mechanism - entering an "english-style" number is perfectly ok in my opinion. Reject anything that contains characters other than "."

Possible solution 2: Allow locale-formatted numbers and check against them. Reject anything that does not contain the locale-specified decimal separator.

Priority: I think this bug is really critical and has the potential to cause severe damage.

**Comment by skorokithakis** [comment]
Just to chime in, I agree that this is a critical bug, it is unacceptable that any software would receive input like "1.23" and silently convert it to anything other than the intended. It should at least throw an error.
