### ISSUE TITLE
Tracker: add support for ALT_SOURCE, SERVO_YAW_TYPE, SERVO_PITCH_TYPE

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1282]
Tracker v0.7.8 (current in beta testing) has support for a few new fields.
ALT_SOURCE : allows user to control whether pitch axis is driven by the vehicle's GPS (or more accurately EKF) altitude or the barometer's.
SERVO_TYPE has been replaced by two new parameters, SERVO_YAW_TYPE and SERVO_PITCH_TYPE.
In the picture below I've also moved the pitch axis's slider as mentioned in this other to-do request.  https://github.com/ArduPilot/MissionPlanner/issues/1278

![tracker_servotypeupdate](https://cloud.githubusercontent.com/assets/1498098/15951958/d23b4b7a-2ef7-11e6-829e-db706ffff98d.png)

**Comment by meee1** [comment]
assume is good

**Comment by rmackay9** [comment]
Thanks very much!
