### ISSUE TITLE
Full Param List's "Reset to Default" applies to wrong vehicle (or all vehicles?) in multi vehicle environment

### ISSUE THREAD

**Issue by yak-54** [ArduPilot/MissionPlanner#1285]
Antenna Tracker some thing to look at 
when your in full list of the prams working on Antenna Tracker  with missionPlanner and click on restore to defaults it reset all it can see LoL so reboot the quad as well that was in the air at the time i watch it drop 20 meters to its death and it was on antenna tracker in the stats window

**Comment by rmackay9** [comment]
@yak-54, you're sure that you had the Antenna Tracker selected on the Flight Data screen?

**Comment by meee1** [comment]
could you please provide the tlog?

**Comment by yak-54** [comment]
Hi buddy yes it was the Antenna Tracker selected on the Flight Data screen

**Comment by yak-54** [comment]
no sorry no logs empty
