### ISSUE TITLE
Live calibration seems to be broken for second compass

### ISSUE THREAD

**Issue by staroselskii** [ArduPilot/MissionPlanner#1288]
FS: ArduCopter 3.4-rc1
Hardware: Raspberry Pi 2 + Navio 2

Our users have spotted a strange issue with calibration offsets. 

Take a look at these pictures:
1) Live Calibration

Offsets after the calibration:
![image](https://cloud.githubusercontent.com/assets/4541230/16084577/08241216-3322-11e6-9828-bea4dec7f35f.png)

Tuning tab:
![image](https://cloud.githubusercontent.com/assets/4541230/16084634/3361a3bc-3322-11e6-9605-18db71447aab.png)

2) Onboard Calibration
Offset after calibration:
![image](https://cloud.githubusercontent.com/assets/4541230/16084644/381c5866-3322-11e6-8c1e-ef2df94bfd48.png)

Tuning tab:
![image](https://cloud.githubusercontent.com/assets/4541230/16084652/3c56c38a-3322-11e6-9a86-a563e1180a10.png)

It's pretty evident that something's wrong with `my` and `my2` being so different. In fact it seems as if OFF2 was inverted the whole thing would've been gone. To confirm I adjusted the parameter manually and it did the trick - all axis got intact and aligned. So I suppose 
I was also a little confused with the fact that offsets don't get updated once onboard calibration is complete. It seems like the Y axis is to be inverted.

A quick glance at MagCalib.cs hasn't resulted in a solution, so I'd be extremely glad if someone could have a look.

**Comment by meee1** [comment]
are you sure you have the correct orientation set for compass 2?

**Comment by staroselskii** [comment]
@meee1 

Yes. Pretty sure. Some of our users have confirmed that onboard calibration works and the live doesn't (with orientation not changed between the tests). Although I do share your scepticism, I'm no static analyzer. Is there a chance the could be a typo in this piece of code?

**Comment by ivereninov** [comment]
Is there anything we can do to help debug? The issue has been confirmed by several users.

**Comment by staroselskii** [comment]
Sorry for the hustle. It was my bad all the way. Will be fixed with https://github.com/ArduPilot/ardupilot/pull/5249
