### ISSUE TITLE
extract params from log file

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/MissionPlanner#1295]
Maybe another task for the create KML+gpx button? Maybe its time to rename that button label? :)

feature request: extract params from .bin/.log file. method options:
- one file with all params
- One file for the boot-up, another file for all further changes (similar to mission extraction)

**Comment by cala2** [comment]
+1 create a param file with a log one, usefull for upload to vehicle.

**Comment by magicrub** [comment]
done a long time ago

**Comment by ddomit** [comment]
> done a long time ago

How can i do this? Can you please explain? I dont know where i can extract the .param file from the .bin file

**Comment by magicrub** [comment]
@ddomit This is hiding in the "create KML+gpx" button and needs a better label, can you add that @meee1 ? That button also extracts missions and mission changes.
![image](https://user-images.githubusercontent.com/4782875/128261721-da94b89c-7ec7-4056-a39a-1359873b639f.png)

**Comment by ddomit** [comment]
Thank you!! @magicrub
