### ISSUE TITLE
+ and - shortcuts not working during tlog playback

### ISSUE THREAD

**Issue by Kelly-Foster** [ArduPilot/MissionPlanner#1299]
Space bar works to pause and resume, but can't get + or - keys (with or without Shift or Ctlrl modifiers) in any MP window to effect increase or decrease in playback speed as advertised.  Windows 7, MP 1.3.38.

Kelly

**Comment by meee1** [comment]
to use it you must use the numberpad + and -, not shift x

**Comment by meee1** [comment]
assume all is ok
