### ISSUE TITLE
rtklib mission planner compatibility

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/MissionPlanner#1302]
Hello Mickael,

Using gps inject, as detailled on your vidéo, I dont't achieve rtk...

Could you please detail how to setup serial 4 port on copter for it works?

I use ac3.4.1 beta.

**Comment by meee1** [comment]
I need more information.
what gps are you using on the vehicle, and on the ground?

**Comment by meee1** [comment]
closing  no info
