### ISSUE TITLE
Ardu pilot link not working in description

### ISSUE THREAD

**Issue by talhahasanzia** [ArduPilot/MissionPlanner#1306]
The link provided in the description as : http://ardupilot.com/wp-content/plugins/download-monitor/download.php?id=82 is not working, giving 404 error.

**Comment by magicrub** [comment]
Its .com

**Comment by talhahasanzia** [comment]
It is .com in the description, still checked not worked. I am closing the issue as it is non-technical.

**Comment by magicrub** [comment]
I mean, the problem is its .com. it needs to be .org.
