### ISSUE TITLE
Rover Enhancement: new CMD 

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/MissionPlanner#1310]
Hi.  I've added a new MAV_CMD to common.xml:
https://github.com/ArduPilot/mavlink/pull/11

Can MP be updated to support this for Rover? I went to do it myself and submit a PR but then wasn't too certain.  
It only uses the first parameter at the moment.  0 for forward and 1 for reverse.

If I can help just let me know.

Thanks, Grant.

**Comment by meee1** [comment]
added thanks
