### ISSUE TITLE
FLIR Vue for camerasBuiltin.xml

### ISSUE THREAD

**Issue by 0n3-70uch** [ArduPilot/MissionPlanner#1311]
Hello,

the FLIR Vue parameters are wrong in the "camerasBuiltin.xml".

Greetings
Fabian

**Comment by meee1** [comment]
what should they be?

**Comment by 0n3-70uch** [comment]
Oh sorry. Here are the specs:

`<Camera><name>FLIR Vue 336 6,8mm</name><flen>6.8</flen><imgh>256</imgh><imgw>336</imgw><senh>4.352</senh><senw>5.712</senw></Camera><Camera><name>FLIR Vue 336 9mm</name><flen>9</flen><imgh>256</imgh><imgw>336</imgw><senh>4.352</senh><senw>5.712</senw></Camera><Camera><name>FLIR Vue 336 13mm</name><flen>13</flen><imgh>256</imgh><imgw>336</imgw><senh>4.352</senh><senw>5.712</senw></Camera><Camera><name>FLIR Vue 640 9mm</name><flen>9</flen><imgh>512</imgh><imgw>640</imgw><senh>8.704</senh><senw>10.88</senw></Camera><Camera><name>FLIR Vue 640 13mm</name><flen>13</flen><imgh>512</imgh><imgw>640</imgw><senh>8.704</senh><senw>10.88</senw></Camera><Camera><name>FLIR Vue 640 19mm</name><flen>19</flen><imgh>512</imgh><imgw>640</imgw><senh>8.704</senh><senw>10.88</senw></Camera>`

**Comment by meee1** [comment]
done thanks.
