### ISSUE TITLE
Download All Logs rewriting old files

### ISSUE THREAD

**Issue by vfp1** [ArduPilot/MissionPlanner#1313]
Hi, 
thank you for this amazing piece of software. In earlier versions when my missions were completed I usually followed the practice of downloading all the logs via "Download DataFlash Log Via Mavlink", and then selected "Download All Logs". Usually the files were never overwritten and they were stored in the log folder in Mission Planner without being modified. Since the APM consistently makes space for new data, old logs are being progressively erased as new logs are coming in. Now, when I download the all the logs, the old ones are overwritten with the ones that are missing some data that was erased to make space for new logs. So I found that I have some logs with half of the data missing. This never happened before, and I am guessing if it is due to a new update or some bad procedure that I am following. At the moment I just try to remember which were the newest logs and try to download those, but for security reasons it will be nice to download all logs every time. 

Best,

**Comment by meee1** [comment]
what version of MP are you running?

**Comment by vfp1** [comment]
Hi, thanks for the reply. I am using Mission Planner version "1.3.38 build 1.1.5983.12141" in Windows 10.

**Comment by meee1** [comment]
please update to the latest
issue has ben solved
https://github.com/ArduPilot/MissionPlanner/blob/master/ChangeLog.txt#L108

**Comment by vfp1** [comment]
That's great then, thank you very much!
