### ISSUE TITLE
Zoom adjustment when changing angle in Survey (Grid)

### ISSUE THREAD

**Issue by vfp1** [ArduPilot/MissionPlanner#1314]
Hi, 

within Survey (Grid), if the area is zoomed in, changing the angle of the flight path jumps back to the default zoom. I guess that its because the map refreshes to a default status when changing the angle of the flight path. It is not a big issue, but I think that maintaining the selected zoom will help planning the turns according to the wind direction, and make the feeling of the software more smooth out in the field.

Btw, thanks for this really nice software!

**Comment by meee1** [comment]
closing, thanks
