### ISSUE TITLE
include RC12 - RC14 in "Servo" tab

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#1317]
Why does the Servo tab only include channels RC5-RC11? I'm wanting to activate servos on channel RC13. Has this just not been updated since the APM 2.6, or is there some other limitation?

![servo tab](https://cloud.githubusercontent.com/assets/4913946/17091214/3512abea-51d4-11e6-9a3d-49345a75a399.JPG)

**Comment by iskess** [comment]
Also, the Camera Setup page doesn't allow any channels above RC11. Not a really an issue because I can set up in the full parameters, but thought I would mention it.

I can't think of any work around for manually activating a servo, and still having it available for DO_SET_SERVO. To my knowledge there is no way to use my RC transmitter to move a servo once allowing the APM to control it.  This Servo control tab is the only way I know.

**Comment by meee1** [comment]
added
