### ISSUE TITLE
Gimbal config screen on latest beta - WIP ??

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1322]
<img width="1349" alt="screen shot 2016-08-03 at 22 51 01" src="https://cloud.githubusercontent.com/assets/3130363/17388328/66f8d61c-59f3-11e6-90e4-4946c101154d.png">

I would assume a WIP issue ??

**Comment by meee1** [comment]
thanks for this report. now fixed.

**Comment by lvale** [comment]
Thanks Michael :)
