### ISSUE TITLE
Tracker: extended tuning page PITCH_RANGE to PITCH_MIN, PITCH_MAX

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1324]
Tracker version 1.0.0 (now released) replaced the PITCH_RANGE parameter with two new parameters, PITCH_MIN and PITCH_MAX.

![tracker_pitchminmaxangle](https://cloud.githubusercontent.com/assets/1498098/17471405/d5c2ebf8-5d7e-11e6-87cb-bc7d36125f34.png)

**Comment by meee1** [comment]
added

**Comment by rmackay9** [comment]
thanks!
