### ISSUE TITLE
add NAV_DELAY to Copter's list of mission commands

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1325]
Copter-3.4-rc2 (and higher) support the NAV_DELAY mission command.  It would be nice to have it added to the Flight Plan screen's Command drop-down.

93	MAV_CMD_NAV_DELAY	Delay the next navigation command a number of seconds or until a specified time
	Mission Param 1:   Delay in seconds (decimal, -1 to enable time-of-day fields)
	Mission Param 2:   hour (24h format, UTC, -1 to ignore)
	Mission Param 3:   minute (24h format, UTC, -1 to ignore)
	Mission Param 4:   second (24h format, UTC)

Plane and Rover do not support this command at the moment.

**Comment by meee1** [comment]
added.
