### ISSUE TITLE
DataFlash viewer events 62, 63, 64

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1331]
Copter-3.4 adds these events some of which at least are not showing up in the MP's dataflash viewer.
#define DATA_EKF_ALT_RESET                  60
#define DATA_LAND_CANCELLED_BY_PILOT        61
#define DATA_EKF_YAW_RESET                  62
#define DATA_AVOIDANCE_ADSB_ENABLE          63
#define DATA_AVOIDANCE_ADSB_DISABLE         64

![ev](https://cloud.githubusercontent.com/assets/1498098/17684911/54338ab2-639a-11e6-9f7c-2cb7ebdb0787.png)

**Comment by meee1** [comment]
fixed.

**Comment by rmackay9** [comment]
great, thanks!
