### ISSUE TITLE
Full Parameter Tree can't write more than one parameter at a time

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1332]
It seems that if I update 3 parameters on the full parameter tree page and then push the Write Params button they are not saved.  Also even if I tab away and back to the page, or push refresh, the green highlighting remains around the changed parameters.
If I shut down the mission planner, restart and write then individually I can save them.
![cantwrite3parms](https://cloud.githubusercontent.com/assets/1498098/17721672/2193ece6-6467-11e6-8d74-0f1b61a21778.png)

I'm using the latest beta Mission Planner and Copter-3.3.3.

**Comment by meee1** [comment]
fixed.

**Comment by rmackay9** [comment]
Thanks.  I've tested and it works.

One issue I've noticed is that pressing the "Refresh Params" button doesn't clear the green highlighting.  Maybe I'll create a new issue for that.
