### ISSUE TITLE
CRITICAL BUG: missions planning is defaulting to absolute alt

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/MissionPlanner#1333]
Using Flight-Plan tab, the altitude pull-down is defaulting to ABSOLUTE instead of RELATIVE. This is causing me instant SITL crashes because I didn't notice this change. Could definitely happen to real aircraft too. 

This happened when switching to the latest v1.3.9.1 beta.

Please fix ASAP!

**Comment by meee1** [comment]
ive had a good look at the logs provided, i can see they where uploaded as absolute. MP always prompts when a mission is uploaded as absolute.

**Comment by magicrub** [comment]
I guess it was just user error then. Sorry! Thanks for your time looking through and understanding it.
