### ISSUE TITLE
Geo Fence with Copter 3.4 master

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1336]
<img width="642" alt="screen shot 2016-08-19 at 01 09 22" src="https://cloud.githubusercontent.com/assets/3130363/17794798/73809344-65aa-11e6-8d1f-f5392ab6e95c.png">
Michael, something broke on the last MP update.

Every time I try to enable GeoFence always asks me to update param F5, and I do it every time. Even went to CTRL F Param Gen and still the same result.

Plus, on the Flight Plan screen I'm now unable either to retrieve a pre existing Geo Fence or create a new one

**Comment by meee1** [comment]
@lvale what version of copter where you using?

**Comment by lvale** [comment]
3.4 master

**Comment by rmackay9** [comment]
I think this is all fixed now because that parameter is no longer the special enable/disable hide thingmy.
