### ISSUE TITLE
MP - Unable to do setup Polygon fence

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1346]
Latest release of MP beta with latest master of Copter 3.4

Unable to create Polygon fence

<img width="1188" alt="screen shot 2016-08-27 at 17 06 37" src="https://cloud.githubusercontent.com/assets/3130363/18029300/3e5a27e6-6c8c-11e6-8b2d-826c87deb04a.png">

**Comment by magicrub** [comment]
"Latest master" or "current beta" doesn't help when this is seen 2
weeks/months/years from now. What version number?

**Comment by lvale** [comment]
Top bar of MP
Copter 3.4dev from 24-8-2016

**Comment by meee1** [comment]
I just tested and everything looks fine.
did you connect via a non standard method?
            if (MainV2.comPort.MAV.param["FENCE_ACTION"] == null)
            {
                CustomMessageBox.Show("Not Supported");
                return;
            }

also could be the FENCE_ENABLE issue.

**Comment by lvale** [comment]
Connection was via USB on this screenshot, because I had tried previously via telem radio also unsucessfully.
