### ISSUE TITLE
FlightGear Simulation and HIL support removed from current build of Mission Planner

### ISSUE THREAD

**Issue by kngako** [ArduPilot/MissionPlanner#1348]
"The issue for us with SITL vs HIL is where the code runs: in SITL, the code runs on the PC, and not on the APM. In HIL the code runs on the APM."

Testing APM with Flightgear can no longer be implemented since the code was removed in the commit 7044c1a6509a84698bda9a833e4fd077364ce2e5. 

Uploading HIL Simulation also isn't seen anymore on the Install Firmware Tab. 

How will these two functionalities be supported in future?

**Comment by meee1** [comment]
they are being replaced by sitl. the current sim of choice is also x-planes.

Support for flightgear might return, support for HIL will not return.

**Comment by kngako** [comment]
Hmm... thanks for the heads up.

**Comment by kngako** [comment]
Can I ask what are the reasons for taking it out?

**Comment by meee1** [comment]
because support from the firmware is being removed.
this all has to do with the amount of data that needs to be sent between the pc and the autopilot to make it work. the connection is not fast enough.

**Comment by kngako** [comment]
thank you
