### ISSUE TITLE
Links in readme are leading to 404

### ISSUE THREAD

**Issue by mfuhrmeister** [ArduPilot/MissionPlanner#1351]
Links to Forum, Download, msysgit & DirectX are leading to a 404 site or redirect.

**Comment by magicrub** [comment]
where are those links located in Mission Planner?

**Comment by mfuhrmeister** [comment]
As the title indicates... in the README.md. Sorry, i should have pointed that out in the description too.

**Comment by meee1** [comment]
fixed, thanks
