### ISSUE TITLE
Camera drop down missing

### ISSUE THREAD

**Issue by FLYBYME** [ArduPilot/MissionPlanner#1358]
I have an issue where the camera drop down has noting in the list not even the camera that is currently selected.

Is this a bug or a problem Im having?
Im running 1.3.40

![camera-options](https://cloud.githubusercontent.com/assets/339283/18610808/d74f3a50-7cf3-11e6-9f88-71a2adba8107.png)

**Comment by meee1** [comment]
its a bug, thanks for the report

**Comment by FLYBYME** [comment]
Also the aircraft drop down does not work.

**Comment by meee1** [comment]
please try do another MP update

**Comment by meee1** [comment]
ive updated just the plugins, as they where the issue.

**Comment by FLYBYME** [comment]
Cool thanks it works now.
