### ISSUE TITLE
Downloading datalogs over mavlink issue

### ISSUE THREAD

**Issue by qmayberry** [ArduPilot/MissionPlanner#1359]
I get the attached screenshot error when trying to download the datalogs from mission planner over the mavlink. Used to work fine until upgrade to version 1.3.39.
![apm error](https://cloud.githubusercontent.com/assets/3246161/18613341/4476d490-7d70-11e6-8664-67a590941bb9.JPG)

**Comment by meee1** [comment]
please see https://github.com/ArduPilot/MissionPlanner/issues/1356
