### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void MissionPlanner.Controls.HUD.set_gpsfix2(Single)

### ISSUE THREAD

**Issue by clovett** [ArduPilot/MissionPlanner#1363]
Fresh install of Mission Planner on clean Windows 10 machine and I get this error:

"A Major error has occured : System.MissingMethodException: Method not found: 'Void MissionPlanner.Controls.HUD.set_gpsfix2(Single)'.
at MissionPlanner.GCSViews.FlightData.InitializeComponent()
   at MissionPlanner.GCSViews.FlightData..ctor() in C:\Users\michael\Source\Repos\MissionPlanner\GCSViews\FlightData.cs:line
175
   at MissionPlanner.MainV2..ctor() in C:\Users\michael\Source\Repos\MissionPlanner\MainV2.cs:line
652"

Oddly enough that property exists, in Hud.cs.  Did you publish the wrong version of something?  if I run MissionPlanner.sln myself on the same system it runs fine.

**Comment by meee1** [comment]
@clovett  msi or zip? I assume msi.

**Comment by meee1** [comment]
the gac isn't coming into play here either?

**Comment by clovett** [comment]
uninstall and reinstall (using this msi link) into a clean directory now works, thanks (it is possible I installed newer bits into a directory that already existed and that may have caused problems).
