### ISSUE TITLE
AltitudeAngelWings build error.

### ISSUE THREAD

**Issue by clovett** [ArduPilot/MissionPlanner#1364]
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4106,5): error MSB3030: Could not copy the file "D:\git\MissionPlanner\ExtLibs\AltitudeAngelWings\Keys.config" because it was not found.

**Comment by magicrub** [comment]
does that file exist?

**Comment by meee1** [comment]
its not included on purpose, check .gitignore. however I think I may need to add some placeholder, as this I now the seconds notice I have received about this

**Comment by clovett** [comment]
They way I do private machine signing is to create an environment variable on that machine which is picked up by VS like this:
<AssemblyOriginatorKeyFile>$(MyKeyFile)</AssemblyOriginatorKeyFile>

This way if that variable is not defined then the project builds just fine, just won't be signed.  For app.config you could potentially create the included keys.config from MSBuild when some environment variable is set.  By the way I couldn't see where that MapKey is actually used in the code, and there's another mapkey in Mapbox.cs.

**Comment by meee1** [comment]
this should be resolved now. remove ref from project file
