### ISSUE TITLE
VS F5 run after upgrade fails 

### ISSUE THREAD

**Issue by clovett** [ArduPilot/MissionPlanner#1365]
Moving file from 
D:\git\MissionPlanner\bin\Debug\config.xml
to
d:\Users\Chris\Documents\Mission Planner\config.xml
fails
Additional information: Cannot create a file when that file already exists.

Line 233 of Settings.cs.

Perhaps the answer is to do a copy then delete the old file to be sure we don't reenter this code path.
                File.Copy(path,newpath, true);
                File.Delete(path);

**Comment by magicrub** [comment]
does a clean build work?

**Comment by meee1** [comment]
@clovett can you report back as to what state the files are in?
considering the first run is a move, I'm not sure how the file can still exist in the original location. if you can highlight why that may be that would be great.

**Comment by meee1** [comment]
@clovett never mind, "multiple installs" is the concept I was not thinking of.

**Comment by clovett** [comment]
Thanks.
