### ISSUE TITLE
LogBrowser dublicate log items

### ISSUE THREAD

**Issue by Fossdal** [ArduPilot/MissionPlanner#1367]
In LogBrowser if you click on the name of one item and not the checkbox, the item is added to the graph window even if it allredy is there 
![missionplanner log bug](https://cloud.githubusercontent.com/assets/15619646/18809078/4051553e-826b-11e6-9280-f2c5d7f5f984.png)

**Comment by magicrub** [comment]
That whole mechanism gets silly sometimes.. using same colors and also the
duplicates.

**Comment by meee1** [comment]
both these issue should be resolved in beta
