### ISSUE TITLE
Mission Planner Crashes when executing in Debug mode

### ISSUE THREAD

**Issue by ArvindShankar** [ArduPilot/MissionPlanner#1369]
Hi All,

When running in debug mode if selected option is "Survey (Grid)" option of "Auto WP" in the ContextMenu of "Flight Planner" application crashes.

I think MissionPlanner.Grid.dll to be called which is in plugins directory.

Please suggest do I have to make any changes in my project settings.

This issue occurs in Debug as well as in Release mode.

Looking forward for solution to this issue.
Thank you for your time.

**Comment by meee1** [comment]
please try a clean, and rebuild all.

**Comment by meee1** [comment]
please try a clean, and rebuild all.

**Comment by ArvindShankar** [comment]
Thanks for the reply.
Code is up and running now.
