### ISSUE TITLE
Log Analyser crashes runner.exe

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1370]
When trying to execute Auto Analysis, from the DataFlash tab, Log Analyser /runner.exe crashes

Latest beta, as in the screenshot

Logs are from Copter 3.4RC5 and trying to use the log file (not the bin)

<img width="1183" alt="screen shot 2016-09-28 at 22 00 26" src="https://cloud.githubusercontent.com/assets/3130363/18932258/70391f20-85c7-11e6-8996-536846043924.png">

<img width="1169" alt="screen shot 2016-09-28 at 22 05 01" src="https://cloud.githubusercontent.com/assets/3130363/18932296/ab2ececc-85c7-11e6-9d3c-46e4cc6c0cc0.png">

**Comment by meee1** [comment]
does it happen on all 3.4-rc5 logs?

**Comment by lvale** [comment]
Hi, sorry but forgot to mention that the logs were from 3.4RC5. I try to analyse a converted log, not a bin, if that helps.

**Comment by estebanavv** [comment]
This happens to me too using Mission Planner 1.3.41 and the log from ArduPlane V3.5.3 (b8461671) .bin log

**Comment by Fossdal** [comment]
same at this bug #1315

**Comment by magicrub** [comment]
Luis, please close this issue on favour of the other original issue

**Comment by lvale** [comment]
Closed because similar to https://github.com/ArduPilot/MissionPlanner/issues/1315
