### ISSUE TITLE
Overlaping of quadcopter and plane

### ISSUE THREAD

**Issue by pedroalmoutinho** [ArduPilot/MissionPlanner#1389]
Hello,

I am seeing an issue that I can not solve. I already googled but I stil have no solution for this weird situation.

In the initial screen appears a quadcopter and a plane, but the versian is for Plane.

Can anyone tell me what am I doing wrong.
![mission_planner](https://cloud.githubusercontent.com/assets/16958963/19413305/2fe33aac-9321-11e6-95c1-03db97c642c7.png)

**Comment by magicrub** [comment]
Have you tried latest mission planner and latest arduplane?

**Comment by pedroalmoutinho** [comment]
Finally I solved the problem. The problem was not with Mission Planner. I also tried with MavProxy and I also noticed the problem.

The problem was that I was using a 3dr radio for telemetry, but now I changed to a laird module (2.4ghz), like XBee. I forgot to disconnect tx from telemetry. With Xbee radios just connects rx, ground and +5v.

My fault, sorry!!
