### ISSUE TITLE
joystick.loadconfig() use wrong xml path

### ISSUE THREAD

**Issue by chobitsfan** [ArduPilot/MissionPlanner#1399]
in joystick class, loadconfig(string joystickconfigbutton, string joystickconfigaxis)

it prefix this.joystickconfigbutton with user directory
this.joystickconfigbutton = Settings.GetUserDataDirectory() + joystickconfigbutton

but later when load xml, it still use local , not updated variable
StreamReader sr = new StreamReader(joystickconfigbutton)

here, joystickconfigbutton is not this.joystickconfigbutton. Because there is a local joystickconfigbutton declared

**Comment by gediminasgu** [comment]
I have created PR for this already #1397

**Comment by chobitsfan** [comment]
#1397 fix this problem, thanks a lot
