### ISSUE TITLE
Missing Parameter Descriptions

### ISSUE THREAD

**Issue by Code-Tester** [ArduPilot/MissionPlanner#1412]
I can't see my Parameter Descriptions and Units in the Mission Planner when i add new Parameter in the ArduCopter Firmware. I have tried to modify the ParameterMetaDataBackup.xml File without success. 

Normally it should work, right?

What i have to do? Is it necessary to recompile the MissionPlanner with new Descriptions and Units?

I use the MissionPlanner Version 1.3.41

**Comment by magicrub** [comment]
Nope, that text is pulled from the internet from the latest release. Custom params will show the string and value but not description.

**Comment by Code-Tester** [comment]
Is there a way to change this? I mean the source for the "Descriptions", perhaps it will be better to have an own Parameter-File offline for the MissionPlanner. So everybody can modify his own file.

**Comment by meee1** [comment]
edit ParameterMetaDataBackup.xml in my documents > mission planner.

**Comment by Code-Tester** [comment]
Thanks. This works for me.

**Comment by saintofinternet** [comment]
> 
> 
> edit ParameterMetaDataBackup.xml in my documents > mission planner.

what should be edited in that file?
