### ISSUE TITLE
DO_DIGICAM_CONTROL mission command is sending ShutterCmd and CommandID x 10,000,000

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1413]
With the arrival of AC3.4, the Do-Digicam-Control mission item is being corrupted when stored/saved to ardupilot.  I've investigated and it seems that when MP sends a mission_item_int (http://mavlink.org/messages/common#MISSION_ITEM_INT) it is multiplying the x and y fields by 10,000,000.  This makes sense for commands in which those fields hold lat/lon but this command uses those fields for different purposes so they shouldn't be multiplied by anything.

The issue is raised and discussed here: http://discuss.ardupilot.org/t/apm-copter-v3-4-2-rc2-the-command-do-digicam-control-does-not-trigger-the-servo-camera/12816

And here's the corresponding ArduPilot issue: https://github.com/ArduPilot/ardupilot/issues/5215

**Comment by Seidenschwang** [comment]
There exists already a commit in the File "MissionPlanner/Mavlink/MAVLinkInterface.cs" from Oborne:

["MAVLinkInterface: dont scale x,y for digicam mission items"](https://github.com/ArduPilot/MissionPlanner/commit/442fea05420528d1a0bfd012fa9d30c97202ac48#diff-3d22e8b9c35a62cf3528da7c9a5d5198)

**Comment by samucs** [comment]
Hi, is this fixed for Mission Planner 1.3.43?

**Comment by Seidenschwang** [comment]
Sorry, the problem still exists. 

When i create a mission with DO_DIGICAM_CONTROL it needs the ShutterCMD with number "1". After writing the mission via USB to the Pixhawk (Write WP's) i clear the mission in the planer and click "Read WPs". Then i receive the ShutterCMD with "1E-07" :-(

Here the screenshots:
**Before upload:**
![2017-01-07 16_13_11-mission planner 1 3 43 2 build 1 1 6216 20043 apm_copter v3 4 2 6076bdfc -before](https://cloud.githubusercontent.com/assets/17014641/21742756/ffc963b2-d4f4-11e6-9088-e6e440f0033d.png)

**After download:**
![2017-01-07 16_14_04-mission planner 1 3 43 2 build 1 1 6216 20043 apm_copter v3 4 2 6076bdfc -after](https://cloud.githubusercontent.com/assets/17014641/21742761/180f6098-d4f5-11e6-9713-8ee0b0c827d3.png)

**Used versions:**
MissionPlanner 1.3.43.2
ArduCopter V3.4.2

**Comment by meee1** [comment]
@Seidenschwang  thanks for the report, I can confirm its a display bug, it saves it as 1, but displays it wrong. I will post a fix very soon

**Comment by rmackay9** [comment]
this is long since fixed I think.
