### ISSUE TITLE
Mavlink decoding race condition?

### ISSUE THREAD

**Issue by mredstall** [ArduPilot/MissionPlanner#1418]
We experience an intermittent issue where mission planner reports a disarm/arm cycle during flight (the flight controller is unaffected, this is a mission planner _reporting_ issue). The behaviour is present but not deterministic during log replays.

Looking at the code which updates armed status via heartbeat messages, at break-point the issue seems to be illustrated in the screenshots below. the contents of `hb` are all zero despite the assignment from `mavLinkMessage` which has non-zero values.

![racecondition1](https://cloud.githubusercontent.com/assets/23462482/20776267/581a7fea-b7c4-11e6-84a0-e9b21e2add94.jpg)
![racecondition2](https://cloud.githubusercontent.com/assets/23462482/20776274/5f830ebe-b7c4-11e6-8253-1c0f6a9ca24a.jpg)

**Comment by meee1** [comment]
I would be interesting to see the contents of mavlinkmessage.buffer, under the bad state.

just trying to determine what part is failing, I assume the structure conversion. but I could be wrong.

any chance of capturing that?

**Comment by mredstall** [comment]
Is this what you were after?

![racecondition3](https://cloud.githubusercontent.com/assets/23462482/20782233/d6671dde-b7ee-11e6-9996-305b8fbbdb95.jpg)

**Comment by meee1** [comment]
yes and no.

to determine whats actually failing really need to see if its the object creation that's causing the issue.

I have a feeling mavutils.ByteArrayToStructure is failing, but I want to know whats going into that function for it to fail. its in charge of converting the byte array to the structure. and could explain the results. but I still would like to know the cause. so I can address that

how are you creating this scenario? maybe I can recreate?

**Comment by mredstall** [comment]
I am creating the scenario through log playback with a log that has confirmed instances of the issue occurring (it was first evident during live flight, this is what brought our attention to it). During the period between 60-80% of the way through the log file play back it occurs (at different points) at least once more often than not. I could send you through the log file for you to use if you would like?

**Comment by magicrub** [comment]
Yes, please link us to the log.

**Comment by mredstall** [comment]
https://www.dropbox.com/s/gx038l8ku1m09qk/2016-11-11%2015-45-07.tlog?dl=0

**Comment by jmachuca77** [comment]
I have experienced this same issue on several flights.

**Comment by meee1** [comment]
@mredstall can you test the latest changes. I think its fixed.

ive added a lock around the entire packet struct creation, as I believe the null check was returning a created blank packet.

**Comment by mredstall** [comment]
Issue appears to be fixed. I have played through the log file several times and have not been able to recreate the issue.

**Comment by meee1** [comment]
@mredstall thanks for reporting back.
