### ISSUE TITLE
Show only onboard compass calibration when vehicle has the capability

### ISSUE THREAD

**Issue by OXINARF** [ArduPilot/MissionPlanner#1422]
With https://github.com/ArduPilot/ardupilot/pull/5325 merged to master, I'd love to see the live calibration be hidden away and only show the onboard one (maybe with a button to show the live calibration if a user really wants it).

**Comment by proficnc** [comment]
Please +1 to this... people appear to think these are both the same... but they are not.. 

for Pixhawk 2.1, i would prefer people only used the onboard calibration... Thanks

**Comment by OXINARF** [comment]
Fixed with c409c1a5f3f7c678e3edf03dc4f27a3bcfabee7c and cfed796bee77143d784c34ce69c1b7fe0a854226
