### ISSUE TITLE
Can't theme UDP progress dialog box

### ISSUE THREAD

**Issue by mredstall** [ArduPilot/MissionPlanner#1424]
It is currently not possible to apply the theme to the ProgressReporterDialogue form that is called in CommsUdpSerial.cs whilst connecting using UDP. This is because it is called from a location that cannot get the scope of the theme manager.

**Comment by meee1** [comment]
fixed here
https://github.com/ArduPilot/MissionPlanner/commit/d517585535c2077c9277ac1b8ac1074a3779c287
