### ISSUE TITLE
Compass external/internal inconsistency

### ISSUE THREAD

**Issue by staroselskii** [ArduPilot/MissionPlanner#1427]
It seems like ["Compass 1 = External if present/else internal"](https://github.com/ArduPilot/MissionPlanner/blob/master/GCSViews/ConfigurationView/ConfigHWCompass.ko-KR.resx#L139) is not relevant anymore or at least very [confusing](https://community.emlid.com/t/external-compass-questions/4422/4).
![image](https://cloud.githubusercontent.com/assets/4541230/21090902/e8880e3e-c053-11e6-9a76-ba320b34df16.png)

I suggest to remove or rephrase. Thanks!

**Comment by meee1** [comment]
removed, thanks
