### ISSUE TITLE
"Unexpected error" trying to upload mission

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/MissionPlanner#1428]
I'm at home, getting ready to fly, of course no GPS. Click on 'Write WP' and got

![mp-wp](https://cloud.githubusercontent.com/assets/6255710/21169789/8ab3e5fc-c1e9-11e6-8cd5-a3f1b97f3123.png)

**Comment by meee1** [comment]
please set your home location. right hand side under the write wp button.

**Comment by night-ghost** [comment]
What a speed of closing!

Why I need to set FAKE home location when I try  just to write WPs? I do not know where I'm going to fly, so the return is to be on the point of Arm, not to there where I write WP.

**Comment by night-ghost** [comment]
moreover, it would be better to make a more clear diagnosis than "unexpected error"

**Comment by meee1** [comment]
because home is sent as part of the wp upload. always has been.

ill look at making the error nicer

**Comment by night-ghost** [comment]
fresh controller, city apartment - MP may not have the coordinates! In this case, it is more logical to send NAN, NAN as coordinates -  the controller to knew that there is no Home point

**Comment by meee1** [comment]
MP requires you to set a home point for many of the display features/distance calcs. so no, home is REQUIRED.

**Comment by night-ghost** [comment]
But this REQUIRED value can be a NAN, yeah? MP is rather a tool for configuring and not for flight control, while Tover is more suitable for the direct support of the flight.

So, it is illogical when the Configuration Tool for some reason requires coordinates. In the best case there is no coords, at worst, these coordinates are wrong, and the copter will remembers that point of "home" and fly away.

**Comment by rmackay9** [comment]
Just to be clear though, aside from whatever argument about functionality, I don't think Copter will fly away when doing the RTL.  the vehicle's home is normally set on arming.  It is possible to set it from the ground station as well, but I'm unsure whether that is set when someone does/doesn't click on the home fields in MP.

**Comment by night-ghost** [comment]
I wish to hear it! So, you agree that the requirement to specify the home point to upload mission is excessive because it will be replaced on Arming?

**Comment by meee1** [comment]
@night-ghost you can set your home as 0,0,0 if you want. that is your choice, and MP will accept that.

**Comment by meee1** [comment]
added message here
https://github.com/ArduPilot/MissionPlanner/commit/c836f7f2c8b1ba0cd21f533b1083de135500b994
