### ISSUE TITLE
Identify the .tlog files that were from an actual flight, not just the bench

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#143]
I spend a too much time digging through .tlog files trying to weed out the useless ones and locate the ones from an actual flight. Since I am frequently bench testing, I generate far more tlogs than I need.
Is there a way that the names of the .tlog files can somehow be annotated based on whether the APM actually flew? I'll let you guys decide the best triggers since they are likely to be different for Copters and Planes. 
What if every .tlog file name included the total distance traveled and highest altitude reached. It might look like this: 
2013-08-22 12-23-21 1200m125m.tlog
This flight's trip distance was 1200 meters, and the max altitude achieved was 125 meters.
This is just an idea, perhaps others have better ideas of what data to include in the file names to help identify the logs we need.

**Comment by meee1** [comment]
check out logindex. control-f
