### ISSUE TITLE
Copter: LOG_WHEN_DISARMED Checkbox doesn't work with AC3.4

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/MissionPlanner#1437]
The LOG_DISARMED checkbox in the Standard Parameters page does not toggle the LOG_DISARMED parameter.  Instead is probably toggles the old logging bitmask bit.

**Comment by meee1** [comment]
ive updated the base param meta data
https://github.com/ArduPilot/MissionPlanner/commit/ec2c4b25c686f52d92843e2bd1e22ee85abfae33
however if you had done an update, this should have updated itself.
either way problem should be resolved with newest version

**Comment by rmackay9** [comment]
Great, thanks for this.

**Comment by R-Lefebvre** [comment]
Sorry, what do you mean "done an update"?  I think my MP install was updated.

**Comment by meee1** [comment]
if you had done an update since installing from either zip or msi, it should have resolved itself
