### ISSUE TITLE
Logfile variables explaination

### ISSUE THREAD

**Issue by BurnPlane** [ArduPilot/MissionPlanner#1438]
Hi everyone, where can I find the specific explaination of logfile variables for fixed-wing? Fixed-wing logfile variables are different from copter',like AHR2,ARSP,ATT,BARO,ect. thanks.
![fixed-wing logfile variables](https://cloud.githubusercontent.com/assets/24536379/21490061/721f918e-cc2b-11e6-9e6a-38795e597a6d.png)

**Comment by magicrub** [comment]
HowTo questions are best asked in the forum: discuss.ardupilot.org but since I know they are in the wiki, but old, I also suggest starting an issue on the wiki in GitHub too.

**Comment by BurnPlane** [comment]
thanks,magicrub, i'm a newbee for github, don't know how to start an issue, but still thanks.

**Comment by magicrub** [comment]
This is an issue. You just made one in mission planner.

**Comment by rmackay9** [comment]
I might close this one.  It's not really a mission planner thing, but rather a Plane wiki thing..

**Comment by blowschoolup** [comment]
have you found the answer,i have the same question now
