### ISSUE TITLE
Connect tab defaults to UDP

### ISSUE THREAD

**Issue by timvand** [ArduPilot/MissionPlanner#1441]
With the update to v1.3.43, the connection defaults to UDP on startup, rather than last used connection type, as in previous version(s) v 1.3.41,

Why the change?  What's the fix to set it to use the last connection type used?

**Comment by meee1** [comment]
you are correct, I will fix

**Comment by meee1** [comment]
fixed here https://github.com/ArduPilot/MissionPlanner/commit/77c8ee5057aaf236634b620438e64ecc3bb0dbc2
