### ISSUE TITLE
Heli: setup window doesn't works correctly on firmware 3.4.3

### ISSUE THREAD

**Issue by Fortesque0** [ArduPilot/MissionPlanner#1444]
Hello, 
I opend this issue because seems to be a mission planner issue (see ardupilot opened issue too).
On heli setup window, with firmware 3.4.3 traditional heli, it's not possible to trim or reverse the servos of swash plate. I have not test all window options, but seems to be bad too.
Thanks

**Comment by magicrub** [comment]
Here is the referenced Ardupilot issue https://github.com/ArduPilot/ardupilot/issues/5471
