### ISSUE TITLE
Proximity view's distances are hard to read

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1453]
It's very helpful to see the proximity viewer when flying close to objects but normally I need to increase the size of the window in order to see it while flying (the default is very small).  When the window is resized the numbers don't increase in size meaning they're really tiny and difficult to read from a distance.  Maybe it would be good to resize them if the window is really big.

![proximityview_smallnumbers](https://cloud.githubusercontent.com/assets/1498098/21874559/f67f36de-d8b8-11e6-958e-dba96a490c0f.png)

**Comment by meee1** [comment]
changed. thanks
