### ISSUE TITLE
build name changed from ArduCopter-frame to just ArduCopter

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#1456]
Hi Michael,
In master we now build just two binaries for copter, one for heli and one for everything else.
So you'll notice the directories have changed here:
http://firmware.ap.ardupilot.org/Copter/latest/
and binary names have changed.
This will likely also be in the copter 3.5 release.
Can you fix control-Q so it copes with the new binary names?
Thanks!
ping: @rmackay9

**Comment by meee1** [comment]
updated thanks
https://github.com/ArduPilot/binary/commit/dbe43bcac1cc56755dfc22e7f918f66db791ab1a
