### ISSUE TITLE
Add note beside Compass calibration's Fitness drop-down

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1459]
People don't seem to be getting the message that they can reduce the compass calibration "fitness" in order to complete the compass calibration.  This note in red makes it a bit more obvious.
![compass_relaxfitness](https://cloud.githubusercontent.com/assets/1498098/22170021/7c1a1c32-dfbc-11e6-9fb5-6705fc4e1857.png)

**Comment by OXINARF** [comment]
That might make people relax it to the maximum instead of fixing any issue they have.

**Comment by rmackay9** [comment]
@OXINARF, yes, i've relaxed it for the pixracer board anyway..

**Comment by meee1** [comment]
changed
