### ISSUE TITLE
Compass orientations list could come from COMPASS_ORIENT

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1464]
It looks like the Initial Setup >> Mandatory Hardware >> Compass screen's orientation drop-down uses a hardcoded list of orientations instead of using the COMPASS_ORIENT parameters descriptions.  This means that a few possibilities are currently missing like Solo's 38.

By the way, if we don't like the current wording of the COMPASS_ORIENT's options we can change them.

**Comment by proficnc** [comment]
Thanks Randy
for 38, we should just label that as "Solo" as it is special for it.

**Comment by meee1** [comment]
modified here
https://github.com/ArduPilot/MissionPlanner/commit/e0cd54df76fd10db242cc7f041552fc3994ad32a

using the name from the parameter doc
