### ISSUE TITLE
About flight mode...Am I Right?

### ISSUE THREAD

**Issue by trigger1996** [ArduPilot/MissionPlanner#1466]
http://ardupilot.org/dev/docs/apmcopter-adding-a-new-flight-mode.html?highlight=flight%20mode
This official paper says we should modify MP ourselves, but I've tried another way, that is,  we can modify the parameters in the original MP in this place, changing the selected flight mode ourselves.
Tested, seems OK, but am i right?
![default](https://cloud.githubusercontent.com/assets/24710213/22460150/9d1c7680-e7de-11e6-9b68-d452b3778d98.png)
![default](https://cloud.githubusercontent.com/assets/24710213/22460249/ea795420-e7de-11e6-9e43-5b3e212a1e64.png)
Sorry for Chinese windows, may get you confused.

**Comment by trigger1996** [comment]
First time using this, I put in the image twice.. -_-||

**Comment by meee1** [comment]
yes, putting in the number will work fine.
it just will not display the correct name on the hud.

**Comment by trigger1996** [comment]
Thanks, I fogot about this.
I just thought that it were impossible to select it in MP.

**Comment by meee1** [comment]
you can modify paramatermetadata.xml file, and add your own mode, that will be used inside missionplanner.
