### ISSUE TITLE
Ghost vehicle appears at lat,lon 0,0 if companion computer attached

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1472]
During recent tests of object avoidance using a companion computer, the MP showed a 2nd vehicle at lat,lon 0,0.  I think the issue was that on the companion computer OpenKai was running and also sending heartbeats.  The sys-id in those heart beats was the same as the vehicle but the component-id was different (MAV_COMP_ID_PATHPLANNER = 195).

I don't think MP should try to show the position of a component if it's not a vehicle.

**Comment by meee1** [comment]
resolved
