### ISSUE TITLE
Request: Command-line options

### ISSUE THREAD

**Issue by ijustwant** [ArduPilot/MissionPlanner#1480]
A command-line startup of MP where i at least can wait for UDP 14550 and select fullscreen.

**Comment by meee1** [comment]
latest beta mp will automaticlly connect to anything sending to udp 14550

**Comment by meee1** [comment]
https://github.com/ArduPilot/MissionPlanner/commit/e1a4e7cab974e1b3c42867e28b4a9bf8c6daf678
