### ISSUE TITLE
Pixhawk Mini only 2 motors arm

### ISSUE THREAD

**Issue by maddmackx** [ArduPilot/MissionPlanner#1484]
Hello,  I have uploaded the beta firmware and performed all calibrations etc.  (all componets have been tested and verified as working)  However, the mini does not send any signals to motors 3 and 4 and the motor just beeps waiting for a signal to be received from the FC.

If I switch the motor outputs around 1-3, 2-4 it does the same thing except to the different motors beep instead obviously.

My partner also has the same problem with his mini that we purchased at the same time except his is opposite to mine where his motors 3 and 4 spin but motors 1 and 2 just beeps.

**Comment by rmackay9** [comment]
You've calibrated the ESCs?
If this is the 3DR Pixhawk Mini I think you'll need to use AC3.5 which is in beta testing.
By the way, support issues should go into the forums.  http://discuss.ardupilot.org/c/arducopter
