### ISSUE TITLE
Sensor/Lidar/Rangefinder vs Baro only shows baro

### ISSUE THREAD

**Issue by OlivierJB** [ArduPilot/MissionPlanner#1490]
In "pre-made" graphs, drop down menu.
Tested on log with valid rangefinder data

**Comment by meee1** [comment]
did the log contain RFND messages?
the dropdown trys to graph 
BARO.Alt RFND.Dist1 RFND.Dist2

**Comment by OlivierJB** [comment]
Just checked, no. I guess I am confused. Thought the dropdown would compare Baro alt and Salt from CTUN?
Here are 2 displays from same log . MP 1.3.44.3
Also http://discuss.ardupilot.org/t/sonar-rangefinder-check/15366  ?

![dropdown](https://cloud.githubusercontent.com/assets/24396967/23576081/7714e5a2-0058-11e7-94b5-8a3362fed57f.jpg)
![altsalt](https://cloud.githubusercontent.com/assets/24396967/23576082/7a4a83ee-0058-11e7-8ae9-37f628075391.jpg)

**Comment by meee1** [comment]
ill add salt to the message list

**Comment by OlivierJB** [comment]
Sounds great, thanks!
