### ISSUE TITLE
Can't maximize HUD to full screen on 16:9 monitor

### ISSUE THREAD

**Issue by gediminasgu** [ArduPilot/MissionPlanner#1503]
#### Issue details
Steps to reproduce:
- Open mission planner
- On HUD click mouse right button and choose "Set Aspect Ratio", the HUD will change to 16:9 format
- Double click the HUD to have it as separate window and then try to maximize it, it will back to 4:3 format

#### Version
1.3.45

**Comment by gediminasgu** [comment]
I have fixed it in #1502

**Comment by meee1** [comment]
merged
