### ISSUE TITLE
Pixracer does not arm or connect to mission planner if sd card is missing

### ISSUE THREAD

**Issue by b70dub** [ArduPilot/MissionPlanner#1507]
#### Issue details
Pixracer does not arm or connect to mission planner if sd card is not inserted. 

#### Version
Copter V3.4.6

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
quad

#### Hardware type
pixracer

#### Logs
NA

**Comment by magicrub** [comment]
related to https://github.com/ArduPilot/ardupilot/issues/4661

**Comment by meee1** [comment]
this is not a MP issue. so closing
