### ISSUE TITLE
MP error on launch

### ISSUE THREAD

**Issue by chris669** [ArduPilot/MissionPlanner#1515]
#### Issue details
Hi, three weeks that I try to launch MP with no success. I desinstalled it and reinstalled. See the error message on the attached pict. Error that appears after some minutes...
I try other software like APM and QGC and I have not this problem. I forwared the error messages when I was invited to do that, but no answer at this time. It's possible that I desactivated some required by MP Windows services because I try to optimized my Windows.

#### Version
1.3.45

#### Platform
Windows 10 64bits
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
X4_

#### Hardware type
pixhawk

#### Logs
see pict

![image](https://cloud.githubusercontent.com/assets/15046400/24711731/16502712-1a21-11e7-9183-6295578626d3.png)

**Comment by meee1** [comment]
does MP continue to run after this error?

**Comment by chris669** [comment]
Ok, I have to wait around 4 minutes in order to be able to use MP. If I wait without doing nothing, I do not have the error displayed in the above printscreen. I was invited after the 4 minutes to download the latest version. Now running 1.3.4.6. It seems your app is looking for something that it couldn't find on my PC. A missing service? How can I help?

**Comment by meee1** [comment]
do you use windows 10 with a intel onboard graphics card?

**Comment by chris669** [comment]
Yes, Graphique HD Intel, on a HP

**Comment by hackra76** [comment]
One of the latest windows 10 updates breaks the Intel graphics driver, you have to reinstall it... It worked for me, I used the Intel driver update utility from Intel website.

**Comment by chris669** [comment]
Thanks a lot hackra76, that was the solution for me.
