### ISSUE TITLE
Enhancement- NMEA output Update Rate selector

### ISSUE THREAD

**Issue by SSUAV** [ArduPilot/MissionPlanner#1516]
#### Issue
Could an "Update Rate" drop down selector be added to the NMEA output options

#### Platform
[x  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

**Comment by magicrub** [comment]
Is this for input or output?

**Comment by SSUAV** [comment]
The CTL-G output

**Comment by meee1** [comment]
MP attempts to output at 5hz, and this is 100% dependant on the input stream rate. ie the location option in MP options stream rates

**Comment by SSUAV** [comment]
Thanks Michael,
I was hoping for something similar to the Follow Me Form.
My main motivation is the 2018 UAV Outback Challenge NMEA output requirement of a 1Hz update rate.

**Comment by SSUAV** [comment]
Cheers Michael,
That looks great!!
