### ISSUE TITLE
Bug: Survey tool Invalid Entry Error

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#1517]
#### Issue details
When pressing Accept in the Survey Tool, an error window appears that says, "A invalid entry has been detected, Invadid number on row 1".
There is on OK button but nothing happens when it is pressed. I can not dismiss the window. I had to use CTRL+ALT+DEL to get past the error. 

#### Version
MP 1.3.46

![image](https://cloud.githubusercontent.com/assets/4913946/24877355/a01e3b4e-1dca-11e7-8cd3-419157256576.png)

**Comment by iskess** [comment]
If I click OK enough times (one for each WP I presume), the dialog will disappear, but no flight lines will show. Downgrading to 1.3.45 resolves the problem

**Comment by meee1** [comment]
ok ive resolved this. and am pushing a replacement
