### ISSUE TITLE
Gstreamer Setup File Link generates uncaught exception

### ISSUE THREAD

**Issue by Loran425** [ArduPilot/MissionPlanner#1519]
#### Issue details
Mission Planner Detects a stream and brings up the new install/config prompt the link on this tab is broken

#### Version
1.3.46
build 1.1.6310.11669

#### Platform
[X] All 
[   ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
N/A

#### Hardware type
N/A

#### Logs
![gstreamer_error_box](https://cloud.githubusercontent.com/assets/7898215/24929843/13a4cd78-1ecd-11e7-802c-aa234425bd37.PNG)

[Gstreamer_install_link_error_log.txt](https://github.com/ArduPilot/MissionPlanner/files/914611/Gstreamer_install_link_error_log.txt)

**Comment by meee1** [comment]
this error normally indicates an issue on your pc. with the default browser association.
the link is this
https://gstreamer.freedesktop.org/data/pkg/windows/1.9.2/gstreamer-1.0-x86-1.9.2.msi

**Comment by Loran425** [comment]
Ahhh that sounds about right. I found the file just fine. Just wanted to make sure the error was noticed since that dialog is new with the release today.
