### ISSUE TITLE
Can't open MP on latest win10.

### ISSUE THREAD

**Issue by armadyne** [ArduPilot/MissionPlanner#1526]
Recently Microsoft pushed me the latest win10 update, after updating the system mission planner can not be used, it will crash when I start up, please help!

**Comment by meee1** [comment]
can you please post more info on the issue.
logs/screenshots etc
does it hang? does it not start at all? do you have an intel graphics adapter.

**Comment by armadyne** [comment]
Thanks for replying. I have already rolled back to the previous win10 version and MP is working again. My CPU is 4790K but I don't use integrated graphics card I use GTX970 instead. When using the latest win10 version it just crashed when I starts up.

**Comment by rmackay9** [comment]
I think we can close this because MP seems to be working fine on Win10.
