### ISSUE TITLE
MP - updater crashes

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1528]
Latest version of release MP on clean Windows 10

Trying to do the update by the Update to latest beta and Updater crashes

Reboot the machine and tried again, same issue

<img width="975" alt="screen shot 2017-04-23 at 16 41 11" src="https://cloud.githubusercontent.com/assets/3130363/25315553/bf4f7468-284e-11e7-9696-67c1d343e446.png">

**Comment by lvale** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<startup><supportedRuntime version="v2.0.50727" /></startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.Tracing" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reflection" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.InteropServices" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```


<img width="926" alt="screen shot 2017-04-23 at 18 52 23" src="https://cloud.githubusercontent.com/assets/3130363/25315977/13662dd8-2856-11e7-9190-151d75822740.png">

**Comment by rmackay9** [comment]
I've seen this as well actually.

**Comment by hackra76** [comment]
Happens to me also, Windows 10 after latest Creator update ....

**Comment by Rolf-G** [comment]
Happens to me also: win10

**Comment by meee1** [comment]
this should now be resolved. I think

**Comment by SSUAV** [comment]
Yep, Win 10. MP Crashing at startup
![mp](https://cloud.githubusercontent.com/assets/5088787/25521382/a2692f0e-2c42-11e7-80b6-f143611a8704.PNG)

**Comment by meee1** [comment]
@SSUAV different error than the original post
but partial related. are you running beta? 90% of these issues are beta issues

**Comment by SSUAV** [comment]
Yes, sorry about that. Reinstalled MP working good!! Thanks!!

**Comment by lvale** [comment]
sorted. closing. 
Thanks Michael
