### ISSUE TITLE
On Mono can only edit one parameter, then have to restart mission planner

### ISSUE THREAD

**Issue by foobarbecue** [ArduPilot/MissionPlanner#153]
If you edit a field, such as any of the parameters in the full parameter list, clicking on another field does not give you a cursor. You just get a blank box. Edits do not work until you close MP and open it again. I think there is an IndexError related to this; I'll post here if I get that error again.

This problem exists in 1.2.73 on Mono (Ubuntu 13.04 64 bit) but has been around for a few MP versions.

**Comment by meee1** [comment]
resolved i believe
