### ISSUE TITLE
PreFlight Checklist - Verify key parameters are set as desired

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#1535]
I moved this over from #1531 so it would track as its own item. 
I would like to check a few parameters before each flight, like the RTL altitude, whether Terrain Following is active, which Failsafe mode I'm in, the CAM settings, the correct battery mAh, etc. 
Is it possible to add the parameters to the list of variables to choose from so the checklist can display their value?
Thank you

**Comment by meee1** [comment]
yes it is
there is a special word "PARAM" that will return its value.
so FIELD = PARAM
and in Description put {PARAM_NAME}
and in value put {value}

**Comment by iskess** [comment]
Perfect! Thank you.
