### ISSUE TITLE
About Adding New No-Fly Zones

### ISSUE THREAD

**Issue by mustaphos** [ArduPilot/MissionPlanner#1544]
Hi. I want to add custom no-fly zone like of the airport list in the Mission Planner.
Where can i add my no-fly zones as lat, lon, radius?
Thanks for your answers.

**Comment by rmackay9** [comment]
This is not support yet I'm afraid.  It's on the to-do list however:
https://github.com/ArduPilot/ardupilot/issues/391
https://github.com/ArduPilot/ardupilot/issues/1056

**Comment by rmackay9** [comment]
Sorry, I thought this was on the ardupilot issues list but I see this could be a request to customise the list that Mission Planner shows for informational purposes to the pilot.

**Comment by meee1** [comment]
MP uses kml's to display the no fly zones. just place a kml inside the nofly directory
