### ISSUE TITLE
cache folder error on Linux

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/MissionPlanner#1545]
Using mono on Linux, (Ubuntu) , this error pops up every time:
- also - it does not quit - but runs after that.
if it's a temporary cache, it should be stored in /tmp  , otherwise somewhere in user config, like  ~/.config/missionplanner/cache

![screenshot from 2017-05-07 14-04-56](https://cloud.githubusercontent.com/assets/1468842/25780811/b8f8b4c2-332e-11e7-9714-2d7ac794df72.png)

**Comment by kikislater** [comment]
Still issue since October 2016 : 
https://github.com/ArduPilot/MissionPlanner/issues/1379

**Comment by AndKe** [comment]
thanks that confirms my impression of MP.
I saw a user recently claim that it worked fine in mono, so I thought there were maybe some attempts in the past years to get it out of the windows quagmire.

**Comment by kikislater** [comment]
It works with mono Linux but not as well as under windows. There is some bugs, you have to refresh panels by switching to different menu (example : if you don't have HUD in flight data, move to flight plan and revert back to flight data and you could get HUD or resize window). Some functions does not work as expected, so definitively could not use as a GCS on field under Linux.
LogAnalyser does not work. In that case, I use it only for flight plan. Qgroundcontrol should be better in the future : more cross platform GCS wit QT. 
We choose a prooven opensource platform but discover after using it that apm planner is not reliable (lack of functions) and we have to use a software (Mission Planner) under a non opensource operating system.

**Comment by AndKe** [comment]
thanks for sharing .
I am usually using AP2 , often flying in valleys and varying altitude, drawing mission manually. I recently started to try out QGC for planning,   using mavproxy + AP2 for flight monitoring. 
I use AP2 for log analysis, it's kind of perfect, fast and smooth solution even for big logs (many hours, and much data)

**Comment by meee1** [comment]
in current beta ive moved this folder if mono is detected.

**Comment by kikislater** [comment]
Got it working, thanks. 
Which mono version should we use ? 4.6 ?

**Comment by AndKe** [comment]
nope, does not work, and why not use /tmp for that ?   

![screenshot from 2017-06-28 20-30-23](https://user-images.githubusercontent.com/1468842/27653927-
e53ca954-5c40-11e7-84cc-82cdb0c6c06e.png)

**Comment by meee1** [comment]
@AndKe  are you using the latest beta?

**Comment by AndKe** [comment]
@meee1 - downloaded it yesterday from http://firmware.ardupilot.org/Tools/MissionPlanner/MissionPlanner-latest.zip
the attempt on /usr/share tells me it must be recent, not sure it "latest" equals "beta", or "stable"

**Comment by meee1** [comment]
nope, http://firmware.ap.ardupilot.org/Tools/MissionPlanner/beta/

**Comment by AndKe** [comment]
Beta works fine - thanks.
