### ISSUE TITLE
Survey grid: Distance between lines is wrong

### ISSUE THREAD

**Issue by StephBMG** [ArduPilot/MissionPlanner#1547]
#### Issue details
Survey grid: Distance between lines
#### Version
1.3.41, the distance is wrong (320m) - 1.3.37, the distance is right (480m)
![1 3 48](https://cloud.githubusercontent.com/assets/18239609/25782863/bbc31be4-335a-11e7-9314-5cca77495fa8.jpg)
![1 3 32](https://cloud.githubusercontent.com/assets/18239609/25782864/bbcedf42-335a-11e7-8615-62c05cd1cf06.jpg)

sidelap:65%

**Comment by meee1** [comment]
can you do a control-s and post the file it saves?

**Comment by iskess** [comment]
If this turns out to be a verified bug, could you let us know which versions were affected? I need to go back and check my surveys for accuracy. 
Thank you.

**Comment by StephBMG** [comment]
Sorry, my fault was not a bug: since V1.3.40, the "front facing camera" is not ticked by default, I did not see that, sorry
