### ISSUE TITLE
"Load custom firmware" does not appear

### ISSUE THREAD

**Issue by MR444** [ArduPilot/MissionPlanner#1554]
Cannot upload custom firmware. Buttons are gone in newest firmware.
#### Version
Newest

Using Win10x64 Education
![unbenannt](https://cloud.githubusercontent.com/assets/17322455/26035226/5d9297ec-38c9-11e7-8e7a-9314f10501b9.JPG)
How to change to english language? I dont like this language mixing.

**Comment by meee1** [comment]
goto MP settings.
 and change layout to advanced. 

then retry

**Comment by MR444** [comment]
Thanks for fast reply. Where can I find MP settings? I can not remember ever having changed this but I uploaded some beta firmwares last year. It is very confusing because the button appears first when checking for firmwares and is gone later:
![unbenannt2](https://cloud.githubusercontent.com/assets/17322455/26038669/e5724d80-390d-11e7-80b0-61a076ad3716.JPG)
![unbenannt3](https://cloud.githubusercontent.com/assets/17322455/26038670/e7546534-390d-11e7-9273-89f5bec67ab8.JPG)

Could you please add this information to manual? http://ardupilot.org/planner/docs/common-loading-firmware-onto-pixhawk.html

**Comment by rmackay9** [comment]
It's Config/Tuning >> Planner >> Layout drop-down
