### ISSUE TITLE
DsHot ESC Support in PixHawk

### ISSUE THREAD

**Issue by iskymaster** [ArduPilot/MissionPlanner#1564]
#### Issue details
Is it true that at this point PixHawk doesn't support DShot ESC's?

I saw an article on it before now I can't find it.

Is anyone working on adding Dshot support on PixHawk.

#### Version
2.4.8.

#### Platform
[  ] All
[  ] AntennaTracker
[x  ] Copter
[ x ] Plane
[ x ] Rover
[  ] Sub

#### Airframe type
QUAD

#### Hardware type
PixHawk 2.4.8

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
There's an issue over here to add support to ardupilot: https://github.com/ArduPilot/ardupilot/issues/5300

I don't think we have any special support for it yet.
