### ISSUE TITLE
Mission Planner 1.3.48 build 1.1.6330.31130 and APM 2 freeze while openning 

### ISSUE THREAD

**Issue by ozzcet** [ArduPilot/MissionPlanner#1568]
#### Issue details
OS win 10 
last update 2 days ago after that mission planner running. However yesterday suddenly when i try to open mission planner it freeze on splash screen. (not responding)
how is it fixed?

Inculuding APMPlanner 2 has same issue,

Best regards.

#### Version
Mission Planner 1.3.48 build 1.1.6330.31130 

#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

![image](https://user-images.githubusercontent.com/29270943/26915123-6fd802da-4c2d-11e7-839a-966292c1f407.png)

![image](https://user-images.githubusercontent.com/29270943/26915749-ef0118b0-4c2f-11e7-94f3-199ff4bacf71.png)

**Comment by meee1** [comment]
do you have an intel graphics card?

**Comment by ozzcet** [comment]
![image](https://user-images.githubusercontent.com/29270943/26920316-5349428c-4c41-11e7-87ce-c385f70f3128.png)

**Comment by ozzcet** [comment]
So? My friend how can i handle?  should i format my computer to setup again... i need to fix this to first autonomous fly, i am curious :-D

**Comment by ozzcet** [comment]
Now it is working :) but i dont know why :D :D  Thanks.

**Comment by amcmahon01** [comment]
I am having the same problem on Windows 7 (with Intel Graphics 530 and AMD Radeon R9 M375X) but have been unable to resolve it.  The latest version that works for me is 1.3.44.

**Comment by amcmahon01** [comment]
Updating the AMD driver solved it.  I was previously running 15.30.1025 and have now updated to 17.10.1731.

**Comment by ozzcet** [comment]
First time i get a chance to debug , and i get this ....

![image](https://user-images.githubusercontent.com/29270943/27255036-0b6aa33e-539e-11e7-986f-a4b095c06f7e.png)
