### ISSUE TITLE
Mission planner - Firmware 1.3.39.msi    -file corrpted- ? 

### ISSUE THREAD

**Issue by Sas-LAB** [ArduPilot/MissionPlanner#1569]
#### Issue details
Looking at the folowing link. 
http://firmware.ap.ardupilot.org/Tools/MissionPlanner/archive/

Tried to download the firmware version 1.3.39
http://firmware.ap.ardupilot.org/Tools/MissionPlanner/archive/MissionPlanner-1.3.39.msi

Try to execute this file at windows 10 I get an error. 

(This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows installer package.) 

Is that normal?
I'm doing something wrong?
(just wanna install **this** version on the PixHawk FC) 

Thank you very much !
Sascha

#### Version
1.3.39 

#### Platform
[  ] Copter

**Comment by meee1** [comment]
i just tried it and I got no issues.
please provide more info on the exact error

**Comment by Sas-LAB** [comment]
Good afternoon,

Will try to record a video so you can see the exact error.
(sorry for the delay)

**Comment by Sas-LAB** [comment]
**UPDATE**

Check the link today and **everything is working perfectly.**
(I could not reproduce the error)

Sorry for the troubles, didn't change anything, update....

**Comment by Sas-LAB** [comment]
You can close the ISSUE

**Comment by PPL30** [comment]
почему не скачивается программа Mission planner - Firmware 1.3.39.msi

**Comment by PPL30** [comment]
почему не скачивается программа Mission planner - Firmware 1.3.39.msi
