### ISSUE TITLE
Here+ RTK NTRIP No longer working 

### ISSUE THREAD

**Issue by LeonDwyer77** [ArduPilot/MissionPlanner#1571]
#### Issue details
I update the Here+ RTK Firmware. and also update to the latest Beta version of MP as of Monday 12 06 17.  Base and Rover are working correctly. However, the NTRIP VRS no longer send corrections to the Rover

#### Version
12/06/2017 beta. 

#### Platform
[ x ] Plane

#### Airframe type
flying wing

#### Hardware type
PH2.1 Alfa  Here+ firmware 1.3

**Comment by meee1** [comment]
I made a few changes, please try the latest beta

**Comment by leondwyer** [comment]
This is fixed.
Thank you.
