### ISSUE TITLE
Mission Planner SITL -Copter

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1578]
I was asked how to use the simulator from within Mission Planner. From my understanding it starts a SITL via a sim_vehicle.py file. So far, so well. But contrary of what I'm used to run from a command line, this Mission Planner invoked SITL requires to setup the frame type for copter, keeps nagging about RC roll not configured and demands to have a 3D Accel calibration done. Short of moving the pc in all directions I really don't know how to instruct NON developer people to use SITL with MP to practice mission planning.

<img width="521" alt="screen shot 2017-06-15 at 03 23 57" src="https://user-images.githubusercontent.com/3130363/27162623-34d6bee0-517a-11e7-9d1d-747b6632b4d7.png">
<img width="1024" alt="screen shot 2017-06-15 at 03 25 24" src="https://user-images.githubusercontent.com/3130363/27162648-5039e0e0-517a-11e7-82dd-cd283e7f16a7.png">

**Comment by meee1** [comment]
broke via this commit
https://github.com/ArduPilot/ardupilot/commit/3a9ac2ef40129ec81ad6c537257574cf67f8b34f

**Comment by meee1** [comment]
new beta pushed with fix

**Comment by lvale** [comment]
thanks Michael

**Comment by lvale** [comment]
Verified working on last beta
