### ISSUE TITLE
Uploading Waypoints Errors out

### ISSUE THREAD

**Issue by RVBldr** [ArduPilot/MissionPlanner#1580]
#### Issue details
While writing a waypoint file with approx. 35 waypoints, from MP 1.3.48, build 1.1.6330, to a 3DR Solo, I get Timeout on Read - getRequestedWPNo error. This can fail with partial waypoint write or after completion. 

#### Version
MP 1.3.48, build 1.1.6330,

#### Platform
[  ] Win 10
[  ] AntennaTracker
[  x] Rotorcraft
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
3DR Solo

#### Hardware type
Pixhawk 2 running Ardupilot

See screen capture of error.
![capture](https://user-images.githubusercontent.com/29493290/27245732-27b6b624-52a2-11e7-9c99-13d9204ebdc5.JPG)

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
please provide the tlog
