### ISSUE TITLE
Mission Planner MSI throws "not a valid Windows installer" error

### ISSUE THREAD

**Issue by ramygad** [ArduPilot/MissionPlanner#1582]
Hi,
I have tried to download  the latest stable version : http://firmware.ardupilot.org/Tools/MissionPlanner/MissionPlanner-latest.msi

I got this error  "not a valid Windows installer"

I have tested this with Windows 7 and 8

**Comment by meee1** [comment]
can you please try again. i have a feeling this is a server issue
