### ISSUE TITLE
Batt Monitor broken in 1.3.48

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#1590]
#### Issue details
After updating to 1.3.48 I get nonsense current readings. If I play the .tlog back on my computer with 1.3.46 it shows the proper readings. 

#### Issue details
Today I upgrade 2 of my planes to 3.8r6.  The following screen shots were taken on the bench at zero throttle. 

Before:
![batt monitor in 3 71](https://user-images.githubusercontent.com/4913946/27983869-4862378c-6363-11e7-945f-adc78ea9c029.JPG)

After:
![batt monitor in 3 8r6](https://user-images.githubusercontent.com/4913946/27983878-82321054-6363-11e7-9c04-af4e87f90b66.JPG)

Here is me pulling 38,300 Amps in flight.  Looks like the decimal place got moved 3 places somehow. 
![amps in flight](https://user-images.githubusercontent.com/4913946/27984122-f0503ea8-6368-11e7-96f2-217427757336.JPG)

#### Version
1.3.48

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Sub

#### Hardware type
Pixhawk

#### Logs
https://www.dropbox.com/s/gty6b1331gm4v9t/2017-07-07%2015-37-51.tlog?dl=0

**Comment by magicrub** [comment]
Looks like a units problem..

**Comment by meee1** [comment]
can you try beta MP and see if its still an issue. I think this is to do with the new battery message scaling.

**Comment by iskess** [comment]
I played back my tlogs from flights that displayed batt incorrectly, with the lastest beta it now displays as it should. Thanks for the quick response.
