### ISSUE TITLE
mavlink.csproj

### ISSUE THREAD

**Issue by afbasile** [ArduPilot/MissionPlanner#1605]
Visual Studio 2015 reports that: 
The attribute "Include" is missing from the element <Compile> in the file MAVLink.csproj.
Therefore I cannot open the project MissionPlanner.sln. 
Also, the attribute "Remove" in that same element is not acknowledged,
and had to be replaced by "Exclude".
I have .NET FRamework 4.6.2. SDK and Python2.7.13 installed on my PC.

**Comment by meee1** [comment]
please use VS 2017
