### ISSUE TITLE
Settings.Instance Doesn't Have Key/Value of ConfigPlanner's Checkbox.

### ISSUE THREAD

**Issue by 54way** [ArduPilot/MissionPlanner#1616]
#### Issue details
Settings.Instance doesn't have the key whose name is the same as the Checkbox of ConfigPlanner.
If I click the Checkbox, and the key will be added to Settings.Instance.

#### Version
ec61293477e3f1c82de81f25b249d67d7fc44ffc

#### Platform
[ v ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
which checkbox? there or not enough information here to do anything with.
