### ISSUE TITLE
"VSync" Error in Design Time

### ISSUE THREAD

**Issue by jvasanthan** [ArduPilot/MissionPlanner#1618]
#### Issue details
Hi,
I have pulled the latest Mission Planner Source code and built it using Visual Studio 2017 Community Edition. I added a button in the FlightData.Designer and tried to save the file, it threw up an error window as shown below. I found that when I cleared the ContextMenuStrip Option for the "hud1" component then I am able to save it.
I tried it in Windows 7 & 10 and i see the same error window while saving the FlightData.Designer. I read in the forum that it is related to openGL but not much of help. 

Could anybody please point me in right direction. 

Thank You

James

![image](https://user-images.githubusercontent.com/21172484/28741972-5fac82d8-7440-11e7-87ce-b589d1a84df8.png)

#### Version
Source code pulled on 27th July 2017

#### Platform
[ ~ ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Quad

#### Hardware type
Pixhawk

#### Logs
-

**Comment by grvgoel1** [comment]
Is your problem solved? I am also facing the same problem.

**Comment by jvasanthan** [comment]
I tried the following:
1. Disabled the context menu of hud and I didn’t get the vstnc error.
2.When I make change and do save(not save all) I don’t get the vsync error

Let me know if it helps

**Comment by grvgoel1** [comment]
okay i will try it and get back to you on that

**Comment by grvgoel1** [comment]
So I tried your solution but it did not work for me. Here's what I did, I set the bool of isShowContext to false. I hope that was what you meant. If not, then could you be a little more specific about which code to alter? Thanks!

**Comment by jvasanthan** [comment]
pls disable the ContextMenuStrip of hud

**Comment by grvgoel1** [comment]
@jvasanthan I cannot find the option to disable the contextmenustrip for hud, can you please pinpoint the file name or the code? Thank you!

**Comment by meee1** [comment]
please update your source code, as i believe this is resolved in newer versions
