### ISSUE TITLE
Mission Planner incorrectly reports that there is a new firmware version available when there is not.

### ISSUE THREAD

**Issue by george-hawkins** [ArduPilot/MissionPlanner#1620]
#### Issue details
Mission Planner incorrectly reports that there is a new firmware version available when there is not. See the attached screenshot - Mission Planner reports that APM:Copter V3.5.0 is available but the latest stable version number shown in <http://firmware.eu.ardupilot.org/Copter/stable/PX4-quad/git-version.txt> is V3.4.6, which is the version I have installed already on my Pixhawk (this can also be seen in the screenshot).

#### Version
1.3.49

#### Platform

[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
X quadcopter.

#### Hardware type
Pixhawk

#### Screenshot
![bad-version2](https://user-images.githubusercontent.com/5216161/28747651-940d39fa-74a4-11e7-8878-9a1ee4cb1a0b.png)

**Comment by meee1** [comment]
its not a bug. your looking at the wrong url. and 3.5 is out.

**Comment by george-hawkins** [comment]
Apologies - I see now from looking at the MP source that I should have been looking at [`ArduPilot/binary/.../Firmware/firmware2.xml`](https://github.com/ArduPilot/binary/blob/master/Firmware/firmware2.xml) and worked from there to [`stable/PX4`](http://firmware.eu.ardupilot.org/Copter/stable/PX4/) rather than [`stable/PX4-quad`](http://firmware.eu.ardupilot.org/Copter/stable/PX4-quad/) as I'd assumed.

But what do you mean by "the issue is more around the realy old version of MP in that screenshot"? As you can see in the title bar it says **1.3.49** and according to [ChangeLog.txt](https://github.com/ArduPilot/MissionPlanner/blob/master/ChangeLog.txt) 1.3.49 is the latest version (released 20-7-2017). It's the version I downloaded from the [Mission Planner installation page](http://ardupilot.org/planner/docs/common-install-mission-planner.html) a few weeks ago.

![image](https://user-images.githubusercontent.com/5216161/28749632-0319428e-74ce-11e7-96eb-b554cd2b2c38.png)

**Comment by meee1** [comment]
@george-hawkins  sorry misread the version number.
