### ISSUE TITLE
Waypoint file: loading files without a home[0] will remove first waypoint[1]

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/MissionPlanner#1635]
I generated waypoint files from a .bin log file and some files did not have a home [0] index. When loading those files, the first index [1] was skipped.

**Comment by auturgy** [comment]
This looks like it should address the root of
https://github.com/ArduPilot/ardupilot_wiki/pull/893
and hence https://github.com/ArduPilot/ardupilot_wiki/issues/867
Comment added so I can track and close the wiki issue/pr if resolved

**Comment by magicrub** [comment]
Thanks @meee1

**Comment by magicrub** [comment]
and thank you @auturgy for bringing those other issues to our attention. I missed them.
