### ISSUE TITLE
Remote RTSCTS supported but Local RTSCTS not supported

### ISSUE THREAD

**Issue by amilcarlucas** [ArduPilot/MissionPlanner#1640]
#### Issue details
I have setup my 3DR radios like this:

- remote radio:
-- RTS CTS activated in the Sik radio configuration
-- BRD_SER1_RTSCTS parameter set to 1 (enable)
- Local radio
-- RTS CTS deactivated in the Sik radio configuration

This configuration works fine with Mission Planner.

Now I activate RTS CTS on the Local radio in the Sik radio configuration, and restart both mission planner and the autopilot.

1. Mission Planner times out and complains that it can not receive heartbeat packets
2. Close Mission Planner
3. Open MavProxy
4. MAVproxy works fine
5. Close MavProxy
6. Open Mission Planner
7. Mission Planner times out and complains that it can not receive heartbeat packets

I do have Hardware flow control enabled on the Windows device manager.

#### Version
1.3.49

#### Platform
[  ] All
[  ] AntennaTracker
[ *] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
OctaQuad

#### Hardware type
pixhawk, official 3DR radios

**Comment by meee1** [comment]
can you please try disabling reset apm on connectin in the MP options. this should not touch the rts settings

**Comment by amilcarlucas** [comment]
I disabled "Reset APM on USB connect" in the MP options ... It still does not connect.

The RTS CTS radio setings do not get changed. The only issue is that MP can not directly connect (via USB) to a 3DR radio that has RTS CTS set.

**Comment by amilcarlucas** [comment]
MP can however still configure the Sik Radios. That does work, regardless of RTS CTS.
![grafik](https://user-images.githubusercontent.com/24453563/30417213-3f462472-992f-11e7-953d-a9e5504587c4.png)

**Comment by amilcarlucas** [comment]
bump

**Comment by amilcarlucas** [comment]
Tested in Qgrouncontrol. There it works as well.

**Comment by meee1** [comment]
there is a fix in MP beta

**Comment by amilcarlucas** [comment]
Tested in 1.3.50. It works fine.

Thank you for fixing this.
