### ISSUE TITLE
Adding or Modifying camerasBuiltin.XML

### ISSUE THREAD

**Issue by jagrandle** [ArduPilot/MissionPlanner#1658]
#### Issue details
I wish to add new camera and/or change the order in which they appear in this list. I can open and edit it but when I go to save it I am told

File/Device may be ReadOnly, or open for write by another application.

As I just re-booted my computer and opened nothing else I don't believe it is. What can I do ?

Thanks

#### Version
1.3.49

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
n/a

#### Hardware type
n/a

#### Logs
n/a

**Comment by meee1** [comment]
you need to modify cameras.xml in  your "my documents\mission planner" folder
