### ISSUE TITLE
Unnable to upgrade to version 1.3.50

### ISSUE THREAD

**Issue by tatsuy** [ArduPilot/MissionPlanner#1659]
#### Issue details
I can't upgrade to version 1.3.50 because the hash of protobuf-net.dll does't match.

http://firmware.ardupilot.org/MissionPlanner/checksums.txt
0328d67fc2071670f11ce17970b8ecda  upgrade/protobuf-net.dll

Downloaded the hash of protobuf-net.dll:
73b39ad1d7b1f2729c38f5b764a581cc

The dll here is old.
http://firmware.ardupilot.org/Tools/MissionPlanner/upgrade/protobuf-net.dll

I can install a new installation instead of an upgrade.

#### Version
1.3.49 => 1.3.50

#### Logs
Update Failed File downloaded does not match hash: protobuf-net.dll

**Comment by meee1** [comment]
this was a server issue, no resolved
