### ISSUE TITLE
Access to Parameter screens when not attached to the APM

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#166]
Often when I am not with my aircraft I need to look through the parameter pages to see what a parameter range, description, or to see what value I have been using. Ideally I would like to be able to load a .param file into the Full Parameter page with the APM disconnected . If Mission Planner could allow at least view only access to greyed out parameters it would be a great help.

**Comment by meee1** [comment]
i would suggest using sitl to archive this

**Comment by iskess** [comment]
Ok, then how about just showing all the parameter descriptions without the values until mavlink is connected?
