### ISSUE TITLE
Unable to change internal icons

### ISSUE THREAD

**Issue by kane111** [ArduPilot/MissionPlanner#1660]
I am trying to develop a modern interface for the learning purposes. But since I am new to c#, I can only edit the interface to an extent and cannot change the icons at all. Can someone please help me with this?

ps: I have tried replacing the icons in the Resources folder but that does not work for me.

**Comment by meee1** [comment]
This list is for issues. Not general requests like this. I would suggest google in this instance, as your problem revolves around knowledge of the language.
