### ISSUE TITLE
Gimbal test error

### ISSUE THREAD

**Issue by HumbleBeck** [ArduPilot/MissionPlanner#1676]
#### Issue details
Please check attached screenshot. Error on pressing "gimbal test" button

#### Version
1.3.50

#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
V

#### Hardware type
Pixhawk

#### Logs
![screenshot_1](https://user-images.githubusercontent.com/9539697/32148125-bab6bde4-bcfa-11e7-9aa6-f5a3aedcd281.png)

**Comment by meee1** [comment]
most things in control-f are alpha, currently gimbal test doesn't really do anything.
