### ISSUE TITLE
Mission planner fails opening vlc streams

### ISSUE THREAD

**Issue by OlivierJB** [ArduPilot/MissionPlanner#1678]
#### Issue details
Vlc is installed stock, and opens the stream fine. 
See below for error message. An additional windows trace confirmed dll was opened.

![mp vlcbug](https://user-images.githubusercontent.com/24396967/32189116-68b4bb20-bd6f-11e7-8e86-490428d05e4e.PNG)

#### Version
1.3.50

#### Platform
Via control-F, stream from skyviper
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
if you are on a 64bit os, you need 64bit vlc installed, and 32bit uninstalled

**Comment by meee1** [comment]
current beta MP will try detect the skyviper and start the video automatically using gstreamer. you need gstreamer 1.9.2 installed first though, with the full install

**Comment by Sas-LAB** [comment]
**@meee1 Worked out for me !!! thanks!** 
(just 64bit vlc installed, and 32bit uninstalled)
