### ISSUE TITLE
Error while trying to use openCV 

### ISSUE THREAD

**Issue by kane111** [ArduPilot/MissionPlanner#1688]
I intend to use openCV in Mission Planner Scripts. I have tried to import it using the import cv2 method, but it did not work. I also tried using the OS library to change the working directory to import cv2, but it gave me the following error: 

Object reference not set to an instance of an object.

So can anyone please tell me if there is a way to have openCV working with Mission Planner?

**Comment by meee1** [comment]
Mission planner uses iron python internally. so I'm not sure if its fully supported or now
