### ISSUE TITLE
MP opens up a myriad of Radius windows when it starts

### ISSUE THREAD

**Issue by expntly** [ArduPilot/MissionPlanner#1690]
#### Issue details
When MP starts and before I connect to any vehicle, it spawns anywhere between 3 to 10 of these Radius windows:

<img width="608" alt="screen shot 2017-11-26 at 4 02 50 pm" src="https://user-images.githubusercontent.com/6870452/33244804-571e8436-d2c3-11e7-800c-9db5dd4bca98.png">

Is this a bug, or is there a way I can disable this?

#### Version
1.3.49

**Comment by rmackay9** [comment]
I think it's a bug.  I've seen it as well.

**Comment by n1kitap** [comment]
Noted this as well at 1.3.49 and still get it in latest stable version.

**Comment by meee1** [comment]
fixed here f9d4bffb

**Comment by expntly** [comment]
I just updated to 1.3.50, and saw the windows again.  Is that in this version?

<img width="552" alt="screen shot 2017-12-07 at 7 00 00 pm" src="https://user-images.githubusercontent.com/6870452/33746143-f014723e-db80-11e7-882d-77d4356625ae.png">

**Comment by expntly** [comment]
Any update?  Thanks a lot!

**Comment by meee1** [comment]
update your MP

**Comment by wisnufireball** [comment]
I just update my mission planner to 1.3.53 and a bug akin to this appear. It appear on Arduplane with sonar just after it completed the "getting param" process. And it won't stop spawning even after I disconnect the FC. APM:copter with sonar is fine, and Arduplane without sonar is also fine. I haven't test another firmware though.

System spec:
Mission planner 1.3.53 on Windows 10 64bit
Arduplane 3.4.8
APM:Copter 3.5.5
FC is Pixhawk, and sonar is Maxsonar EZ4 on analog mode.

**Comment by meee1** [comment]
can you please posts 1 of your logs?

**Comment by wisnufireball** [comment]
This is the logfile; https://drive.google.com/open?id=1etf7aV9YOCv19H7aXyuvs5x99pPLkDEg
Even when the Sonar hardware is disconnected, the windows is still spawning.
