### ISSUE TITLE
Flightplan "View KML" height is not abosulte

### ISSUE THREAD

**Issue by GekoCH** [ArduPilot/MissionPlanner#1694]
The feature works quite nice however the altitude is shown in the wrong frame of reference.
You need to switch form Relative ground to absolute altitude and then the flight plan would be shown correct in GoogleEarth.

**Comment by iskess** [comment]
That’s been broken for ages. I wrote an issue on it over 4 years ago. See #180

**Comment by GekoCH** [comment]
hmm ok so no hope to get this solved in a few weeks then....

**Comment by meee1** [comment]
I believe this is fixed. referenced in the old issue #180
