### ISSUE TITLE
Script sendPacket() paramters have changed, update example2.py

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/MissionPlanner#1699]
#### Issue details
The parameters of the script command MAV.sendPacket(...) appear to have changed to 

MAV.sendPacket(msg,sysid,compid)

The example2.py needs to be updated accordingly: https://github.com/ArduPilot/MissionPlanner/blob/master/Scripts/example2.py#L41

I couldn't figure out what the sysid and compid are actually doing; whatever I used I always obtained messages with FF & BE. A clarifying comment in the example script could be helpful.

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
I will update the example.
the sysid and compid are used for tracking the remote state of that specific MAV.
ie sequence id, signing key, and mavlink version to send. so its internal only for the most part. but with multiple drones on one link, this is required.
