### ISSUE TITLE
Rover: Radio calibration should not change SERVOx_REVERSED parameters

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1701]
In Rover-3.2.0 (and later versions) we've properly separated the input and output min/max/trim/reversed values.  Now the MP's Initial Setup >> Mandatory Hardware >> RC Calibration screen's "reversed" check boxes should only affect should only affect the RCx_REVERSED parameters (i.e. input) not the output (SERVOx_REVERSED).

Here is a sample report where the user is intending to modify the RC input reversing and getting into trouble with the outputs also being reversed. https://discuss.ardupilot.org/t/rc-configuration/23821/9

**Comment by rmackay9** [comment]
It may actually be better to completely remove these reverse check boxes for Rover as we have done for Copter and then ask the users to perform any input reversing in their transmitter.

The reason I think the check boxes is that users tend to get themselves into trouble by reversing the input when they really need to modify the output.

**Comment by meee1** [comment]
ive added a new servo output screen. and removed the RC/SERVO reversed link
