### ISSUE TITLE
Determine whether -v2 or -v3 pixhawk firmware should be uploaded

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1708]
At the moment the MP uses the bootloader's reporting of it's flash size to determine if it should upload -v2 or -v3.  Unfortunately it seems the bootloader always reports 2MB even on boards that suffer from the 1MB flash issue. 

https://www.youtube.com/watch?v=BNgClHf9nIo

This is currently not a problem for Copter which is below the 1MB limit even for -v3 but it may be an issue for Plane firmware.

**Comment by meee1** [comment]
fixed here https://github.com/ArduPilot/MissionPlanner/commit/4c6aa3e52f2767472131b0e4a7bb8a531ebd42fe
