### ISSUE TITLE
Error while building mission planner in VS 2017

### ISSUE THREAD

**Issue by sunib95** [ArduPilot/MissionPlanner#1710]
I am getting this below error while i was trying to build it.
CS0234  C# The type or namespace name 'Speech' does not exist in the namespace (are you missing an assembly reference?)
Even sometimes it gives the error that missionplanner.dll is missing

#### Version
VS community 2017 version 15.5.2

CS0234 error was seen in mainV2.cs file

**Comment by meee1** [comment]
same as #1711
