### ISSUE TITLE
missionplanner.dll is missing

### ISSUE THREAD

**Issue by sunib95** [ArduPilot/MissionPlanner#1711]
#### Issue details
couldn't compile mission planner source code, as it says missionplanner.dll is missing.

#### Version
VS 2017 community version 15.5.2

![error](https://user-images.githubusercontent.com/28543782/34151416-25cefb34-e4d1-11e7-80b0-2eff38f2d95d.png)

**Comment by meee1** [comment]
please have a read here
https://msdn.microsoft.com/en-us/library/office/hh361618(v=office.14).aspx
the dll is missing. so you at missing a prereq.
