### ISSUE TITLE
UDP connection failure if connection was lost

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1730]
I've found that if I have mission planner connect to my Rover (which has a TX1 running APsync on it) that I must restart MP after pushing the Disconnect button.  Here are the steps to reproduce the problem:

1. start up a vehicle with APSync running on it and creating a wifi access point
2. connect to the access point from a windows PC
3. connect the MP using UDP
4. push disconnect on the MP
5. push reconnect on the MP, it will fail to connect

If I shut down and restart MP and then push the connect button, it will connect successfully.

**Comment by meee1** [comment]
there was a bug with this in an older version. is it still happening with a new version?

**Comment by rmackay9** [comment]
I've updated to the latest beta and it seems to be working, thanks!
