### ISSUE TITLE
Unexplained outgoing UDP connections in MissionPlanner

### ISSUE THREAD

**Issue by DawoodTaii** [ArduPilot/MissionPlanner#1743]
#### Issue details
MissionPlanner is sending UDP multicast packets to 244.0.0.251 on port 5353 on startup without any apparent reason.

#### Version
1.3.52

#### Platform
It does this on startup before connecting or doing any thing.

I found this in the code here but I don't know why it does this and I'm not sure if it's a security issue.

https://github.com/ArduPilot/MissionPlanner/blob/c9bcf78a4ce0432125099a028542a0b4a69ac632/ExtLibs/Zeroconf/Zeroconf/Platforms/netstandard1.3/NetworkInterface.cs

**Comment by meee1** [comment]
it is zeroconf, and it is looking for zeroconf cameras. ie IP cameras
