### ISSUE TITLE
Rename Dataflash "PX4 .Bin to .Log" to "Convert .Bin to .Log

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1745]
The .bin files are not related to the hardware used so we should rename the button to someting like "Convert .bin to .log".

![mp-df-convert-to-log](https://user-images.githubusercontent.com/1498098/35490235-9c3163d6-04e1-11e8-88bb-8be2978cdfad.png)

**Comment by meee1** [comment]
consider it removed

**Comment by rmackay9** [comment]
Great, thanks!

**Comment by rmackay9** [comment]
This is in the latest beta so closing, txs!
