### ISSUE TITLE
SiK radio no longer working with 1.3.50.0 or 1.3.52.0

### ISSUE THREAD

**Issue by timvand** [ArduPilot/MissionPlanner#1754]
#### Issue details
_Please describe the problem, or desired feature_
Attempted to connect to radio on COM3, which gernerated connection error.  Updated driver, fail.  Remove driver, reboot, add driver via \mission planner\Driver\DPInstx64.exe tool, attempt to connect via COM3, fail.
#### Version
_What version was the issue encountered with_
1.3.50.0 or 1.3.52.0
#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Plane
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
Pixhawk 1, SiK radio
#### Logs
_Please provide a link to any relevant logs that show the issue_
N/A

![mission_planner_connect-fail](https://user-images.githubusercontent.com/13006982/35783071-a36011be-09b6-11e8-953d-57a5a99cc17b.jpg)

**Comment by meee1** [comment]
That error message means something else is using the port.
I have verified here, and nothing wrong with missionplanner

**Comment by timvand** [comment]
Does it require being run as admin?  When the radio is unplugged from the USB port, the COM port connection is removed.

**Comment by timvand** [comment]
How much do I need to pay to help resolve the issue?

**Comment by meee1** [comment]
depending on the model of radio you are using it most likely has a ftdi chipset inside it. I use rfd900 and sik radios on the same install all the time.
you need to close other apps on your pc to get to the bottom of what is opening the port and not closing it.

**Comment by meee1** [comment]
also check device manager to ensure you have the correct port
![image](https://user-images.githubusercontent.com/511568/35783590-c5ce96b0-0a44-11e8-8430-9f7d9dabef20.png)

**Comment by timvand** [comment]
Doesn't removing the device from the USB port on the PC remove the port in use?  In my experience it does, as I see the COM port being added and removed in the computer management\device manager window when the radio is added and removed from the USB port.

**Comment by meee1** [comment]
not always, reboot the pc as well.

**Comment by timvand** [comment]
Been doing reboots as well.

No radio plugged in.
![com1_pic](https://user-images.githubusercontent.com/13006982/35783671-e1adb062-09bf-11e8-80c1-eab19f16bb8d.jpg)

433 radio added
![com1-com15_pic](https://user-images.githubusercontent.com/13006982/35783680-ef03a21c-09bf-11e8-961b-00638cc11969.jpg)

COM15 detail
![com1-com15_detail_pic](https://user-images.githubusercontent.com/13006982/35783684-f8856690-09bf-11e8-80b3-719eb2ba1c7b.jpg)

Connection fail
![com1-com15_pic_connect-fail](https://user-images.githubusercontent.com/13006982/35783685-06643c00-09c0-11e8-93a9-3efe4ed27272.jpg)

**Comment by timvand** [comment]
So, do a reboot, and then add the radio?

**Comment by meee1** [comment]
Could be a driver issue as well.

MP has never shipped with Silicon Labs drivers.

**Comment by timvand** [comment]
Shit.

What drivers are to be used?

**Comment by timvand** [comment]
And here is a similar issue, which the download of the SL drivers appeared to resolve the issue.
https://discuss.ardupilot.org/t/new-dell-pc-with-windows-10-home-mp-doesnt-see-the-serial-ports-and-crashes/22724
