### ISSUE TITLE
Issue with download page

### ISSUE THREAD

**Issue by mattviney** [ArduPilot/MissionPlanner#1756]
The download page for Mission Planner doesn't appear to be working:

http://firmware.ardupilot.org/Tools/MissionPlanner/MissionPlanner-latest.msi

I'm getting '404 page not found'. Any suggestions?

**Comment by magicrub** [comment]
We're getting reports that the web file server is having issues. We're working on it, please try again in a few hours. Sorry for the delay!

**Comment by magicrub** [comment]
Please close issue, it is not related to Mission Planner. It's an internet server hosting thing.

**Comment by mattviney** [comment]
Thanks very much. Clearly i was very unlucky when trying to download as it is now working fine.
