### ISSUE TITLE
M8N gps module not responding

### ISSUE THREAD

**Issue by doljako** [ArduPilot/MissionPlanner#1757]
#### Issue details
when i first pluged gps module in a pixhawk controller it was working fine but after i unpluged it and pluged it in again it didn't turn on

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
This is not the place to post hardware issues.
