### ISSUE TITLE
Boats should appear as a boat icon

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1762]
In Rover-3.3 we will probably report boats as boats by setting the mav_type field (of the hearbeat?) to MAV_TYPE_SURFACE_BOAT.

Here's the corresponding issue in the vehicle code: https://github.com/ArduPilot/ardupilot/issues/7646

We probably need someone to make us a boat-ish looking icon.

**Comment by gmorph** [comment]
Spoke with Michael O. about this - there is a boat icon in MP he is happy for us to use I think.

**Comment by rmackay9** [comment]
Ah great!

**Comment by meee1** [comment]
MP already does exactly this. just needs the firmware to change, ant it will work already

**Comment by rmackay9** [comment]
great.  i'll close this then.
