### ISSUE TITLE
Compass Calibration Error in Mission Planner

### ISSUE THREAD

**Issue by thompsbp** [ArduPilot/MissionPlanner#1763]
#### Issue details
New Pixhawk install. Trying to calibrate external compass and get an error.

#### Version
MP 1.3.52
AP 3.8.4

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Strix Stratosurfer

#### Hardware type
Holybro Pixhawk Set from GetFPV

#### Logs
![pixhawk_compass_issue](https://user-images.githubusercontent.com/10853710/36356186-1219336e-14bc-11e8-8061-3c724ae23582.png)

**Comment by meee1** [comment]
i believe this is fixed in beta MP

**Comment by thompsbp** [comment]
Confirmed. Updating to Beta build fixes the issue.

Thanks.
