### ISSUE TITLE
Missing data on web target (AntennaTracker)

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1765]
Using latest release
 from console window

> 
> INFO MissionPlanner.Utilities.Firmware - APMVERSION: AntennaTracker V1.0.0
> INFO MissionPlanner.Utilities.Firmware - Get url http://px4-travis.s3.amazonaws.com/Firmware/stable/git-version.txt
> INFO MissionPlanner.Common - getModesList Called
> INFO MissionPlanner.Common - getModesList Called
> ERROR MissionPlanner.Utilities.Firmware - System.Net.WebException: The remote server returned an error: (404) Not Found.
>

**Comment by meee1** [comment]
this file has never existed. and never will. as MP doesn't officially upload this firmware anyway
