### ISSUE TITLE
Calibrate compass error

### ISSUE THREAD

**Issue by colmer** [ArduPilot/MissionPlanner#1781]
#### Issue details
Error when I try calibrate compass

#### Version
MP 1.3.52 , Arducopter V3.2.1

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
quad

#### Hardware type
ARM 2.6

#### Logs
![error](https://user-images.githubusercontent.com/4122445/37572426-f1066a40-2b1b-11e8-9fea-95da71aeb581.png)

**Comment by meee1** [comment]
this should be resolved in latest release
