### ISSUE TITLE
Nuget Package Issue (System.Drawing.Common)

### ISSUE THREAD

**Issue by alphajafarabadi** [ArduPilot/MissionPlanner#1784]
I clone the **last Mission Planner source code** using **Visual Studio** then i try to **Rebuild** it but i can't cause of project decencies. **Nuget** restores all packages successfully except _**System.Drawing.Common** 4.5.0-preview2-26225-02_, in Nuget package manager the last version of System.Drawing.Common is 4.5.0-preview1-26216-02.

Are you using from a custom/third-party Nuget source?

**Comment by meee1** [comment]
please do a 
nuget.exe sources Add -Name "myget" -Source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

**Comment by alphajafarabadi** [comment]
Thank you @meee1 😄 my problem has been solved but now i have a new one...
Please check attached file.

Details:
Windows 10 1709
Visual Studio Enterprise 15.6.3 Full
.NET Core/Standard/Framework all versions
![log](https://user-images.githubusercontent.com/37267028/37708852-6abce12c-2d1d-11e8-9440-597e0e80ba16.jpg)
