### ISSUE TITLE
[SOLVED] Mission Planner bug. Random gimbal control windows popup after latest MP update

### ISSUE THREAD

**Issue by pompecukor** [ArduPilot/MissionPlanner#1789]
[SOLVED]
#### Issue details
I just updated to the latest (stable) version of MP just now. As soon as I connect UAV (via COM port). Then small windows start to pop up and never stop. I think originally meant for controlling gimbal, the one that says "Radius (+/-)5m.." in the title.

UPDATE: I have added video in second post to make the problem more clear.

#### Version
_What version was the issue encountered with_

#### Platform
[ x? ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Sub

![image](https://user-images.githubusercontent.com/31744367/37877442-bde7bb1a-305b-11e8-8254-3dc88f6ac2be.png)

**Comment by pompecukor** [comment]
https://youtu.be/49i6NjdY0lQ

**Comment by meee1** [comment]
please update to the latest MP 1.3.54

**Comment by pompecukor** [comment]
Thx Mike. Fixed in 1.3.54
