### ISSUE TITLE
Feature Request: Export Flight Plan in .KMZ file for viewing on Google Earth

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#180]
Flight planning a mapping mission over very high terrain is much easier using Google Earth's 3D maps . I created a flightplan.txt file, converted it to a .kmz file by reorganizing the columns and adding the appropriate headers, then I imported that into Google Earth as a "Path". Google Earth has the option to "Show Elevation Profile" which has some features that MP lacks. You can drag your pointer across the profile and see exactly where that corresponds to on the plan view. This helps to locate the areas where terrain clearance is a factor, and helps to calculate where overlap will be an issue. This worked, but was a cumbersome process. If there was a scripted .KMZ "Save As" feature it would be very useful to visualize the flight plan against the terrain. 

Ideally MP would allow flight planning in using Google Earth, but I think that would require Google Earth Pro.

**Comment by meee1** [comment]
I believe this is fixed now

**Comment by iskess** [comment]
Thank you for fixing this! 
The other 3 suggestions (font size, WP icon size, extend to ground outline), are not as important so I'll close the issue now.
