### ISSUE TITLE
Allow loading ChibiOS firmware

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1814]
Copter-3.6, Rover-3.3, Plane-3.9 will support ChibiOS.  It would be nice if the install firmware screen allowed loading ChibiOS easily to the flight controller.

The firmwares are available on firmware.ardupilot.org:

old Pixhawk1: http://firmware.ardupilot.org/Copter/latest/fmuv2/
pixhawk1/cube: http://firmware.ardupilot.org/Copter/latest/fmuv3/
pixracer: http://firmware.ardupilot.org/Copter/latest/fmuv4/

**Comment by rmackay9** [comment]
the beta versions are now available as well for Copter and Rover..

**Comment by rmackay9** [comment]
As a side note, some users have had temporary problems falling back to the NuttX versions of Copter-3.6 probably because the ChibiOS versions of ArduPilot (and their slightly different USB connection string) are different.  [Issue raised by user is here](https://discuss.ardupilot.org/t/how-to-get-back-to-nuttx/28495).

**Comment by meee1** [comment]
the latest beta should deal with this

**Comment by meee1** [comment]
also assuming the board is booting, click the force px4 bootloader option

**Comment by Kelly-Foster** [comment]
I have the latest beta, assuming "Check for beta updates" on the help screen is what is meant by "latest beta".  It still doesn't work with a RevoMini which has been flashed with an Ardupilot-compatible bootloader.  Do you have a RevoMini or AirbotV2 / Omnibus F4 V3 to test with?

Kelly

**Comment by rmackay9** [comment]
@Naterater, for me it sometimes pops up a message asking "ChibiOS?".  I'm unsure when that pops up though.  Sometimes I see it... I'm not sure if it always appears though.

**Comment by Naterater** [comment]
https://discuss.ardupilot.org/t/how-to-downgrade-from-chibios-to-nuttx/31117

**Comment by rmackay9** [comment]
surely this is done now

**Comment by andyp1per** [comment]
> 
> 
> also assuming the board is booting, click the force px4 bootloader option

Ah, this is key! I have had endless trouble uploading firmware to a board with ChibiOS installed. Clicking force bootloader before trying totally solves this! There should really be an item on the wiki about this IMO.
