### ISSUE TITLE
Motor Compass Offset only uses Current Sensor #1

### ISSUE THREAD

**Issue by JacksonUAS** [ArduPilot/MissionPlanner#1818]
#### Issue details
Motor compass offset calibration is based off current sensor #1, when it should be done for 1 & 2.

**Comment by rmackay9** [comment]
This is really an ardupilot issue instead of a mission planner issue so probably belongs over on the ardupilot [vehicle code issues list](https://github.com/ArduPilot/ardupilot/issues).
