### ISSUE TITLE
Flight plan screen windows

### ISSUE THREAD

**Issue by JeyPi** [ArduPilot/MissionPlanner#1822]
For some reason the flight plane screen windows reorganized. How do I put them back?

Mission planner wersion 1356

running windows 8

![mission planner windows](https://user-images.githubusercontent.com/16972472/39461463-0ca56b78-4d0b-11e8-84d3-14a8df34d582.jpg)

**Comment by meee1** [comment]
right click > switch docking

**Comment by JeyPi** [comment]
Thanks a lot.
