### ISSUE TITLE
typo in batt mon?

### ISSUE THREAD

**Issue by vierfuffzig** [ArduPilot/MissionPlanner#1824]
using "battery monitor" settings under "optional hardware" fails trying to set BATT_AMP_PERVOLT for respective parameter name is BATT_AMP_PERVLT (without the "O").
parameter handling via full parameter list is unaffected.

Version 1.3.56

[  ] All
[  ] AntennaTracker
[  ] Copter
[x ] Plane
[  ] Rover
[  ] Sub

Basti.

**Comment by dwoolworth** [comment]
+1 on this, had to set BAT_AMP_PERVLT in full parameter list.

**Comment by vierfuffzig** [comment]
this has been fixed by https://github.com/ArduPilot/MissionPlanner/commit/61e3a2acfc15c40b808b1d5c3d4ac75bb13b003e
thanks!
