### ISSUE TITLE
ESC_TELEMETRY_1_TO_4 stops HUD to stop updating

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1877]
Copter master includes sending the ESC_TELEMETRY_1_TO_4 message.  It seems the MP is unhappy receiving this message because the HUD stops updating.

![esc_telemtry](https://user-images.githubusercontent.com/1498098/42145828-93cb7736-7dfe-11e8-9c56-7c91fa58769c.png)

Update: it may not actually be caused by ardupilot sending the message because the error message shown above occurs even without being connected to a vehicle.

**Comment by meee1** [comment]
this error is caused by a bad dll version. I would try doing an update again. so the dll is correctly updated.

**Comment by rmackay9** [comment]
I'm having a few issues probably caused by McAfee zapping dlls somewhat randomly.
