### ISSUE TITLE
Add simple wildcard ability to param search

### ISSUE THREAD

**Issue by Kelly-Foster** [ArduPilot/MissionPlanner#1881]
It would be great if param search in Full Parameter List & Tree had basic wildcard ability, even if just * matching one or more characters.

**Comment by meee1** [comment]
wild cards do work. but the syntax is a little different
eg
se.*_pro

it uses what's known as regex

**Comment by meee1** [comment]
ie   dotstar

**Comment by Kelly-Foster** [comment]
Thanks.  I should have tried Unix regexp.  My bad.  Issue closed.

**Comment by meee1** [comment]
i have added a simple * replace with .*, in the search box
as im sure that will cover 90% of uses. but for those more advanced regex is the better answer

**Comment by Kelly-Foster** [comment]
Good call.  Agree simple * covers vast majority of likely needs.
