### ISSUE TITLE
Copter Extended Tuning page updates for Copter-3.6 release

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1903]
A few parameters have changed names in Copter-3.6 so the extended tuning page needs to be updated:

- ACCEL_Z_* renamed to PSC_ACCZ_*
- POS* parameters renamed to PSC_POS*
- VEL* parameters renamed to PSC_VEL*

![copter36-param-change](https://user-images.githubusercontent.com/1498098/43053549-437505de-8e68-11e8-9e23-1c19f5d570d4.png)

[This issue was brought up by a beta tester in this discussion](https://discuss.ardupilot.org/t/extended-tuning-parameters-to-zero-after-firmware-update-arducopter-3-6rc6/31070/2).

**Comment by sq7lrx** [comment]
also loiter speed is missing (readonly field)

**Comment by rmackay9** [comment]
@sq7lrx txs for spotting that.

@meee1, so WPNAV_LOIT_SPEED has become just LOIT_SPEED now.

**Comment by meee1** [comment]
yep, already fixed that

**Comment by rmackay9** [comment]
all fixed so closing
