### ISSUE TITLE
Previous Firmware(AP V3.8.5) upload Issue

### ISSUE THREAD

**Issue by pieservice** [ArduPilot/MissionPlanner#1915]
#### Issue details
I am trying to upload ArduPlane V3.8.5 to my cube by choosing Previous Firmware tab. and there are some message saying uploading error.  The message is below

Failed to download new firmware : System.UriFormatException: Invalid URI: The format of the URI could not be determined.
    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
    at System.Net.WebRequest.Create(String requestUriString)
    at MissionPlanner.Utilities.Download.CheckHTTPFileExists(String url) in C:\Users\michael\Source\Repos\MissionPlanner\ExtLibs\Utilities\Download.cs:line355 
    at MissionPlanner.Utilities.Firmware.update(String comport. software temp, String historyhash) in C:\Users\michae\Source\Repos|MissionPlanner\Utilities\Firmware.cs:line 406

#### Version
Mission planner 1.3.57

#### Platform
[] All
[  ] AntennaTracker
[  ] Copter
[-] Plane
[  ] Rover
[  ] Sub

#### Airframe type
plane + VTOL_

#### Hardware type
pixhawk

#### Logs
![error](https://user-images.githubusercontent.com/24711644/43759386-07e6d2e2-9a5a-11e8-820d-95f659f15ce8.png)

**Comment by JeyPi** [comment]
The same for me.
![image1](https://user-images.githubusercontent.com/16972472/49876357-1c780580-fe1b-11e8-8212-3e85a43cc5ce.jpg)
How do we cure this?

**Comment by meee1** [comment]
update your mission planner

**Comment by JeyPi** [comment]
OK I did and I get still the same report. Mission planner 1.3.62 build 1.3.6917.15581

**Comment by JeyPi** [comment]
I am using this board:
https://www.goodluckbuy.com/minipx4-beta-version-flight-controller-support-pwm-ouptut-for-fpv-multicopter-quad.html

![image2](https://user-images.githubusercontent.com/16972472/49877182-c1dfa900-fe1c-11e8-8000-b1655e022826.jpg)

**Comment by JeyPi** [comment]
Well this is closed. So I suppose I am opening it again as updating the mission planner did not help.
