### ISSUE TITLE
SITL broken on master (1.3.58 build 1.3.6794.34444)

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#1916]
Starting SITL via the GUI, no matter what vehicle, fails.

<img width="1028" alt="screen shot 2018-08-09 at 13 01 53" src="https://user-images.githubusercontent.com/3130363/43897780-1be298d6-9bd5-11e8-83e1-ecb87c342174.png">

**Comment by rmackay9** [comment]
I've noticed the MP simulator doesn't work as well right now.  It's unclear to me whether it's an ArduPilot change or an MP change that is to blame.  It's hit some teammates who are competing in a competition as well.. although they've found a way around the problem by starting the simulator manually.

**Comment by lvale** [comment]
Starting the simulator from within MP and using QGC on the same machine works ok, so I guess that is a MP issue

**Comment by lvale** [comment]
working now.
thanks @meee1 

closing
