### ISSUE TITLE
Send Error message & cant escape  system null referenceException:Object reference not set to an instance of an Object

### ISSUE THREAD

**Issue by dwright361** [ArduPilot/MissionPlanner#1924]
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
please fill in the form correctly.

**Comment by dwright361** [comment]
Version 1.3.57 build 1.3.6794.30567 ArduRover v3.4.2(318a941d)
Pixhawk

**Comment by dwright361** [comment]
![ardupilot error3](https://user-images.githubusercontent.com/6415684/44266680-02be0d00-a1f1-11e8-854c-ad74cd2d5684.PNG)
