### ISSUE TITLE
ESC Telemetry Display

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/MissionPlanner#1925]
#### Issue details
The newest releases of ardupilot are compatible with BL_Heli32 ESC telemetry. Individual ESC volts, current, and RPM can be logged and sent via telemetry, and it would be a huge benefit to be able to monitor this real-time rather than just looking at the averages and sums (BATT messages)

#### Version
Plane 3.9

#### Platform
[ X ] All
[  ] AntennaTracker
[ X ] Copter
[ X ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Dual-motor plane

#### Hardware type
Cube Black. Lumineer BL_Heli32 51A ESC

#### Logs
Will post if requested.

**Comment by meee1** [comment]
have a look for
esc1_volt... etc

**Comment by Naterater** [comment]
The current value shown is currently 100x the value that is logged. It's almost right, but not as of the latest beta from 1 hour ago.

**Comment by meee1** [comment]
are they all x100? or just some fields?

**Comment by Naterater** [comment]
Just some. Volt and Currnet are x100 while RPM is /10.

![image](https://user-images.githubusercontent.com/35429159/44314356-d5828200-a3dd-11e8-8834-d77b96ddb90a.png)
