### ISSUE TITLE
Compass calibration is not reporting success on completion

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1932]
Using latest (Copter-3.7-dev) the compass calibration screen is not reporting success once calibration completes.  Instead the green bars stay at 99%.

I'm unsure if this is an ArduPilot flight code issue or a mission planner issue.

**Comment by meee1** [comment]
idealy i would need a tlog of the issue, but MP if fairly passive at this point, it only listerns to what its told.

**Comment by rmackay9** [comment]
I think this has been resolved.
