### ISSUE TITLE
EKF label on HUD remains red after reboot

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1933]
It seems that if the flight controller is disconnected from the MP while the EKF label is red, the label remains red after reconnecting even if the EKF is in a good state.

Below is a picture of this situation.
![ekf-reporting-issue](https://user-images.githubusercontent.com/1498098/44567507-b3a64800-a7ad-11e8-988b-e2326dbf9434.png)

**Comment by meee1** [comment]
you dont have a velocity horz fixed yet, so yes its meant to be red.

**Comment by rmackay9** [comment]
ok, oops, sorry.
