### ISSUE TITLE
Camera Gimbal Tab restricts setting MNT_ functions to SERVO5 and up

### ISSUE THREAD

**Issue by vierfuffzig** [ArduPilot/MissionPlanner#1934]
#### Issue details
MP's Camera Gimbal Tab allows setting MNT_ function only to SERVO5 to 12, while it really is a valid function for any SERVOn_ via full param list. 

#### Version
MP 1.3.58

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Sub

#### Hardware type
OmnibusF4Pro

**Comment by meee1** [comment]
is your aim to use one of the first 4? or above 12?

**Comment by vierfuffzig** [comment]
thanks for your heads up. 
i actually noticed this while helping a buddy who tried to set MNT_ axis to one of the first 4 SERVO outs. background: some omnibus- /AIO "chibios-only"-type boards only have the first 4 SERVO outs fully equipped with signal/5V/Gnd, whereas outputs 5 and up are signal-only solder-pads. so in some cases it makes sense to run servo-type-gimbal control from those first four connectors on the servorail and move other functions that don't necessarily require dedicated 5V power further up.
while this is perfectly possible to set using the full parameter list (as SERVOn_FUNCTION is freely configureable for any SERVOn), the gimbal tab's options are restricted as noted above. 
if this restriction is intentional to keep users from accidentally overriding essential control-surface functions, please disregard. in this case a respective note might prevent confusion.
my initial intention however was to suggest adding SERVO1-4 to the dropdown list.

cheers, basti.
