### ISSUE TITLE
Rally point position should be at point where right-mouse-button was clicked

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1935]
When entering Rally points it seems like the procedure is:

1. click on the map with the left mouse button
2. right-mouse-button-click, Rally, Set Rally Point

I think instead it should be using the point from step 2 (i.e. step 1 shouldn't be necessary).  I think this would be consistent with other right-mouse-button-menu features like "Set Home".

The way it is now, if the user hasn't done (1) then the right-mouse-button menu is still visible but the point isn't added.  Sometimes I found the rally point appeared in an odd place on the map (far from my cursor) because it was using a point that I had clicked on long before.

**Comment by meee1** [comment]
fixed in beta

**Comment by rmackay9** [comment]
Thanks!!
