### ISSUE TITLE
mission planner never support HIL again?

### ISSUE THREAD

**Issue by rxwang04** [ArduPilot/MissionPlanner#1936]
#### how to load HIL simulator firmware into pixhawk
i try to set up hardware in the loop with xplane 10 to test my pixhawk before taking off but i can't find out where to load HIL firmware in the initial page of mission planner when i follow the instructions in ardupilot. i search in the internet and some one said the hil function has been cancel. HIL is good way to test the apm and less risk to crash , why is it to be cancel or maybe something i didn't set up?
#### 1.3.58
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
there is no longer any firmware that supports HIL. so no this support will not be coming back
