### ISSUE TITLE
building process giving error

### ISSUE THREAD

**Issue by kane111** [ArduPilot/MissionPlanner#1937]
#### Issue details
_Please describe the problem, or desired feature_

Build error

#### Version
_What version was the issue encountered with_

master, 1.3.54 (basically every version until 1.3.49, after that the code doesn't build)

#### Platform
[O] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Logs

I get the following types of error repeatedly:

> Error	CS0006	Metadata file '..\MissionPlanner\bin\Debug\net461\MissionPlanner.exe' could not be found

> Error	CS0006	Metadata file '..\missionlatest\MissionPlanner\ExtLibs\Maps\bin\Debug\netstandard2.0\MissionPlanner.Maps.dll' could not be found

> Error	MSB3577	Two output file names resolved to the same output path: "obj\Debug\netstandard2.0\MissionPlanner.Strings.resources"	MissionPlanner.ArduPilot

>Error	CS0234	The type or namespace name 'Speech' does not exist in the namespace 'System' (are you missing an assembly reference?)

I am using 
Windows 8.1 x64
Visual Studio 2017 15.8.2, 
.NET 4.7.0362
.NET CORE SDK 2.1.202 x64

**Comment by meee1** [comment]
you can only currently build on windows 10
