### ISSUE TITLE
Error when close vlc stream 

### ISSUE THREAD

**Issue by MonkO** [ArduPilot/MissionPlanner#1941]
Hello!
After vlc rtsp stream,i close MP, and have error:
![capture](https://user-images.githubusercontent.com/2711685/45304184-36563380-b520-11e8-84f3-cb51133330aa.PNG)

How can i fix it?

**Comment by meee1** [comment]
ive added a bitmap clone, so should prevent this error, but will reduce performance.

**Comment by MonkO** [comment]
I try to use bitmap clone, but it didnt help me. Can you show me where, you mean, use it?

also im interested to use gstreamer, but pipeline what i use didnt work:
rtspsrc location=rtsp://192.168.10.145:554/mux1.sdp ! queue ! rtpjitterbuffer latency=100 ! rtph264depay ! avdec_h264 ! autovideosink sync=false
but it work through cmd
