### ISSUE TITLE
Survey (Grid) has incorrect "Distance" and "Flight Time (est)" values

### ISSUE THREAD

**Issue by TheGeographer** [ArduPilot/MissionPlanner#1947]
#### Issue details
In the Survey (Grid)  tool, the distance and flight time estimates are incorrect. Looks like the units on the distance value are in meters and not kilometers as indicated (see screen capture).

![2018-09-21_12-15-11](https://user-images.githubusercontent.com/3716224/45896127-cace5a80-bd98-11e8-9cc1-79e374e02a1e.png)

#### Version
1.3.58

#### Platform
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
NA

#### Hardware type
NA

#### Logs
NA

**Comment by EosBandi** [comment]
Your home point is not set, but located somewhere in a great distance. Distance between home point and waypoint 1 is added to the total distance.....
