### ISSUE TITLE
Simulator unable to load terrain data

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1957]
while testing at a search and rescue event in Hokkaido Japan I found that the simulator was unable to load terrain data.  This means we are unable to test the terrain alt based missions.
![ter-pend-test](https://user-images.githubusercontent.com/1498098/46805908-35275900-cda1-11e8-97d2-cf583f382e7f.png)

mission: https://www.dropbox.com/s/wuxrd9uttva1nsf/JIC-test-mission.waypoints?dl=0

By the way, the terrain data seems to work fine on a real vehicle, it's just the simulator that I think is not working.

**Comment by meee1** [comment]
I have seen this as well, but given mission planner works for real flights, I don't think its a MP issue.
its a sitl issue I think.

**Comment by meee1** [comment]
I think I found the source of this issue.
the mavlink packet spec changed, and MP didn't handle the change to the packet structure
