### ISSUE TITLE
Gstreamer RTSP stream pipeline problem 

### ISSUE THREAD

**Issue by MonkO** [ArduPilot/MissionPlanner#1958]
Hi!
I'm trying receive my RTSP video on MissionPlanner. I use this pipeline:
rtspsrc location=rtsp://192.168.10.145:554/mux1.sdp ! application/x-rtp ! rtph264depay ! avdec_h264 ! videoconvert ! video/x-raw,format=BGRA ! appsink name=outsink
it work, when I put it on cmd, but not in MissionPlanner.
Also I trying  udp like in example:
videotestsrc pattern=ball ! x264enc ! rtph264pay ! udpsink host=127.0.0.1 port=5600
and it work. But I need rtsp video. Can you help me?

**Comment by meee1** [comment]
what error do you get when you do it in MP?

**Comment by meee1** [comment]
to use
rtspsrc location=rtsp://192.168.10.145:554/mux1.sdp ! application/x-rtp ! rtph264depay ! avdec_h264 ! videoconvert ! video/x-raw,format=BGRA ! appsink name=outsink

you need to right click the hud > set gstreamer source. and paste in that pipeline

**Comment by MonkO** [comment]
I right click the hud and set gstreamer source. but it not working. No error, but no video too

**Comment by meee1** [comment]
please try the latest version. i found a bug
