### ISSUE TITLE
brand new visual studio (15.8.7) can not compile mission planner, please help

### ISSUE THREAD

**Issue by hbzhang** [ArduPilot/MissionPlanner#1959]
I am trying to compile the mission planner code using the latest Visual studio  15.8. I am using .net framework 4.0.

After downloading mission planner code. I hit build solution. Here is the error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file Config.zh-Hans.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SikRadio			
Error	CS0006	Metadata file 'D:\unrealeditor\MissionPlanner-master\ExtLibs\GMap.NET.Core\bin\Debug\netstandard2.0\GMap.NET.Core.dll' could not be found	GDAL.NET(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\GDAL\CSC	1	Active
Error	CS0006	Metadata file 'D:\unrealeditor\MissionPlanner-master\ExtLibs\SvgNet\bin\Debug\netstandard2.0\SvgNet.dll' could not be found	GDAL.NET(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\GDAL\CSC	1	Active
Error	CS0006	Metadata file 'D:\unrealeditor\MissionPlanner-master\ExtLibs\Maps\bin\Debug\netstandard2.0\MissionPlanner.Maps.dll' could not be found	MissionPlanner.ArduPilot(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\ArduPilot\CSC	1	Active
Error	CS0006	Metadata file 'D:\unrealeditor\MissionPlanner-master\ExtLibs\Maps\bin\Debug\netstandard2.0\MissionPlanner.Maps.dll' could not be found	tlogThumbnailHandler(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\tlogThumbnailHandler\CSC	1	Active
Error		Couldn't process file Config.zh-TW.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SikRadio			
Error		Couldn't process file Config.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SikRadio			
Error		Couldn't process file Config.zh-Hant.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SikRadio			
Warning	CS0162	Unreachable code detected	GMap.NET.Core(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\GMap.NET.Core\GMap.NET.Internals\Cache.cs	140	Active
Warning	CS0108	'ProxySocket.Connect(string, int)' hides inherited member 'Socket.Connect(string, int)'. Use the new keyword if hiding was intended.	GMap.NET.Core(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\GMap.NET.Core\GMap.NET.Internals\SocksProxySocket\ProxySocket.cs	130	Active
Warning	CS0108	'ProxySocket.BeginConnect(string, int, AsyncCallback, object)' hides inherited member 'Socket.BeginConnect(string, int, AsyncCallback, object)'. Use the new keyword if hiding was intended.	GMap.NET.Core(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\GMap.NET.Core\GMap.NET.Internals\SocksProxySocket\ProxySocket.cs	195	Active
Warning	CS0108	'GMapBaloonToolTip.DefaultStroke' hides inherited member 'GMapToolTip.DefaultStroke'. Use the new keyword if hiding was intended.	GMap.NET.Core(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\GMap.NET.Core\GMap.NET.WindowsForms\ToolTips\GMapBaloonToolTip.cs	20	Active
Warning	CS0414	The field 'AFeature.TimeStampSpecified' is assigned but its value is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Abstract\AFeature.cs	130	Active
Warning	CS0414	The field 'AFeature.TimeSpanSpecified' is assigned but its value is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Abstract\AFeature.cs	147	Active
Warning	CS0414	The field 'AFeature.StyleSpecified' is assigned but its value is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Abstract\AFeature.cs	172	Active
Warning	CS0414	The field 'Style.StyleSpecified' is assigned but its value is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Style.cs	54	Active
Warning	CS0414	The field 'ColorStyle.colorModeSpecified' is assigned but its value is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Style.cs	97	Active
Warning	CS0414	The field 'IconStyle.IconSpecified' is assigned but its value is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Style.cs	168	Active
Warning	CS0414	The field 'IconStyle.scaleSpecified' is assigned but its value is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Style.cs	185	Active
Warning	CS0414	The field 'LabelStyle.scaleSpecified' is assigned but its value is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Style.cs	229	Active
Warning	CS0169	The field 'KmlDouble.value' is never used	KMLib(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\KMLib\Support\Wrappers.cs	42	Active
Warning	CS0168	The variable 'ex' is declared but never used	Transitions(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\Transitions\Transition.cs	144	Active
Warning	CS0168	The variable 'ex' is declared but never used	Transitions(netstandard2.0)	D:\unrealeditor\MissionPlanner-master\ExtLibs\Transitions\Utility.cs	74	Active
Warning		Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	BSE.Windows.Forms			
Warning		The referenced component 'Newtonsoft.Json' could not be found.	BSE.Windows.Forms			
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	GMap.NET.WindowsForms		1	Active
Warning		Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.	Updater			
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	ZedGraph		1	Active
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	SikRadio		1	Active
Error	NETSDK1064	Package System.Drawing.Common, version 4.5.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	Transitions	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
Error	NETSDK1064	Package GeoAPI.CoordinateSystems, version 1.7.5 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	ProjNET	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
Error	NETSDK1064	Package System.Drawing.Common, version 4.5.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	KMLib	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
Error	NETSDK1064	Package System.Drawing.Common, version 4.5.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	AviFile	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
Warning	MSB3106	Assembly strong name "C:\Users\hbzhang\.nuget\packages\directshowlib\1.0.0\lib\DirectShowLib.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).	WebCamService	D:\Visual Studio\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110	
Warning	MSB3106	Assembly strong name "C:\Users\hbzhang\.nuget\packages\system.drawing.common\4.5.0\ref\netstandard2.0\System.Drawing.Common.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).	WebCamService	D:\Visual Studio\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110	
Error	NETSDK1064	Package System.Drawing.Common, version 4.5.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	Core	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
Error	NETSDK1064	Package System.Drawing.Common, version 4.5.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	SvgNet	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
Error	NETSDK1064	Package System.Drawing.Common, version 4.5.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	GMap.NET.Core	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
Warning	MSB3106	Assembly strong name "C:\Users\hbzhang\.nuget\packages\mono.posix\4.0.0\lib\net40\Mono.Posix.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).	SharpAdbClient	D:\Visual Studio\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110	
Error	NETSDK1064	Package System.Drawing.Common, version 4.5.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	netDxf	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
Warning	NU1701	Package 'DirectShowLib 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	WebCamService	D:\unrealeditor\MissionPlanner-master\ExtLibs\WebCamService\WebCamService.csproj	1	
Warning	NU1701	Package 'Mono.Posix 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	SharpAdbClient	D:\unrealeditor\MissionPlanner-master\ExtLibs\SharpAdbClient\SharpAdbClient.csproj	1	
Warning	NU1701	Package 'GDAL 1.11.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	GDAL.NET	D:\unrealeditor\MissionPlanner-master\ExtLibs\GDAL\GDAL.NET.csproj	1	
Error	MSB3821	Couldn't process file Resources.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	MissionPlanner.Maps	D:\Visual Studio\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	3049	
Error	NU1202	Package csmatio 1.0.20 is not compatible with net40 (.NETFramework,Version=v4.0). Package csmatio 1.0.20 supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package System.Threading.Tasks 4.3.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package System.Threading.Tasks 4.3.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.0 (.NETStandard,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package System.Reactive 4.1.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package System.Reactive 4.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - uap10.0 (UAP,Version=v10.0)
  - uap10.0.16299 (UAP,Version=v10.0.16299)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package System.Drawing.Common 4.5.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package System.Drawing.Common 4.5.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net461 (.NETFramework,Version=v4.6.1)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package System.Reactive.Linq 4.1.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package System.Reactive.Linq 4.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - uap10.0 (UAP,Version=v10.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package Microsoft.Win32.Registry 4.5.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package Microsoft.Win32.Registry 4.5.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net461 (.NETFramework,Version=v4.6.1)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package System.Reactive.Core 4.1.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package System.Reactive.Core 4.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - uap10.0 (UAP,Version=v10.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package SixLabors.ImageSharp.Drawing 1.0.0-beta0005 is not compatible with net40 (.NETFramework,Version=v4.0). Package SixLabors.ImageSharp.Drawing 1.0.0-beta0005 supports:
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package Flurl.Http 2.3.2 is not compatible with net40 (.NETFramework,Version=v4.0). Package Flurl.Http 2.3.2 supports:
  - net45 (.NETFramework,Version=v4.5)
  - net46 (.NETFramework,Version=v4.6)
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package SixLabors.ImageSharp 1.0.0-beta0005 is not compatible with net40 (.NETFramework,Version=v4.0). Package SixLabors.ImageSharp 1.0.0-beta0005 supports:
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1)
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package System.Text.Encoding.CodePages 4.5.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package System.Text.Encoding.CodePages 4.5.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net46 (.NETFramework,Version=v4.6)
  - net461 (.NETFramework,Version=v4.6.1)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package IronPython 2.7.8.1 is not compatible with net40 (.NETFramework,Version=v4.0). Package IronPython 2.7.8.1 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1202	Package System.IO.Ports 4.5.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package System.IO.Ports 4.5.0 supports:
  - net461 (.NETFramework,Version=v4.6.1)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - uap10.0.16299 (UAP,Version=v10.0.16299)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project MissionPlanner.ArduPilot is not compatible with net40 (.NETFramework,Version=v4.0). Project MissionPlanner.ArduPilot supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project solo is not compatible with net40 (.NETFramework,Version=v4.0). Project solo supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project ZedGraph is not compatible with net40 (.NETFramework,Version=v4.0). Project ZedGraph supports: net461 (.NETFramework,Version=v4.6.1)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project LibVLC.NET is not compatible with net40 (.NETFramework,Version=v4.0). Project LibVLC.NET supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project Core is not compatible with net40 (.NETFramework,Version=v4.0). Project Core supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project ManagedNativeWifi.Simple is not compatible with net40 (.NETFramework,Version=v4.0). Project ManagedNativeWifi.Simple supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project AviFile is not compatible with net40 (.NETFramework,Version=v4.0). Project AviFile supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project MissionPlanner.Maps is not compatible with net40 (.NETFramework,Version=v4.0). Project MissionPlanner.Maps supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project MissionPlanner.Utilities is not compatible with net40 (.NETFramework,Version=v4.0). Project MissionPlanner.Utilities supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project Zeroconf is not compatible with net40 (.NETFramework,Version=v4.0). Project Zeroconf supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project MetaDataExtractor is not compatible with net40 (.NETFramework,Version=v4.0). Project MetaDataExtractor supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project SharpZipLib is not compatible with net40 (.NETFramework,Version=v4.0). Project SharpZipLib supports:
  - net45 (.NETFramework,Version=v4.5)
  - netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project MissionPlanner.Strings is not compatible with net40 (.NETFramework,Version=v4.0). Project MissionPlanner.Strings supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project MissionPlanner.Comms is not compatible with net40 (.NETFramework,Version=v4.0). Project MissionPlanner.Comms supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project MissionPlanner.Controls is not compatible with net40 (.NETFramework,Version=v4.0). Project MissionPlanner.Controls supports: net461 (.NETFramework,Version=v4.6.1)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project GDAL.NET is not compatible with net40 (.NETFramework,Version=v4.0). Project GDAL.NET supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project px4uploader is not compatible with net40 (.NETFramework,Version=v4.0). Project px4uploader supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project WebCamService is not compatible with net40 (.NETFramework,Version=v4.0). Project WebCamService supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project GeoUtility is not compatible with net40 (.NETFramework,Version=v4.0). Project GeoUtility supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project tlogThumbnailHandler is not compatible with net40 (.NETFramework,Version=v4.0). Project tlogThumbnailHandler supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project KMLib is not compatible with net40 (.NETFramework,Version=v4.0). Project KMLib supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project GMap.NET.WindowsForms is not compatible with net40 (.NETFramework,Version=v4.0). Project GMap.NET.WindowsForms supports: net461 (.NETFramework,Version=v4.6.1)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project GMap.NET.Core is not compatible with net40 (.NETFramework,Version=v4.0). Project GMap.NET.Core supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project Transitions is not compatible with net40 (.NETFramework,Version=v4.0). Project Transitions supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project SharpAdbClient is not compatible with net40 (.NETFramework,Version=v4.0). Project SharpAdbClient supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project MAVLink is not compatible with net40 (.NETFramework,Version=v4.0). Project MAVLink supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project Arduino is not compatible with net40 (.NETFramework,Version=v4.0). Project Arduino supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1	
Error	NU1201	Project SharpKml is not compatible with net40 (.NETFramework,Version=v4.0). Project SharpKml supports: netstandard2.0 (.NETStandard,Version=v2.0)	MissionPlanner	D:\unrealeditor\MissionPlanner-master\MissionPlanner.csproj	1

**Comment by meee1** [comment]
Error Couldn't process file Config.zh-Hans.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.

for some reason has a weird windows attribute. please fix this, this has nothing to do with the MP compile, and all to do with how you saved the files to your pc.
