### ISSUE TITLE
Can’t update firmwarre, board has been retired

### ISSUE THREAD

**Issue by dindibo** [ArduPilot/MissionPlanner#1960]
#### Issue details

I tried to update my 2.5 APM board to higher firmware, I went to Mission Planner > Initial Setup > Update Firmware and tried to update the firmware, but I've got an error saying:

> The board has been retired, Mission Planner this will upload the last available version to your board (AC 3.2.1/AP 3.4.0)

#### Version
2.5

#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Quad-copter

#### Hardware type
Arducopter - APM 2.5

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
I don't see any issues?
