### ISSUE TITLE
Losing MAG_CAL_REPORT messages against master

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#1963]
MissionPlanner onboard compass cal is failing as MAG_CAL_REPORT is being lost. It looks like the MP mavlink2 parser is not handling the two new extension fields in the msg (the orientation fields)

**Comment by meee1** [comment]
@tridge ive had a look at this, and the packet length hasn't changed in some time. so what version of MP is @pkocmoud using?

**Comment by pkocmoud** [comment]
Hi I am using Mission Planner 1.3.58 build 1.3.6794.30567 ArduCopter V3.7-dev (33a215e8) per the form header.
It should be noted that compass cal finishes correctly if I set the SERIAL0_PROTOCOL = 1

**Comment by meee1** [comment]
@pkocmoud where you connected via usb? or esp8266 with a new firmware?

**Comment by pkocmoud** [comment]
USB Only.

**Comment by meee1** [comment]
@pkocmoud could you try beta MP

got help > update beta

**Comment by tridge** [comment]
looks like this is just an update to the XML.
Does the MP MAVLink2 parser accept packets with length greater than expected? It should do that to allow for extensions that weren't in the XML at the time MP was built

**Comment by tridge** [comment]
I just updated to beta 1.3.6794.30567 and it fails in the same way

**Comment by meee1** [comment]
just made another update, to not Len check mavlink 2 packets
https://github.com/ArduPilot/MissionPlanner/commit/010b7725606be08da2a9074ab260e4bdff68ea78

**Comment by tridge** [comment]
thanks Michael!

**Comment by pkocmoud** [comment]
Just updated to 1.3.6867.5351 and the compass calibration now completes without issue. Thank you!

**Comment by meee1** [comment]
perfect. thanks

**Comment by whiani** [comment]
Hi I am using Mission Planner 1.3.56 build 1.3.6672.30243 ArduPlane 3.9.2beta3(32c5e6b).
The compass calibration screen is not reporting success once calibration completes. Instead the green bars stay at 99% ,but the compass calibration is successful when i set AUTO_ROT to 0(default is 2).
My quction is why the compass calibration is successful  when the AUTO_ROT is  0 sending the same length mag_cal_report message packet ,although you  delete Len check mavlink 2 packets.

**Comment by meee1** [comment]
please update your missionplanner

**Comment by whiani** [comment]
Thanks i know that the compass calibration can be successfully calibrated by updates  missionplanner( new missionplanner is delete Len check mavlink 2 packets).
But my quction is why the compass calibration is successful when the AUTO_ROT is 0 sending the same length mag_cal_report message packet ,although you delete Len check mavlink 2 packets.

**Comment by meee1** [comment]
because the new extension fields are not being set, so it is a valid packet as they get trimmed off.

**Comment by whiani** [comment]
I have begun to think so.however i set AUTO_ROT(default is 2) to 0 ,the new extension fields are also sent,the compass calibration is successful.so can  AUTO_ROT parameter change the length of mag_cal_report message packet?I didn't see that.
