### ISSUE TITLE
C# uploading waypoints

### ISSUE THREAD

**Issue by ahronaldo** [ArduPilot/MissionPlanner#1975]
Is there any possibility to add a send waypoints button or function to the SimpleExample included in the ExtLib folder ?
even if a single waypoint that will help .
Many Thanks in advance .

**Comment by meee1** [comment]
ive added a very basic wp upload. ie one point.

**Comment by ahronaldo** [comment]
You made my day, thank you so much I really appreciate it @meee1

**Comment by ahronaldo** [comment]
@meee1 
The readsomedata function through an error which avoids the process to be done.
is there any solution .

Many thanks in advance.
