### ISSUE TITLE
TLOG: Extract Params not working

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/MissionPlanner#1983]
#### Issue details
Attempting to extract parameters no longer works. 

#### Version
1.3.59 build 1.3.6870.35631

Parameter extract works with 1.3.56

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Sub

#### Hardware type
Cube running plane 3.9.2 stable chibios

#### Logs
https://www.dropbox.com/sh/2am7xx25l6s3jlj/AAAjipRCeAkoTi1r70Fd8fYha?dl=0

![image](https://user-images.githubusercontent.com/35429159/48160372-4a5aaf00-e29d-11e8-96ae-1467c03069be.png)

**Comment by meee1** [comment]
@Naterater thanks for the report. ive fixed the issue in beta MP.
