### ISSUE TITLE
Unable to use Zoom To function

### ISSUE THREAD

**Issue by tatsuy** [ArduPilot/MissionPlanner#1989]
I cannot use Zoom To ([Map Tool] - [Zoom To]) function using Google Map or Bing Map.
![image](https://user-images.githubusercontent.com/16643069/48556607-ca30eb00-e927-11e8-84b2-ccb36a25d266.png)
It works in OSM.

**Comment by dfiter** [comment]
I have the same problem. It seems to be a problem with the connection with Google Earth. 
The elevation graph does not give information from google earth either. Any idea?

**Comment by meee1** [comment]
look like google is not charging for this service

**Comment by tatsuy** [comment]
I closeed that I know it is not a problem on the MP side.
