### ISSUE TITLE
Unable to build mission planner in windows 7

### ISSUE THREAD

**Issue by bagaona** [ArduPilot/MissionPlanner#1992]
#### Issue details
_Please describe the problem, or desired feature_
Can't build! always dll is missing
#### Version
_What version was the issue encountered with_
Tried many. Even the beta
#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
MP will not build on windows 7.
please use windows 10
