### ISSUE TITLE
When disconnected, skip all param failure dialogs

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/MissionPlanner#1998]
When uploading a param file I inadvertently crash the sim. This is a problem with my custom sim compile and/or params which kills the sim and I immediately become disconnected. Meanwhile, Mission Planner gets stuck trying to upload the rest of the params and fails repeatedly. It times out over and over and over and I can't stop it. Takes forever and the only way to stop is to do a hard kill of Mission Planner.

**Comment by meee1** [comment]
this should be resolved now
