### ISSUE TITLE
MP "Previous Firmware" Links Broken

### ISSUE THREAD

**Issue by RANNDON** [ArduPilot/MissionPlanner#1999]
#### Issue details
I have tried every MP version since September 2016, but I cannot download AP 3.7.1 to revive a model that has been out of service for a while. All of the early MP versions give "unexpected error" when I select Previous Versions or AP 3.7.1. The later MP versions substitute AP 3.6 when I select AP 3.7.1

#### Version
MP 1.3.40 to MP 1.3.59

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Monoplane

#### Hardware type
Pixhawk

#### Logs
Here is a screenshot of the error

![mp previous firmware issue](https://user-images.githubusercontent.com/12687772/48925039-a0715880-ef13-11e8-97d4-d65a58be0d12.jpg)

**Comment by meee1** [comment]
this should be resolved in the latest release version
