### ISSUE TITLE
initial setup missing menu items in latest beta

### ISSUE THREAD

**Issue by hdtechk** [ArduPilot/MissionPlanner#2002]
mandatory and optional hardware and firmware are missing from menu
1.3.61 build1.3.6903.42945

![mp1](https://user-images.githubusercontent.com/19457559/48990735-da498700-f0ec-11e8-9d84-b0d26ff0b91e.JPG)
![mp2](https://user-images.githubusercontent.com/19457559/48990743-e3d2ef00-f0ec-11e8-8aac-a846317339ab.JPG)

**Comment by meee1** [comment]
Thanks
Fixed
