### ISSUE TITLE
LogViewer fails to show CTUN items from .bin type logs

### ISSUE THREAD

**Issue by vierfuffzig** [ArduPilot/MissionPlanner#2012]
log viewer doesn't show CTUN group when opening .bin type flashlogs. after conversion from .bin to .log the CTUN group is well accessible again.

Version 1.3.61 build 1.3.6909.22370

**Comment by meee1** [comment]
could i get a copy of your bin?

**Comment by vierfuffzig** [comment]
thanks for looking into this, michael!
just an example: https://github.com/vierfuffzig/Chibios-miscellaneous/blob/master/00000003.BIN
i suspected something wrong with the actual log i was trying to review first, but the issue shows in all log files actually.

cheers, basti.

**Comment by meee1** [comment]
Thanks for reporting this. ive found the problem. and resolved it in the latest beta version

**Comment by meee1** [comment]
the cause was that NTUN's internal id is 0. and i had code that ignored 0.

**Comment by vierfuffzig** [comment]
awesome, thanks a lot!
