### ISSUE TITLE
Status items disorganized

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/MissionPlanner#2015]
#### Issue details
It's hard to find items when they're not in alphabetical order. This also applies to the USER ITEMS list that can be added to the VFR HUD. I also heard that these item titles do not align with the mavlink messages, making them hard to understand where they are coming from in ardupilot.

#### Version

ALL

**Comment by meee1** [comment]
the user item list is already alphabetical?

im not as sure on a change is a good idea on the status screen however

**Comment by Naterater** [comment]
They are not alphabetical. Try finding raw_temp for example. 

![image](https://user-images.githubusercontent.com/35429159/49335730-c1434900-f5b8-11e8-98e7-35da4e0e8a59.png)

**Comment by Naterater** [comment]
Thank you for alphabetizing this.
