### ISSUE TITLE
Flight Plan Column Hides Descriptions

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/MissionPlanner#2019]
#### Issue details
For descriptions that fall in column 2 through 4, the description cannot be seen because the columns are fixed-width. DO_JUMP is one of many parameters that have descriptions cut by the fixed column widths.

![image](https://user-images.githubusercontent.com/35429159/49347591-80553e00-f665-11e8-9f55-84898b7875f8.png)

#### Version
All

**Comment by meee1** [comment]
I do agree, but don't have a good answer.
currently its set to 
auto fit to DisplayedCellsExceptHeader
the reason for this is that some column names are too verbose.

**Comment by meee1** [comment]
ive made some changes. hopefully it improves this...
