### ISSUE TITLE
Duplicate CurveItem elements on the Legend are displayed [BUG]

### ISSUE THREAD

**Issue by TEAM-NAH** [ArduPilot/MissionPlanner#2020]
#### Issue details
**Steps to reproduce:**
1. Run the application
2. Select "Telemetry Logs" CTA when the MissionPlanner GUI loads
3. Select the "Tlog > Kml or Graph" CTA
4. Load in a tlog file by clicking on the "Graph Log" CTA and selecting the tlog file
5. Notice that when checkmarking a CurveItem listed on the right hand side of the log analyses page, clicking on the CurveItem's label name produces duplicate Legend elements to appear.

**Expected results:** Clicking on the label name should not produce duplicate Legend Items to appear as it takes up valuable Graph space and is probably not intended.

**Processor:** Intel Core i7-3630QM CPU @ 2.40 GHZ

**RAM:** 8 GB

**System type:** 64-bit Operating System

**OS:** Windows 10

**Notes:**
![image](https://user-images.githubusercontent.com/44145058/49347689-5bf16580-f655-11e8-8ab6-ddacadee389e.png)

#### Version
Pulled from latest changes.
1 parent 7d3286e commit 12f6bee

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ + ] Rover
[  ] Sub

#### Airframe type
NA, will update this section on Tuesday 12/4/2018 with the correct information.

#### Hardware type
NA, will update this section on Tuesday 12/4/2018 with the correct information.

#### Logs
.tlog file is not supported, so I cannot provide the log file that I tested with.

**Comment by meee1** [comment]
I discovered this myself just today
if you click the tick box it works fine. if you click the text near the tick box, it dups.
