### ISSUE TITLE
Display This - Text Wrap Issue

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/MissionPlanner#2021]
#### Issue details
I think DistFromMovingBase is too long for the Display This table. Thank you for making it alphabetical!

![image](https://user-images.githubusercontent.com/35429159/49347684-1b4e1800-f666-11e8-8e71-84ba9db98244.png)

#### Version
Beta - 1.3.61 build 1.3.6910.18181

#### Hardware type
Windows 10 - 4k display

**Comment by meee1** [comment]
how did you get to that screen? there are a few way to get to it, so just want to make sire im looking at the same thing.

**Comment by Naterater** [comment]
Double-click on a "quick" item under the HUD.

**Comment by meee1** [comment]
fixed here https://github.com/ArduPilot/MissionPlanner/commit/05b3846f1d0884c8580d44da419b7940dceb3990
