### ISSUE TITLE
Initial Setup >> Install Firmware screen's left column white-and-red

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2024]
I've seen this happen twice now after leaving MP open on the Install Firmware screen for a long time (perhaps 30min).  Not at all sure what's going on but of course restarting MP returns it to normal.
![mp-crash-on-install-firmware-screen](https://user-images.githubusercontent.com/1498098/49486172-d225e000-f880-11e8-8ad9-ab609356aba4.png)

**Comment by meee1** [comment]
I think it has something to do with being minimized. but I have not replicated it yet. ie the height going to 0 is the cause, just not sure how its getting to 0 in the first place.

**Comment by rmackay9** [comment]
hvaen't seen this for a while so closing.
