### ISSUE TITLE
Connection list format

### ISSUE THREAD

**Issue by kossumov** [ArduPilot/MissionPlanner#2033]
I tried to connect multiple vehicle in mission planner, and succeed in connecting them one by one.
I find there is a connection list option, but when I chose this one, It ask me to upload a file.
I don't know the proper format.
What's the format?

**Comment by meee1** [comment]
Format:
tcp://IP:PORT
udp://IP:PORT
udpcl://IP:PORT
serial://PORTNAME:BAUD

**Comment by meee1** [comment]
https://www.facebook.com/284466628312940/videos/526902511117569/
is a link to a video about it

**Comment by kossumov** [comment]
Thanks!

**Comment by WilmerAriza** [comment]
How do you use Connection LIST the video is not available anymore
