### ISSUE TITLE
URI missing when uploading a new arduplane software

### ISSUE THREAD

**Issue by JeyPi** [ArduPilot/MissionPlanner#2039]
https://www.goodluckbuy.com/minipx4-beta-version-flight-controller-support-pwm-ouptut-for-fpv-multicopter-quad.html

![image2](https://user-images.githubusercontent.com/16972472/49877182-c1dfa900-fe1c-11e8-8000-b1655e022826.jpg)

_Originally posted by @JeyPi in https://github.com/ArduPilot/MissionPlanner/issues/1915#issuecomment-446612699_

**Comment by meee1** [comment]
are you sure the version you are trying to upload was available for the board you are using. I doubt it was

**Comment by JeyPi** [comment]
You might be correct as the Pixhawk light was not having any problems with the new version.
The board I mentioned there fore seems to be defective or not compatible with the version. It was not compatible with any of the older versions either.
