### ISSUE TITLE
Decode COMPASS_DEVIDs for users

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2056]
Compasses setup troubles and compass issues in general are perhaps our worst long term problem.  One small thing that may help is decoding the device id for users so they have a better idea of what compasses are being used.  This will help in these ways:

- users will have a better chance of realising if compasses are appearing/disappearing on the bus due to cabling issues or firmware changes (new versions of AP support more compasses)
- in cases where there are more than 3 compasses available, users can more easily know how to set the COMPASS_TYPEMASK parameter to make the 4th, 5th compass appear in place of the 1st,2nd or 3rd.  At the moment users really have no easy way to know how disabling a driver will affect what compasses appear because they have no easy way to map the COMPASS_DEVID/2/3 to the compass names which are used in the COMPASS_TYPEMASK parameter.

Below is a mock-up of the MP's compass setup screen with the COMPASS_DEVID broken out into it's four components (bus type, bus number, address on the bus, device type)
![mp-compass-devid](https://user-images.githubusercontent.com/1498098/50390694-ba55c380-077d-11e9-8d9e-09a6ae110cd1.png)

We have a [python script here which can do the decoding](https://github.com/ArduPilot/ardupilot/blob/master/Tools/scripts/decode_devid.py) but in short this is what I think we need:

bus type: COMPASS_DEVID & 0x07.  1 = I2C, 2 = SPI, 3 = UAVCAN, 4 = SITL
bus number: (COMPASS_DEVID >> 3) & 0x1F.
address on the bus: (COMPASS_DEVID >> 8) & 0xFF.
device type: COMPASS_DEVID >> 16 and then use the table below to convert to a human understandable string:

1, HMC5883 (old)
2, LSM303D
4, AK8963
5, BMM150
6, LSM9DS1
7, HMC5883
8, LIS3MDL
9, AK09916
10, IST8310
11, ICM20948
12, MMC3416
13, QMC5883L
14, MAG3110
15, SITL
16, IST8308

**Comment by meee1** [comment]
ive got all the code to do this already, and will be coming in the near future
https://github.com/ArduPilot/MissionPlanner/commit/f8e0c4907d3750ff8f6bb6bb4387feef9f7a9fc9#diff-fac9868a389bd41a084b8e1ff6c74eb4

**Comment by highfreq** [comment]
This is really great!!! Looking forward to test it. It'll be a huge step forward in better understanding what is going on with compasses.
Hope it'll pickup UAVCAN mags too.

**Comment by highfreq** [comment]
Is there any news on this? Looking forward to test it.

**Comment by rmackay9** [comment]
I'd love to get this out to users as well because it will help reduce my support load a bit by making it easier for users.

**Comment by rmackay9** [comment]
Sorry to be persistent but [here's a case where a user is struggling to figure out which compasses they have](https://discuss.ardupilot.org/t/crash-spinning-quad-on-pixracer-r15-arducopter-3-6-6/38666/11) and another user is sending a python file to them to do the decoding.. in practice it's unlikely that most users will be able to figure out how to run a script.

**Comment by rmackay9** [comment]
This is done now although the hardware ids are on a separate HWID page.. I guess it's OK although I think having them on the compass calibration screen would also be good.

**Comment by juancamilog** [comment]
> This is done now although the hardware ids are on a separate HWID page.. I guess it's OK although I think having them on the compass calibration screen would also be good.

What is this Heidi page you're talking about?

**Comment by rmackay9** [comment]
@juancamilog, It can be found under Config/Tuning >> Mandatory Hardware >> HWID
