### ISSUE TITLE
update github project URL to http://ardupilot.org/planner/

### ISSUE THREAD

**Issue by drnic** [ArduPilot/MissionPlanner#2088]
Currently the github.com project page links to http://planner.ardupilot.com/ which does not redirect to the new homepage at http://ardupilot.org/planner/

<img width="698" alt="screen shot 2019-02-18 at 9 43 51 am" src="https://user-images.githubusercontent.com/108/52921332-b8fddd00-3361-11e9-8ba1-6535d3caa839.png">

Could someone with admin permissions pls update the github project description/url to http://ardupilot.org/planner/?

**Comment by meee1** [comment]
Fixed Thanks
