### ISSUE TITLE
Proximity viewer must be closed/re-opened before refreshing starts if only one range finder

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2092]
an AP Partner reported today that the proximity viewer needs to be re-opened before it will start updating if there's only one forward facing range finder.

They were using MP 1.3.56 build 1.3.6672.30243 with Copter-3.6.5.

**Comment by meee1** [comment]
Update mission planner.

**Comment by rmackay9** [comment]
OK, txs.
