### ISSUE TITLE
SITL Options in Mission Planner

### ISSUE THREAD

**Issue by aknight0** [ArduPilot/MissionPlanner#2094]
Is it possible to use the various SITL options with the built in Mission Planner SITL?  Specifically I'm interested in setting the vehicle start position, which I see is normally passed to sim_vehicle.py like
`sim_vehicle.py -L Ballarat --console --map`

**Comment by meee1** [comment]
Yes it's possible, just drag your start position around the map to where you want to start

**Comment by aknight0** [comment]
Great, that was easier than I thought!  Some trial and error also turned up that the other SITL parameters I wanted to change were exposed in Mission Planner's full parameter list.  Thanks!
