### ISSUE TITLE
no scrolling on left menu tree

### ISSUE THREAD

**Issue by twistedwings** [ArduPilot/MissionPlanner#2101]
there is no scrolling on the menu tree, see screenshot.
Lower items (below Antenna Tracker) cannot be reached.

MP 1.3.63, Windows 10

![scrolling](https://user-images.githubusercontent.com/562809/54494906-5277ca80-48df-11e9-8f3d-f9b3906887ef.JPG)

**Comment by meee1** [comment]
the latest beta fix's this
