### ISSUE TITLE
Custom MAVlink messages to connect

### ISSUE THREAD

**Issue by mihalyn** [ArduPilot/MissionPlanner#2102]
#### Issue details
We are developing a custom MAVlink interface for a raspberry pi based autopilot system. What are the minimum set of messages Mission Planner needs to say that the device is connected over telemetry?
We have tested it with only heartbeat messages, without success.

#### Version
Mission Planner 1.3.62.1 on Windows 10

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
fixed wing

#### Hardware type
custom raspberry pi based hardware

**Comment by meee1** [comment]
1. mavlink_heartbeat_t
2. mavlink_param_request_list_t
3. mavlink_param_request_read_t
4. mavlink_param_value_t
