### ISSUE TITLE
Write Params Window Missing OK/similar button

### ISSUE THREAD

**Issue by apache405** [ArduPilot/MissionPlanner#2132]
#### Issue details
In Full param list, the write raw params window is missing an ok or similar button.

#### Version
1.3.64.2 build 1.3.7051.21787

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ x ] Rover
[  ] Sub

#### Airframe type
Rover 3.5.0 w/ Chibios

#### Hardware type
Cube

#### Logs
See Screen shot.
![2019-04-22 (3)](https://user-images.githubusercontent.com/2415334/56540388-70a79a80-651d-11e9-8fd2-fc7647212456.png)

**Comment by meee1** [comment]
fixed thanks jeff
