### ISSUE TITLE
mono MissionPlanner.exe doesn't show .BIN logs on DataFlash log review

### ISSUE THREAD

**Issue by Jaaaky** [ArduPilot/MissionPlanner#2143]
#### Issue details
_On Linux `mono MissionPlanner.exe` doesn't show .BIN logs when I open DataFlash log review
The file browser doesn't show any .BIN extensions by default and I've to type *.BIN in each directory to view any DF log files_

#### Version
_Mission Planner 1.3.66_
_Mono 5.20_

#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

**Comment by meee1** [comment]
will be a case issue.
what case is the file on the filesystem?

**Comment by Jaaaky** [comment]
On Linux everything is case sensitive by default. Even FAT32 filesystem.

**Comment by Jaaaky** [comment]
And DF logs extension is always upper case .BIN

**Comment by meee1** [comment]
ok, so always uppercase

**Comment by Jaaaky** [comment]
I can confirm it's a case issue.
I could work-around it by `export MONO_IOMAP=drive:case` .. found through `man mono`

**Comment by meee1** [comment]
cool thanks for that feedback
ill add a note on MP startup
