### ISSUE TITLE
MP doesn't restore absolute WPs

### ISSUE THREAD

**Issue by Jaaaky** [ArduPilot/MissionPlanner#2146]
#### Issue details
On extract WPs from telemetry log; MP doesn't restore absolute WPs, it restores all as relative which is really confusing and troublesome.
It should restore ALT Frame as well with other wp info.

#### Version
_1.3.66_

#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

**Comment by Jaaaky** [comment]
Resolved? Close?

**Comment by meee1** [comment]
should be resolved yes
