### ISSUE TITLE
Bug: Battery Voltage always displayed as 0.00V

### ISSUE THREAD

**Issue by cheintz** [ArduPilot/MissionPlanner#2153]
#### Issue details
MissionPlanner displays BAT 0.00v (but reads current correctly). This is in the "status" tab, as well as user items.

Connecting with QGroundControl to the same aircraft shows the correct voltage.

#### Version
1.3.66 build 1.3.7054.36589
Windows 7 x64

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Flying Wing

#### Hardware type
PX4

#### Logs
n\a

**Comment by meee1** [comment]
could you try beta MP?

**Comment by cheintz** [comment]
Uninstall and reinstall fixed it. Previously what I had was upgraded, but I'm not sure what the original version was.

**Comment by rmackay9** [comment]
Great, thanks for the follow up, closing..
