### ISSUE TITLE
MP 1.3.66 doesn't "write/apply" changes as expected

### ISSUE THREAD

**Issue by Jaaaky** [ArduPilot/MissionPlanner#2159]
#### Issue details
Tested on Windows 10 and on Linux/Wine 
MP 1.3.66 doesn't apply/write what it should. Specially params.
For example, When I change any param value in Basic tuning, it often doesn't apply this until I move the curser to another box and then write changes again.
The problem is random but occurs frequently.
Also, in full params it usually doesn't write all modified params. Unless you change the curser away from the modified one.

#### Version
1.3.66
It doesn't occur on 1.3.64

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Sub
Didn't test on others

**Comment by meee1** [comment]
this is the focus but.

fixed in beta

i need to do a new release very soon
