### ISSUE TITLE
Config/Tuning: HWID page goes blank when attempting screen capture

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2204]
I sometimes want to capture the HWID page when trying to diagnose why a compass has gone missing.  When I press the "Alt" key however, at least 1/2 the time, the HWID page suddenly becomes blank which makes it difficult to perform a screen capture (Ctrl-Alt-PrintScreen)

**Comment by meee1** [comment]
fixed in beta

**Comment by rmackay9** [comment]
great, thanks!
