### ISSUE TITLE
videowriter

### ISSUE THREAD

**Issue by ashish-yadav1** [ArduPilot/MissionPlanner#2205]
video writer doesn't  write anyother format then avi 
It works fine for .avi extensions but the size is pretty huge for some seconds only so I want to compress it more.

so i want to store in mp4 format but it always give error 
Error  Message=Unable to create VideoWriter. Make sure you have the specific codec installed

**Comment by meee1** [comment]
this is by design. there are too many device that dont have enough cpu to use a better codec. you can reencode as you require however

**Comment by ashish-yadav1** [comment]
How can I get Google Earth 3D features in FlightPlanner
and Map Switch From 2D to 3D
like this
