### ISSUE TITLE
DF Log viewer shows mode numbers only

### ISSUE THREAD

**Issue by vierfuffzig** [ArduPilot/MissionPlanner#2208]
Issue: LogViewer does not display ArduPlane flight mode names, only numbers

![DF_LogView_mode_issue](https://user-images.githubusercontent.com/9342253/63641506-0875ea80-c6b0-11e9-8449-ae149d60c194.jpg)

Version: latest

Platform: ArduPlane 3.10dev / current master

Hardware type: OmnibusF4ProV3 and MatekF405-Wing

Logs: 
https://github.com/vierfuffzig/Chibios-miscellaneous/raw/master/ASW28_omnibus.BIN
https://github.com/vierfuffzig/Chibios-miscellaneous/raw/master/Talon_MatekF405Wing.BIN

**Comment by meee1** [comment]
what MP version?

**Comment by vierfuffzig** [comment]
thanks for looking into this!
first noticed on 1.3.68.1 build 1.3.7174.16110  through 1.3.68.1 build 1.3.7186.15082 of today.
i found it depends on fw version the log was acquired with too. respective logs written on plane master of the last few weeks.
[this log](https://github.com/vierfuffzig/Chibios-miscellaneous/raw/master/nanoT.BIN) written with plane 3.9.8 displays mode names correctly.

**Comment by vierfuffzig** [comment]
this has been fixed along the way, so closing.
