### ISSUE TITLE
MavlinkFTP: FYI

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/MissionPlanner#2216]
FYI, in case you haven't seen, MAVLink FTP specifies now a NACK error for when a file/directory is not found: https://mavlink.io/en/services/ftp.html#error_codes

you may want to implement this, instead of the previous "workaround".

thx btw for the MAVLinkFTP feature, I'm lovin' it :)

**Comment by meee1** [comment]
@bugobliterator looks like the error code enum has changed?

**Comment by olliw42** [comment]
only extended by one entry, not changed

**Comment by meee1** [comment]
Ardupilot already has that extra as Busy, not 404
