### ISSUE TITLE
SITL simulator reports pre-arm warning: throttle below failsafe

### ISSUE THREAD

**Issue by gzhang8** [ArduPilot/MissionPlanner#2219]
#### Issue details
When launching simulator from MP under quad mode, we see this pre-arm warning and not able to do further flight simulation. 

#### Version
1.3.66
#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Simulated quad
#### Hardware type
SITL
#### Logs
![image](https://user-images.githubusercontent.com/16281107/64911998-c273db80-d6dd-11e9-9422-719c45fd3c7c.png)

**Comment by dhollenbeck1** [comment]
The plane does not work either.

**Comment by dhollenbeck1** [comment]
Found a commit in the AP_HAL_SITL layer: 
https://github.com/ArduPilot/ardupilot/commit/1735563bb790ff70b346b1bf5c5342afb34f61c2

Seems to be the issue we are experiencing here.

**Comment by rmackay9** [comment]
Sorry for the troubles, a PR got through without enough testing and review.  It's been reverted in master now so I think it's OK to close this issue.
