### ISSUE TITLE
What is the difference between write wps and write wps fast?

### ISSUE THREAD

**Issue by rain-0** [ArduPilot/MissionPlanner#2226]
![image](https://user-images.githubusercontent.com/47851758/66177843-bc966800-e695-11e9-9e89-3ff45829c4db.png)
My ground station has these two ways of writing wps, but what is the difference between them?

**Comment by huangyangl** [comment]
i dont know

**Comment by meee1** [comment]
one is a tradition write, one at a time.
the fast one will try 10 at a time, but requires a lossless link. ie usb
