### ISSUE TITLE
Geofence Breach displayed when no actual breach?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2241]
I think the "Geofence Breach" message may not be being cleared correctly.  This is testing with Copter-4.0.0-dev and latest beta MP.

Below screen shots show what I mean.  The "Geofence Breach" is displayed but as far as I can tell the "FENCE_STATUS" message being sent is showing there are no actual breaches.

![image](https://user-images.githubusercontent.com/1498098/67921495-48df7080-fbeb-11e9-9265-85e5f98f64a1.png)
![image](https://user-images.githubusercontent.com/1498098/67921498-50067e80-fbeb-11e9-8261-b467286559f8.png)

**Comment by meee1** [comment]
the message comes from 
MAV_SYS_STATUS_SENSOR

so i asume there is a reporting bit error in there

**Comment by rmackay9** [comment]
@meee1, ok, I see the issue.  It's all these extra checks that have been added. https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_Fence/AC_Fence.cpp#L455
