### ISSUE TITLE
Mission Planner conflicts with Wi-Fi

### ISSUE THREAD

**Issue by N7LS** [ArduPilot/MissionPlanner#2258]
#### Issue details
Hello guys, i recently encountered an issue while installing mission planner. The version prior to 1.3.68 was not working so I thought about uninstalling it and re-installing the newest version. However, right after installing it, I was unable to connect to my wifi (ethernet is not an option). A "unable to connect" message just popped up (wireless drivers etc were all just fine), so I was forced to do a system restore which solved the connectivity issue but rendered mission planner useless, once more. thoughts?
#### Version
1.3.68

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
Mission planner has nothing to do with your wifi. im not sure how these are linked at all
