### ISSUE TITLE
ADSB objects do not disappear if flight controller is disconnected

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2261]
While testing object avoidance with Copter-4.0.0 I've noticed that the circles representing objects which are sent to MP using the ADSB message don't disappear.  For example the image below is for a vehicle that hasn't sent any ADSB messages in several minutes.

![image](https://user-images.githubusercontent.com/1498098/69694835-8c12fd80-111d-11ea-859c-20decf304162.png)

**Comment by meee1** [comment]
this should be fixed in beta.

**Comment by rmackay9** [comment]
Great, thanks!
