### ISSUE TITLE
bootloader update hangs for long time

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#2268]
mavlink bootloader update hangs for a long time, and doesn't seem to tell the user if it succeeded. The update only takes about 1s, and gives the usual command long response code

**Comment by meee1** [comment]
@tridge there are alot of printf's in the update code, this is causing a sync issue
eg hal.console->printf("Flashing %s @%08x\n", fw_name, (unsigned int)addr);

**Comment by tridge** [comment]
@meee1 ahh, ok! I can fix that I think
