### ISSUE TITLE
Missing "Draw Polygon" Ver. 1.3.70

### ISSUE THREAD

**Issue by calstrom** [ArduPilot/MissionPlanner#2274]
#### Issue details
No 'Draw Polygon' option from drop down menu when Flight Planning in Mission Planner.

#### Version
1.3.70 build 1.3.7277.34800
Windows 10 Build 1099

#### Platform
[X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
N/A

#### Hardware type
N/A

#### Logs
N/A
![image](https://user-images.githubusercontent.com/54720956/70497495-2f71f400-1ac8-11ea-8fe9-98a510514e7a.png)

**Comment by meee1** [comment]
see the round circle to the left, click that

**Comment by calstrom** [comment]
Thank you for your help and quick response! I did not notice or use that in the past.
