### ISSUE TITLE
Flight Data >> Tuning selector "Display This" window is very wide

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2286]
I've found that after checking the Tuning box on the Flight Data screen the "Display This" window is very wide.

I use a computer with two screens and the window appears using the full width of both screens with the right side largely blank.  This happens regardless of whether the MP's main screen is full screened or not.

**Comment by meee1** [comment]
This should be fixed

**Comment by rmackay9** [comment]
Yes, fixed, thanks!
