### ISSUE TITLE
Log Browser FOLL.Alt scaling error

### ISSUE THREAD

**Issue by twistedwings** [ArduPilot/MissionPlanner#2293]
![image](https://user-images.githubusercontent.com/562809/72093522-d8547e80-3314-11ea-830b-3e34e0249204.png)

Values in the data grid are between -196 and 473 (cm)
Scaling should be in meters.

![image](https://user-images.githubusercontent.com/562809/72093689-2ff2ea00-3315-11ea-849f-2f3635cfcb6a.png)

**Comment by rmackay9** [comment]
What's odd is that it appears fine for me with MP 1.3.70 build 1.3.7312.21688.
![image](https://user-images.githubusercontent.com/1498098/72113339-8139c280-3383-11ea-85d2-ba577f59d735.png)

Here's a link to the log: https://www.dropbox.com/s/9scyc81jyxf5e2l/twisted-wings-follow-log.bin?dl=0

**Comment by meee1** [comment]
it appears correct for me as well.

did you load the bin or log file?

**Comment by twistedwings** [comment]
I have loaded the bin file.
When loading the log file it looks like this:

![image](https://user-images.githubusercontent.com/562809/72126939-3feae800-336e-11ea-9e0a-35a3277c571a.png)

**Comment by meee1** [comment]
yes, it is highly advisable to always use the bin file.
there are a few quirks when using a log file due to double scaling.

**Comment by rmackay9** [comment]
OK, I've reproduced this. I took the .bin file and used MP to convert it to a log file, then graphed FOLL.Alt and it looks like this:
![image](https://user-images.githubusercontent.com/1498098/72127166-1d7abe00-33b2-11ea-864d-35c10c3995a0.png)

I suspect the issue is that the FMT message for the FOLL message doesn't appear in the logs until lin 42941.

**Comment by meee1** [comment]
check the MULT as well.

**Comment by rmackay9** [comment]
I tried moving the FMT and FMTU messages up but it didn't help.  I don't see any different in the MULT messages..

**Comment by meee1** [comment]
ok, found the issue.
please try the latest beta MP. (in about 15 mins)

**Comment by twistedwings** [comment]
no change...

![image](https://user-images.githubusercontent.com/562809/72132255-c4456700-337e-11ea-9777-4e40be7c1967.png)

![image](https://user-images.githubusercontent.com/562809/72132284-d4f5dd00-337e-11ea-9217-ee56591e6fc6.png)

**Comment by meee1** [comment]
are you in a country with a . vs , issue?

**Comment by twistedwings** [comment]
I am in germany and have no idea what a . vs , issue is.

**Comment by meee1** [comment]
https://en.wikipedia.org/wiki/Decimal_separator
germany, uses a period.
i will need to check this again to resolve the localization issue.

**Comment by meee1** [comment]
could you send through the log file? not the bin. just want to see if the error is in converting to log, or reading the log

**Comment by twistedwings** [comment]
this is the log:

![image](https://user-images.githubusercontent.com/562809/72136825-f0b2b080-3389-11ea-9f7c-0821cd5f7cad.png)

**Comment by rmackay9** [comment]
![image](https://user-images.githubusercontent.com/1498098/72136639-95ee7880-33cc-11ea-8e0b-6836c06f6967.png)
It looks ok to me now..

**Comment by meee1** [comment]
i mean send the log via dropbox

**Comment by twistedwings** [comment]
I'm sorry here it is:

[https://drive.google.com/open?id=1yGeebd7b-bl5KGkTUcZ-LuBn2mmYLpbn](url)

**Comment by meee1** [comment]
ok new beta in another 15 mins
https://github.com/ArduPilot/MissionPlanner/commit/f5079406cee8f926b8964383af9ce48876d2b9ba

**Comment by twistedwings** [comment]
no change...

![image](https://user-images.githubusercontent.com/562809/72142906-05954100-3396-11ea-974e-85224015f811.png)

![image](https://user-images.githubusercontent.com/562809/72142935-13e35d00-3396-11ea-94ee-6554f8b35cd0.png)

**Comment by twistedwings** [comment]
issue is gone with latest beta...

![image](https://user-images.githubusercontent.com/562809/72155273-0ab4b900-33b3-11ea-930e-2b867ae1f79c.png)

![image](https://user-images.githubusercontent.com/562809/72155293-1acc9880-33b3-11ea-90d3-a3d6394c6588.png)

**Comment by meee1** [comment]
perfect.   the issue was around period vs comma's in the multiplier data
