### ISSUE TITLE
Load WP File shows scary error box when file is open in another program

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2303]
If a waypoint file is opened in another program (like Windows Excel) at the moment that "Load WP File" is used to attempt to load the file into the Flight Planner screen, MP shows a big scary error box.
![image](https://user-images.githubusercontent.com/1498098/72691776-4e55b280-3b6b-11ea-976c-549dbd381edb.png)

I don't actually understand why MP can't open the file as read-only and avoid the error but in any case, if that can't be resolved then it should at least print a human friendly "Failed to open file, locked by another program" or something similar.

**Comment by meee1** [comment]
the thing i take away from this is some other program has a read/write lock on the file. so MP cant not open it even for reading.

i will make the error a little less verbose however

**Comment by rmackay9** [comment]
@meee1, I don't think excel has taken a read/write lock on the file.  It's only taken a write lock.  I can open the file in NotePad++ so I don't see why MP can't open it.  I suspect MP is trying to open it with a write lock.

**Comment by rmackay9** [comment]
this seems to be resolved now, thanks!
