### ISSUE TITLE
Heli setup page has all fields disabled when using fw 4.0.0

### ISSUE THREAD

**Issue by danielhellin** [ArduPilot/MissionPlanner#2310]
#### Issue details
After updating the flight controller to the 4.0.0 helicopter, the Heli configuration page shows the disabled fields, so no configuration can be made.

#### Version
MP 1.3.70
AC 4.0.0

#### Platform
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Helicopter

#### Hardware type
Pixhawk
Hex Cube black

#### Logs
https://discuss.ardupilot.org/t/heli-setup-page-and-helicopter-4-0-0-fw/51482

**Comment by meee1** [comment]
Beta mp fixs 90% of this
