### ISSUE TITLE
Actions ChangeSpeed button not working

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2311]
From real life and SITL testing it seems that MP's Action tab's ChangeSpeed button is not sending the correct message to cause the vehicle to change it's speed while in autonomous modes.

I've confirmed using mavproxy that AP is correctly accepting COMMAND_LONG messages with the command field set to MAV_CMD_DO_CHANGE_SPEED (178).

[Copter's implementation can be seen here](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L687).  It looks like the target speed should be placed in param2 and should be in m/s.

**Comment by meee1** [comment]
This would have worked at some time. But newer firmware versions must have resulted in it ceasing to function

**Comment by rmackay9** [comment]
Another user reported this issue during the Copter-4.0.1 release. https://discuss.ardupilot.org/t/copter-4-0-1-released/51505/4

**Comment by rmackay9** [comment]
Re-tested with latest beta MP and it works, thanks!

By the way, sharing the number with the "Set Home Alt" is a bit naughty because it rounds off to the nearest integer.  I actually wonder why anyone needs to "Set Home Alt"... anyway, closing!

**Comment by nkikin** [comment]
Hi, I know this session is closed, but I just want to know which firmware version is required to get Actions changespeed button working?

**Comment by rmackay9** [comment]
@nkikin, yes, this should work with Copter-4.0.x (stable) or Copter-4.1.0-beta1 (the current beta).  If it doesn't work with 4.1.0 could you report in the [Copter-4.1.0 beta testing category](https://discuss.ardupilot.org/c/arducopter/6)?  I'm quite actively monitoring reports.

**Comment by nkikin** [comment]
@rmackay9 Thanks, it works with Copter-4.1.0.
