### ISSUE TITLE
Install Firmware screen displays scary error message when "All Options" is selected

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2312]
The title pretty much says it all.
![mp-firmware-install-error](https://user-images.githubusercontent.com/1498098/73116461-28208000-3f7a-11ea-9f8a-d31c469d20b8.png)

**Comment by meee1** [comment]
This error looks like an upgrader issue. Not that error of that specific option

**Comment by meee1** [comment]
traced to an older version dll located inside the plugins folder

**Comment by rmackay9** [comment]
this has been resolved, thanks!
