### ISSUE TITLE
DataFlash Err label is right justified instead of left justified

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2315]
While analysing a user log I was thrown off because the "Err: CRASH_CHECK -1" message appeared right-justified instead of left-justified.  This made me think that the crash had happened a lot earlier in the log than it actually did.  Below is a screen shot and you can see in the bottom "Data Table" area that the Error 12 appears at line 45670 but in the graph part at the top it appears from the label that it happens just before 44000.

![image](https://user-images.githubusercontent.com/1498098/73328369-d0955380-429c-11ea-8c98-4cd4dfb28b90.png)

**Comment by rmackay9** [comment]
But now strangely when I graph the exact same log again the label is in the correct place.. i'm confused.
![image](https://user-images.githubusercontent.com/1498098/73328742-36360f80-429e-11ea-84f4-a7c15ccc4f01.png)

**Comment by meee1** [comment]
it could be a drawing order issue. i will look further into it.

**Comment by rmackay9** [comment]
I'm on the latest beta and I haven't seen this again so closing, thanks!
