### ISSUE TITLE
Cannot save missions or compare parameters

### ISSUE THREAD

**Issue by JonReacher** [ArduPilot/MissionPlanner#2317]
Mission Planner hangs when after hitting SaveWP button. Cannot save missions. Also hangs when selecting Compare parameters. Cannot compare parameters.

Mission Planner 1.3.70

Windows 10

UPDATE: DISREGARD, multiple instances open apparently caused the issue

**Comment by meee1** [comment]
my first guess is it sounds like you have an inaccessible/network drive that is the default location when the save file dialog is trying to show. i think after 60 seconds or so MP would come back and allow you to change the drive.

**Comment by JonReacher** [comment]
Thanks. I was just updating and closing. I had another instance open on a hidden desktop that drove me crazy for a bit. Ooops!
