### ISSUE TITLE
geotiff Add in Gmap.Net MP

### ISSUE THREAD

**Issue by ashish-yadav1** [ArduPilot/MissionPlanner#2319]
i want to load geotiff file in gmap.net  without thrid party app or wms service using geoserver 
so how can i load geotiff file direct in mp

**Comment by meee1** [comment]
please search on the ardupilot forum. github is used for software issue tracking, not general support like this.
https://discuss.ardupilot.org/t/custom-imagery-in-mission-planner/10280/13
and
https://discuss.ardupilot.org/t/custom-maps-in-mission-planner/11290

**Comment by ashish-yadav1** [comment]
i have seen that but it use geoserver for wms custom  
can i directly while  geotiff file on  mp buy adding some thing in code?

**Comment by meee1** [comment]
please check the control-f > custom gdal button
this will load all image types in a directory to show on the map.
then pick GDAL Custom from the map drop down in flight planner

**Comment by ashish-yadav1** [comment]
thanks you so much
