### ISSUE TITLE
Script does not load when running Quadplane SITL (not matter where I put it).

### ISSUE THREAD

**Issue by pompecukor** [ArduPilot/MissionPlanner#2327]
#### Issue details
Script does not load when running Quadplane SITL 

#### Version
Latest MP

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X] Plane
[  ] Rover
[  ] Sub

Tried placing /Scripts/XYZ.lua in various folders.
SITL/Plane
SITL/Quadplane
Even in the root SITL

Plane loads script perfectly. However when running quad plane it just says cannot find lua or something like that.

**Comment by tridge** [comment]
works for me, path is:
C:\Users\andre\OneDrive\Documents\Mission Planner\sitl\quadplane\scripts

**Comment by tridge** [comment]
works now for @pompecukor, was param settings
