### ISSUE TITLE
DASHWARE file conversion incorrect

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/MissionPlanner#2349]
The "CSV" file that Mission Planner creates is incorrect format for DASHWARE....it should have trailing commas for any non-existent columns for a given log message  up to the maximum # of columns for a file....
Otherwise, DASHWARE will interpret those columns as "0" value instead of "NULL" value....which will create errors when you use the "USE PREVIOUS VALUE" method needed to get continuous values for items....ie....filling out BAT_Volt column using the method will get a new value of zero every GPS message since DASHWARE thinks the column in that message is zero instead of null....
Current work-around is to load the MP file into a normal spreadsheet program (which  will not populate zeros in missing columns) and write back in CSV format, which will put commas in for all missing column positions...

**Comment by kd0aij** [comment]
fixed by #2352
