### ISSUE TITLE
Bad right-click menu colors

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/MissionPlanner#2353]
#### Issue details
Bad right-click menu colors

#### Version
Current "advanced" installation: build 1.3.7277.34800  on MONO  
(fresh download)

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
N/A

#### Hardware type
n/a

#### Logs
![Screenshot from 2020-03-11 22-35-16](https://user-images.githubusercontent.com/1468842/76467135-3cfd8980-63e9-11ea-8119-efec10fabdd2.png)

**Comment by meee1** [comment]
What mono version?

**Comment by AndKe** [comment]
Sorry for forgetting that information.
```
Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Mon Jun 24 08:50:44 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
```

And thanks for finally trying to go multiplatform. (at least I see a lot more that works now, than before.)

**Comment by meee1** [comment]
can you try mono in the 6.x series?
![image](https://user-images.githubusercontent.com/511568/76750088-9a625380-67b8-11ea-965f-b55ac74db64b.png)

`Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:20:20 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)`

**Comment by AndKe** [comment]
Yes, I did discover that current stable 6.8.0 does look good.
There are a number of ways to crash it (AP) at will.
Especially when playing with logs, opening/converting - would you fix If I report them?

**Comment by meee1** [comment]
please do report them, but also make sure you running the beta version
https://ci.appveyor.com/api/buildjobs/v44d3jo4vf76jnof/artifacts/MissionPlannerBeta.zip
