### ISSUE TITLE
GeoFenceDist no longer available on Quick Tab "Display This" list of Items

### ISSUE THREAD

**Issue by Warren-Eather** [ArduPilot/MissionPlanner#2365]
#### Issue details
GeoFenceDist no longer available on Quick Tab after upgrade.
We have been using it for Fence Proximity Warnings and in Scripted Soft Fence Avoidance for the OBC

#### Version
MP 1.3.70 Build 1.3.7277.34800
![GeoFenceDistance](https://user-images.githubusercontent.com/54134183/78883205-84d10880-7a9c-11ea-8c9a-17ae824af452.jpg)

#### Platform
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

**Comment by SSUAV** [comment]
Hi,
Any update on this?
Regards 
Warren

**Comment by meee1** [comment]
i will look at adding this back, it was removed because with the new geofence support it got alot more difficult. but dont see any roadblocks bringing it back, other than time

**Comment by meee1** [comment]
please try the latest beta. should be back and support multiple inclusion/exclusion zones

**Comment by Warren-Eather** [comment]
Thanks for that Michael.
It appears that the Geofence Return point is also being included in the distance calculation. [cid:E25854C1-91EE-421F-8F3B-3E6D0DC9AA84-L0-001]
Warren

Sent from my iPhone

On 28 May 2020, at 9:03 pm, Michael Oborne <notifications@github.com> wrote:

﻿

please try the latest beta. should be back and support multiple inclusion/exclusion zones

**Comment by meee1** [comment]
ok new beta again, ignores return point

**Comment by meee1** [comment]
ok ive checked it and im happy
![image](https://user-images.githubusercontent.com/511568/83157851-a4002400-a136-11ea-9f76-341e8026a374.png)

**Comment by Warren-Eather** [comment]
Hi Michael,

It appears that the GeoFence Return is still being included in the fence distance calculations

Regards

Warren

________________________________

**Comment by meee1** [comment]
do you have the latest beta? all my testing says its fixed

**Comment by Warren-Eather** [comment]
1.3.71.1 build 1.3.7454.12815

________________________________

**Comment by meee1** [comment]
i think i need to see your fence. as its good from what i can see
also what firmware and version.

**Comment by Warren-Eather** [comment]
I'm currently just testing on the MP simulator.


________________________________

**Comment by meee1** [comment]
what firmware? copter/rover/plane.

**Comment by Warren-Eather** [comment]
Oh soz, Plane

________________________________

**Comment by SSUAV** [comment]
Thanks Michael 
Looking good!
Regards 
Warren
SSUAV

**Comment by meee1** [comment]
yeah, fixed the other day, forgot to mention it. was the fact that plane still uses the old legacy fence protocol. the others use the new mission item one. but both should be good now
