### ISSUE TITLE
MP cannot connect to an autopilot with signing active

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/MissionPlanner#2386]
#### Platform
[x  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub
While documenting MAVlink2 signing for the wiki, I discovered that MP cannot connect to an autopilot with active signing...QGC does, but of course only gets downlink telem....I believe MP should be able to connect to any autopilot with signing active, but only send commands if the appropriate key is enabled by selecting its USE button after connecting...
tried selecting the correct USE button prior to connecting, no luck...

**Comment by meee1** [comment]
i believe this if fixed in current beta
