### ISSUE TITLE
LogBrowse: decimal scalar fails on separator other than „.“

### ISSUE THREAD

**Issue by vierfuffzig** [ArduPilot/MissionPlanner#2387]
Issue details
setting a decimal scalar in LogBrowse requires system (windows) separator set to „.“ instead of accepting system regional default. LogBrowse ignores the separator otherwise.

Version
1.3.7426.10530

Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x] Plane
[  ] Rover
[  ] Sub

**Comment by meee1** [comment]
can you clarify this. i  kinda of understand, but want to make sure im not asuming things

whats your system set to? comma's or periods?
what are you entering?
anything else thats relevant

**Comment by vierfuffzig** [comment]
@meee1 thanks for getting back on this!
my system's regional setting is comma per default. with this system setting, LogBrowse decimal scalar fails on commata and ignores periods, so that entering `*i,d` has no effect at all while `*i.d` is treated as `*id`.
only with the system set to period this works as i would expect (correct with periods, fail on commata).
...hope i managed to not add confusion ;)

**Comment by vierfuffzig** [comment]
@meee1 fixed, thanks a lot!
