### ISSUE TITLE
ConfigurationView:  support params over ftp

### ISSUE THREAD

**Issue by tatsuy** [ArduPilot/MissionPlanner#2395]
I'd like to download params over ftp when pushing "Refresh Params" button on the following screen:
 Standard Params
 Advanced Params
 Full Parameter List
 Full Parameter Tree

**Comment by meee1** [comment]
the plan is to do this. but wanted to make sure it pass's a few use's before i push it far and wide

**Comment by tatsuy** [comment]
@meee1 OK, thank you!

**Comment by tatsuy** [comment]
now supported, thanks!
