### ISSUE TITLE
Write Waypoints - Immediate Crash

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/MissionPlanner#2407]
#### Issue details
If I plan a mission in MP and click "Write", it crashes immediately. 

#### Version
MP 1.3.71 build 1.3.7451.16917 APM:Copter V3.5.5 (27229c83)

#### Platform
[  ] All
[  ] AntennaTracker
[x  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Hex

#### Hardware type
Pixhawk 1

#### Steps to reproduce

1. Start MP
1. Plug in autopilot
1. Connect (connection successful)
1. Click "Plan" tab
1. Click "Read" to get the stored mission
1. Click "Write" to write the mission

#### Logs
![image](https://user-images.githubusercontent.com/25047695/83975169-9e7da900-a8af-11ea-81fd-4751d7f974c3.png)
I have 5 GPS satellites - I see the error is in getHomePosition if that matters

**Comment by meee1** [comment]
Any reason you are still running 3.5.5

**Comment by Ryanf55** [comment]
It was a known stable version for the functionality I was using and I haven't needed any of the new features. However, now I need AUTO missions, and this prevents me from creating them. I will upgrade APM FW and report back.

**Comment by meee1** [comment]
i released a new version of MP yesterday,could you try that?

**Comment by Ryanf55** [comment]
It worked. Forgot to update the ticket. Closing now.
