### ISSUE TITLE
MAVFTP usability issues when combined with MP

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2413]
I am unsure if these are Mission Planner issues or flight code so I'm documenting these issue but here and in the AP flight code issues list: https://github.com/ArduPilot/ardupilot/issues/14643

All of these issues can be reproduced by doing the following:

- Open Mission Planner
- Open the Simulation page
- Ensure the "wipe" checkbox is checked
- Press the Copter icon at the bottom
- Open Config, MAVFtp

When trying to upload a Lua script to a copter in MP's simulator I've run into these problems:

- Click, "@ROMFS", then click on the unnamed (top directory?), 5 second delay before the directory listing is displayed.  5sec is not very long but it is very noticeably longer than if I click on one of the sub directories (i.e. logs) and then switch back to the top directory
![image](https://user-images.githubusercontent.com/1498098/85190872-8ec28380-b2f7-11ea-898b-e4a275274044.png)
- Attempting to create a directory with the same name as an existing directory causes MP to lock-up for 30 seconds.  The directory is not created and no error message is displayed
- Attempting to delete an empty directory causes MP to lock-up for 30 seconds.  A "Failed to delete file" message is displayed and the directory is not deleted
- Attempting to create the scripts directory under @ROMFS causes MP to lock-up for 30 seconds, the directory is not created and no error message is displayed

**Comment by Hwurzburg** [comment]
another issue being found repeatedly is that on 56K Telem links the " looking for Mavftp param" can take 30seconds or more before reverting to normal param fetching...it can be circumvented by closing that dialog....but I dont think it should be necessary...

**Comment by meee1** [comment]
@Hwurzburg  realy need to test this against the current beta, ive addressed all the already

**Comment by rmackay9** [comment]
I've tested this and all the issues seem resolved thanks!

As a side note I was able to create a @ROMFS directory.  It didn't seem to do any harm though.

**Comment by Hwurzburg** [comment]
thanks...will pass along to those having issues
