### ISSUE TITLE
Shortcut to read or write waypoints

### ISSUE THREAD

**Issue by expntly** [ArduPilot/MissionPlanner#2424]
#### Issue details
I couldn't find a shortcut (hotkey) to read or write waypoints.  MP is really great but so many features are hidden, sorry if I missed this one but I've looked everywhere.  Could this please be added?  Thanks

#### Version
1.3.72

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

**Comment by meee1** [comment]
Currently there is non to read/write wps.
there are to open a wp file, and save a wp file
control-z - undo
control-o - open wp file
control-s - save wp file

**Comment by meee1** [comment]
https://github.com/ArduPilot/MissionPlanner/blob/3bca203ad7ee4ee0cd409431f42a8bcc467b1ffa/GCSViews/FlightPlanner.cs#L331

**Comment by expntly** [comment]
Is this something one can add via a py script or plugin?

**Comment by expntly** [comment]
I did some more digging and found that https://github.com/ArduPilot/MissionPlanner/blob/master/plugins/Shortcuts/Plugin.cs, so I guess one can write their own C# plugin to add shortcuts.

I looked into whether I could do this with python but I can't find that `MainV2` or `MainV2.instance` object exposed: https://github.com/ArduPilot/MissionPlanner/blob/9d8cef76f1b14fd2627afd2a01ae1081f134ad62/Script.cs#L45

Is there a way to add a `ProcessCmdKeyCallback` in a python script?

**Comment by expntly** [comment]
ping @meee1 

If that's not possible in Python this issue can be closed.

**Comment by meee1** [comment]
technically yes you can, i  have not tested it however

**Comment by meee1** [comment]
what key combo did you have in mine? i can add it to beta MP

**Comment by expntly** [comment]
@meee1 Any key combo will do (ctrl+shift+w?), thanks!

**Comment by meee1** [comment]
added

**Comment by sinegole** [comment]
Hi Michael, The ctrl+shift+W is shortcut for "Write fast", could you please add shortcut for standard "Write".
