### ISSUE TITLE
how can i display my new flight mode on mission planner ?

### ISSUE THREAD

**Issue by theonly-unicorn** [ArduPilot/MissionPlanner#2428]
how can i display my new flight mode on mission planner ?
I added a new flight mode, which can run normally in the sitl simulator, but my flight mode is not displayed on the mission planner connected to pixhawk.

my  mission planner version :  Mission Planner 1.3.70
my platform: copter
ardupilot code version : copter4.0.1
hardware type:pixhawk

**Comment by meee1** [comment]
please check here
https://discuss.ardupilot.org/t/new-flight-mode-not-shown-in-mission-planner/42193/7
