### ISSUE TITLE
mission planner 1.3.70how to use the terminal

### ISSUE THREAD

**Issue by theonly-unicorn** [ArduPilot/MissionPlanner#2429]
My device is pixhawk4, and the ardupilort version is copter 4.0.1. After opening the mission planner, I successfully connect to the serial port (COM4) of pixhawk. However, when I select APM connection at the terminal of mission planner 1.3.70, I will prompt rebooting COM4 at 115200, can't open serial port. When Px4 / pixhawk connection is selected, the serial port is opened successfully, but the terminal interface starts to print out garbled codes, and the command line is not displayed normally

**Comment by meee1** [comment]
terminal no longer is used for ardu*. only in older pre 3.0 release does terminal do anything anymore
