### ISSUE TITLE
Drivers doesn't work on windows 10 build 2004

### ISSUE THREAD

**Issue by pmarkiewicz** [ArduPilot/MissionPlanner#2434]
Just upgraded Windows 10 to build 2004 and I can't connect pixhawk 1 to computer, usb driver is unrecognized.
I reinstalled latest MP 1.3.72 without any results.
Before upgrade everything woked ok.

**Comment by pmarkiewicz** [comment]
hardware error, sorry

**Comment by cnpcshangbo** [comment]
@pmarkiewicz How did you solve this issue? Did you replace hardware? Thanks.
