### ISSUE TITLE
Cannot complete the device driver installation wizard

### ISSUE THREAD

**Issue by cnpcshangbo** [ArduPilot/MissionPlanner#2450]
When I install Mission Planner, I got a message said: "Cannot complete the device driver installation wizard".
![image](https://user-images.githubusercontent.com/4831029/91231920-c385f900-e6f3-11ea-8f5d-fc06c96e01ee.png)
After the installation, I tried to connect a serial port, however, it is recognized as Microsoft serial ballpoint.
![image](https://user-images.githubusercontent.com/4831029/91232069-01831d00-e6f4-11ea-9fb1-bce8948db371.png)
I have tried to change register as mentioned in https://stackoverflow.com/questions/9226082/device-misdetected-as-serial-mouse
However, I am still refused to access the serial port. I got a message: Access to the port 'COM3' is denied.
![image](https://user-images.githubusercontent.com/4831029/91232208-44dd8b80-e6f4-11ea-85d5-24478b1cc31e.png)
Hope to get some suggestions. Thanks.

**Comment by meee1** [comment]
I would reboot the VM and try again. Most likely the miss detection is causing it

**Comment by cnpcshangbo** [comment]
@meee1 Thank you. Rebooting the computer solved this issue.
