### ISSUE TITLE
gstreamer did not work

### ISSUE THREAD

**Issue by cyhly** [ArduPilot/MissionPlanner#2460]
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
please provide more information.

**Comment by cyhly** [comment]
Sorry，i want to know how to use gstreamer with missionplanner?

**Comment by meee1** [comment]
best to ask this question on the ardupilot forum in the mission planner section.

**Comment by cyhly** [comment]
i am sorry，i ask this question on the ardupilot forum in the mission planner section.but no reply.
I downloaded the GStreamer component on C disk.
but when i use gstreamer with Right-click hud.
there was no video shown.
I really need this right now.
what should i do?

**Comment by meee1** [comment]
no idea where your post is
should be here
https://discuss.ardupilot.org/c/ground-control-software/mission-planner/
