### ISSUE TITLE
MAVFtp: crc error

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/MissionPlanner#2464]
When downloading files via FTP, both to a real vehicle and SILT, I get a CRC error (MP 1.3.73 build 1.3.558.11943). Also reported  in https://github.com/ArduPilot/MissionPlanner/issues/2422#issuecomment-652200697.

![image](https://user-images.githubusercontent.com/33176108/92999757-6673ab00-f51b-11ea-9064-d442618aed73.png)

MAVProxy will download the same file with `ftp get` without error. The file is actually received fine, it just ends up with some random characters appended. Sending files from MP to AP works as expected. The same error is seen with both `Download` and `Download burst`.

Interestingly param download via MAVFtp works fine. I came across this while trying to track down a issue with the scripting REPL,  it works with SILT but not on real hardware, suspect that is a AP bug rather than a MP one tho.

**Comment by meee1** [comment]
do you have the tlog for this?

**Comment by IamPete1** [comment]
I have put it on [my drive](https://drive.google.com/drive/folders/1jpTm6blDFDA27H3uvAGsNsMgGvBUeLm5?usp=sharing
). 

There is tlog, rlog and the file as it was receved with the extra junk. The orignal file is [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/simple_loop.lua).

Thanks

**Comment by meee1** [comment]
is the lua from a download?
i see this
![image](https://user-images.githubusercontent.com/511568/93018246-e58edf00-f600-11ea-84a8-a6bec2377216.png)

**Comment by IamPete1** [comment]
Yeah, that is the stuff that gets appended.

**Comment by meee1** [comment]
ok, ill start looking there.

**Comment by IamPete1** [comment]
Notepad++ does a better job at displaying them than VS Code, so hadn't considered it before, but I checked, you get more `NULL`s for bigger files, so its not just a constant number at the end. Doesn't seem directly related to the file size tho as far as I can tell.

I also forgot to mention that this used to work fine, I don't recall when exactly tho.

**Comment by meee1** [comment]
i think i now why, its to do with the reported file size, and virtual files.... i will need to look harder.

i can replicate it in sitl, so makes it easier to find

**Comment by meee1** [comment]
new beta in 10 mins

**Comment by IamPete1** [comment]
Can confirm is now fixed, thank you!
