### ISSUE TITLE
Add THERMAL mode for ArduPlane.

### ISSUE THREAD

**Issue by samuelctabor** [ArduPilot/MissionPlanner#2476]
THERMAL mode is now merged into master as ArduPlane mode #24.

**Comment by meee1** [comment]
so long as the param doc was updated, just goto Setup > Advanced > and click Param Gen, this will pull the latest param doc data so MP will display it

**Comment by samuelctabor** [comment]
Hmm, not sure it was actually. Which parameter  - FLTMODEX?

**Comment by meee1** [comment]
correct
