### ISSUE TITLE
Log Browser does not clear line if checkbox is unchecked while a pop-up description is visible

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2489]
Pull up this log with Beta MP's log viewer: https://www.dropbox.com/s/k2z0iz79pdksffj/optflow-line-weirdness.bin?dl=0

To recreate the problem:

- On the right side expand the "OF" field view and check "flowX", "flowY", "bodyX" and "bodyY"
- Quickly uncheck the same fields starting from the bottom and working up.  Make sure to try to uncheck one of the boxes while the pop-up description from the field below it is still displayed

Below if a view of the result.  We can see from the field description on the top right that it's OF.flowX and OF.flowY that are being graphed but we can also see on the right that all checkboxes are unchecked
![image](https://user-images.githubusercontent.com/1498098/95557009-2981d200-0a4f-11eb-940a-23179a28575e.png)

**Comment by meee1** [comment]
ive change the popup to fixed field now. so no longer and issue
