### ISSUE TITLE
[feature request] message button

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/MissionPlanner#2522]
It is possible to send a message to AP that it then records in its log, this uses the GSC send test message. The AP receiving implantation is here:
https://github.com/ardupilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L2833

In MAVProxy this is possible with the `msg` module for example:
```
module load msg 
msg test of message functionality
```

![image](https://user-images.githubusercontent.com/33176108/102725094-15d6cf80-430c-11eb-8b42-27deaf1657e7.png)

The use case is if you notice something in the flight, or want to note a particular time you can send the note and it will be induced in the AP dataflash log.

**Comment by magicrub** [comment]
Great idea!

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/MissionPlanner/pull/2841
