### ISSUE TITLE
ARM Linux build?

### ISSUE THREAD

**Issue by Botspot** [ArduPilot/MissionPlanner#2526]
It would be awesome if I could run MissionPlanner on a Raspberry Pi desktop computer.

Is this possible?

**Comment by meee1** [comment]
this is already being done. check the forum
https://discuss.ardupilot.org/t/how-to-guide-mission-planner-on-raspberry-pi/60889

**Comment by Botspot** [comment]
Thanks!

**Comment by Botspot** [comment]
Okay it worked fine after I disabled the OpenGL driver.  
I didn't want want to disable the OpenGL driver system-wide, so I found an alternative:
```
LIBGL_ALWAYS_SOFTWARE=1 mono /home/pi/MissionPlanner-latest/MissionPlanner.exe
```
Now it works great, and all my other software still has access to the OpenGL driver! :)

@meee1 Could you forward this information to that discuss.ardupilot.org thread please, and maybe get the pdf instructions updated?
