### ISSUE TITLE
Cant find code to receive message by  another System id

### ISSUE THREAD

**Issue by lycn2020** [ArduPilot/MissionPlanner#2533]
#### Issue details
On the source code of Mission Planner I want to receive messages from mavlinke by system ID like 244 
What is the code in C# to receive message by System ID
Please Help me

#### Version
1.3.74
#### Platform
source code of Mission Planner

#### Airframe type

no
#### Hardware type

no
#### Logs
no
![Untitled](https://user-images.githubusercontent.com/73897450/103753012-89225600-501b-11eb-8815-8fff80d21fea.jpg)

**Comment by meee1** [comment]
if its a valid mavlink packet, it will show up already

**Comment by lycn2020** [comment]
i sent  a packet from arduino with sys id 244 . and i wanna show it on mission planner

**Comment by meee1** [comment]
if mission planner not displaying it, then the packet is invalid

**Comment by lycn2020** [comment]
![Untitled](https://user-images.githubusercontent.com/73897450/103757780-4912a180-5022-11eb-92d0-f61649819df0.jpg)
 it displayed in mission planner (mavlink inspector).but how to use it in another form.
