### ISSUE TITLE
FFT button should be named "Open Log"

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2541]
The FFT page has a button labelled, "IMU Batch Sample" but it should probably be renamed to "Open Log".

![image](https://user-images.githubusercontent.com/1498098/104409654-17fa1a00-55aa-11eb-88ae-356a86f9d788.png)

**Comment by meee1** [comment]
the reason i labeled it like that was the cross tie to this
https://ardupilot.org/copter/docs/common-imu-batchsampling.html

**Comment by rmackay9** [comment]
@meee1,  OK thanks.
