### ISSUE TITLE
angular velocity

### ISSUE THREAD

**Issue by cyhly** [ArduPilot/MissionPlanner#2561]
which param is the angular velocity?

**Comment by rmackay9** [comment]
This question should probably go into the forums: https://discuss.ardupilot.org/c/arducopter/copter-40/155

I suspect you're looking to set a multicopter's maximum angular velocity which is set by the ATC_ACCEL_P/R_MAX:
https://ardupilot.org/copter/docs/tuning-process-instructions.html#pid-controller-initial-setup

Or maybe you're looking for the roll and pitch rate controller gains?  these are ATC_RAT_RLL_P/I/D and ATC_RAT_PIT_P/I/D
