### ISSUE TITLE
Widen dropdowns so that full function names are visible

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/MissionPlanner#2619]
Please fix this:
![drop2](https://user-images.githubusercontent.com/6076534/119290743-c413d780-bc12-11eb-9eda-fe4b3bfb4b54.PNG)
![drop1](https://user-images.githubusercontent.com/6076534/119290753-c83ff500-bc12-11eb-98a2-16142345c82e.PNG)

thanks

**Comment by rmackay9** [comment]
As a side note, it would be nice if we could get the parameter lists to always be able to display 16 characters
![image](https://user-images.githubusercontent.com/1498098/119292694-d716be00-bc8b-11eb-84a0-099efb0bd419.png)

**Comment by Hwurzburg** [comment]
done...thanks!
