### ISSUE TITLE
fatal: remote error: upload-pack: not our ref

### ISSUE THREAD

**Issue by gitfishup** [ArduPilot/MissionPlanner#2667]
First，  git pull upstream master,
Then   git Submodule update --init --recursive --force  ， error occurs： 

fatal: remote error: upload-pack: not our ref 478c5bb4b40abd1ceabbe3d1f14ea40ef505f7c4
fatal: remote error: upload-pack: not our ref a17eb357235e4f6d409cdd664daceda2fcac1e7b

git log 

![image](https://user-images.githubusercontent.com/69180601/128282353-8dc367b3-7ba1-4d33-a2e7-e8c14ed20176.png)

git Submodule update --init --recursive --force  ， error occurs： 
![image](https://user-images.githubusercontent.com/69180601/128282274-57792203-5173-466d-902a-b792f72e4b25.png)

Can anyone help me ?

**Comment by meee1** [comment]
Don't do recursive in the submodule

**Comment by gitfishup** [comment]
> Don't do recursive in the submodule

Oh，Thanks a lot.
