### ISSUE TITLE
NETSDK1045 build issue

### ISSUE THREAD

**Issue by MLEI-AERO** [ArduPilot/MissionPlanner#2681]
I have an build error. Installing .NET 6.0.0-preview for my VS2019 16.11.0 doesn't solve it. Do I have to set a path or anything in VS?

![grafik](https://user-images.githubusercontent.com/61831930/130616897-34c1c3fe-59dc-41cb-b829-465e32502380.png)

_Originally posted by @MLEI-AERO in https://github.com/ArduPilot/MissionPlanner/issues/2668#issuecomment-904601306_

**Comment by meee1** [comment]
Compile just missing planner project. You don't need wasm for mission planner to run

**Comment by meee1** [comment]
The answer to the actual issue here though is install VS 2022 preview

**Comment by MLEI-AERO** [comment]
Sorry for german VS code. However, when you say just compile mission planner you mean I should ignore errors and just press run (green arrow). As I understand only MissionPlanner is selected?

![grafik](https://user-images.githubusercontent.com/61831930/130621117-4f36e72e-942e-45d3-a9c6-8f6be1db383f.png)
