### ISSUE TITLE
apk distribution

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#2686]
For users using android transmitters like the HEQ H12 having MissionPlanner is a great step up. For now I've put a copy of the apk of one version here:
http://uav.tridgell.net/tmp/Mission%20Planner_v57819.apk
but it would be a lot better if you could include it in your daily updates on https://firmware.ardupilot.org/Tools/MissionPlanner/ 
Is that possible?

**Comment by meee1** [comment]
ive just added this
https://github.com/ArduPilot/MissionPlanner/releases/tag/latest

**Comment by tridge** [comment]
thanks!
