### ISSUE TITLE
button to restart lua scripts

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#2709]
when doing lua devel it is a pain to restart SITL all the time. We need this command:
https://github.com/ArduPilot/MAVProxy/blob/master/MAVProxy/modules/mavproxy_misc.py#L342
just need a "Lua Restart" button in control-F I think

**Comment by patrickpoirier51** [comment]
@meee1   yes please, this feature would be so useful when tuning script on real scenario as well.
My suggestion is to add a RESTART option when you select file on the SCRIPT directory so you can select a specific script to restart.

**Comment by meee1** [comment]
already exists in the actions tab.  i might need to widen the display though

**Comment by patrickpoirier51** [comment]
@meee1  ok just found it  :-)
![image](https://user-images.githubusercontent.com/12484190/152789165-fd83daf4-4365-4dae-92c1-96c1b1a444be.png)

**Comment by meee1** [comment]
you will need to do an update or beta im releasing now, i double checked, and it was broken

**Comment by patrickpoirier51** [comment]
Yes, I will try later, Thanks
