### ISSUE TITLE
Attempting to launch helicopter stable version of simulator launches latest version instead

### ISSUE THREAD

**Issue by bnsgeyer** [ArduPilot/MissionPlanner#2733]
Issue details
when launching the SITL simulator for helicopters from the simulation tab, selecting the stable version launches a simulation with the latest version instead.

Version
Latest beta of 1.3.75

Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] TradHeli
[  ] Plane
[  ] Rover
[  ] Sub

Airframe type
Helicopter

**Comment by rmackay9** [comment]
I've noticed this as well recently.  I think Rover is also coming up with the wrong version.

**Comment by bnsgeyer** [comment]
@EosBandi Thank You!!!
