### ISSUE TITLE
Feature request: Decode UTF8 messages

### ISSUE THREAD

**Issue by Jaaaky** [ArduPilot/MissionPlanner#2743]
Using gcs().send_text() function on ardupilot passing UTF8 - non ascii - text to it, mavproxy can decode and display the messages correctly.
However MissionPlanner shows '??????? ????????? ???????' instead.

Please allow showing such text correctly.

**Comment by meee1** [comment]
Do you have a sample tlog by chance?

**Comment by EosBandi** [comment]
It seems it is fixed by https://github.com/ArduPilot/MissionPlanner/commit/f91ea21bc4454cafdbf7cf188b410fd1eb067e84 which is in 1.76 release by now.

**Comment by Jaaaky** [comment]
Yes, it's fixed.. Thanks
