### ISSUE TITLE
Plan: add MAV_CMD_DO_SPRAYER (216) to list of available commands for Rovers/Boats

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2763]
Rover-4.1 (and maybe earlier) support the SPRAYER command (216)

Only param1 is consumed.  If it is 1 then the sprayer is turned on.  If it is zero the sprayer is turned off so maybe the column title for Param1 should be "off(0)/on(1)".

For reference here is the link to the mavlink spec https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/ardupilotmega.xml#L41

**Comment by EosBandi** [comment]
There is this PR https://github.com/ArduPilot/MissionPlanner/pull/2761 which makes it possible for users to add any Mavlink commands to the dropdown list and store the added commands in the config.xml.

**Comment by framosnt** [comment]
I was talk about this features feel days ago. I need this to use by Sprayer Agricultural Copter. Can this functionality make to Copters too ?

**Comment by rmackay9** [comment]
Fixed long ago, thanks!
