### ISSUE TITLE
.BIN to .LOG

### ISSUE THREAD

**Issue by Shivankit99** [ArduPilot/MissionPlanner#2770]
#### Issue details
Need help in finding a script to convert .bin to .log file.

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
mission planner supports this in the bin file tab
![image](https://user-images.githubusercontent.com/511568/150672756-8d409ec7-9cdc-46b3-812b-c1f6d2dc9c58.png)
