### ISSUE TITLE
Add Baro device id info to HWID page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2782]
4.1 (and higher) includes BARO1/2/3_DEVID parameter so it would be nice to get these added to the HWID page as well if possible.
![image](https://user-images.githubusercontent.com/1498098/151357697-8131b76f-9c60-49a2-9674-832881fab865.png)

I noticed this as part of handling this support request about a broken baro. https://discuss.ardupilot.org/t/cubeblack-can-not-detect-its-baro/79045/18

This is the PR that added the device ids I think. https://github.com/ArduPilot/ardupilot/pull/14847

**Comment by meee1** [comment]
this should come for free, as MP already has the baro code

**Comment by meee1** [comment]
sorry i was wrong, the param names between that commit and now hav changed. updated as needed

**Comment by rmackay9** [comment]
great, thanks!

**Comment by rmackay9** [comment]
Baro devices appear in the HWID page now.  closing, txs!
