### ISSUE TITLE
alt display incorrect units

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#2790]
![image](https://user-images.githubusercontent.com/831867/152670849-cfce9fe8-4d7a-4b65-ac52-210dfa40cfc0.png)
on 1.3.76 with alt set to feet, the "altasl" in the quick display displays with (m) units, but actually displays in feet
For the above test the actual altitude was 50m

**Comment by meee1** [comment]
this should be resolve, it was using distance units not alt units.
