### ISSUE TITLE
EKF and Vibe graphs unable to be displayed

### ISSUE THREAD

**Issue by Periwink1e** [ArduPilot/MissionPlanner#2794]
#### Issue details
When I open mission planner all functions seem to work fine except when trying to use the EKF and VIBE charts. When I click on these buttons nothing comes up. A window in the background does seem to get generated what is properly named but it is not something that does anything when selected. I did not have this problem when I first started using mission planner but for reasons I'm not sure it has arisen. I have tried getting a fresh install but this has not resolved the issue.
Thanks for any feedback, Logan

#### Version
1.3.76 build 1.3.8029.15962

#### Logs
Not sure if this is standard but I consistently (once every couple seconds) get 
"HUD 1 hz drawtime 3 gl True" with different draw time numbers.

**Comment by rmackay9** [comment]
This could be on the autopilot side though.  perhaps ArduPilot's EKF is not getting a good position estimate?

**Comment by Periwink1e** [comment]
Well I tried again to reinstall and now I am able to view the graphs. Not sure what changed because the build number is the same.
