### ISSUE TITLE
Camera Gimbal: remove Control Angles

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2814]
As mentioned on [the flight code wiki page](https://ardupilot.org/copter/docs/common-camera-gimbal.html) there's no point in updating the "Control Angles" section of the Camera Gimbal page so we should just remove this section from the page.
![image](https://user-images.githubusercontent.com/1498098/158160595-418f3005-3daf-4868-9032-5562887620fe.png)

**Comment by rmackay9** [comment]
@rrr6399,

I don't think that the "Control Angles" fields will actually allow moving the gimbal to a specific angle.  I've had a peek back at the ArduPilot code history and it looks like we removed these parameters 7 years ago (!) so there should be no danger in removing this section.

**Comment by jagrandle** [comment]
I haven't had the "pleasure" of trying to set up a gimbal yet, but I have one waiting my attention. Being able to test it to nominated angles sounds like a very, very useful thing in the set up and testing phase.
Rather than remove this option, if the parameters were removed 7 years ago, what about re-instating the parameters so that it does work ?
Thanks

**Comment by rmackay9** [comment]
@jagrandle,

I agree that it would be convenient to have a place on this page where users can manually control the gimbal.  That shouldn't be done by setting parameters though, instead the [DO_MOUNT_CONTROL mavlink message](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1062) could be used.

For now though, I think expanding the scope will just mean that the suggested change (to remove the fields) won't get done and we will be left with unnecessary fields in the user interface that add confusion.

**Comment by jagrandle** [comment]
Agreed, they are not parameters to be set and forget like the others on this page. More of a testing page sort of thing, like a Motor Test or similar.

**Comment by rrr6399** [comment]
OK. I just assumed it was sending do_mount_control messages for testing purposes.  Couldn't the current controls just be wired to send do_mount_control instead of sending the old parameters? It might be more convenient to have this simple test interface as you're configuring the gimbal.

**Comment by rmackay9** [comment]
this has been done now so closing.
