### ISSUE TITLE
LogBrowser: instance is not always in numerical order

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2817]
![image](https://user-images.githubusercontent.com/1498098/158540141-58b95d7d-7f63-4d85-b573-ef46d6d511b7.png)

Sometimes it seesm the Log Browser displays the instances in non-numerical order as shown above.  I suspect this is because it currently uses the order that the first messages arrive in but that's just a guess.  Txs!

**Comment by cuhome** [comment]
@meee1 This is the flight [log](https://drive.google.com/file/d/17t3CtyhEQMWuc6PyMBVWsDEV_y7f1HrP/view?usp=sharing)

**Comment by rmackay9** [comment]
This has been fixed long ago I think.
