### ISSUE TITLE
LogBrowser can't process because instance field too large

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2830]
We have a report from [Rover-4.2 beta testing here](https://discuss.ardupilot.org/t/rover-4-2-0-beta3-released-for-beta-testing/83623/18) that MP's log browser can't parse the user's log.  I've reproduced the issue and copy-pasted the error message below.

![image](https://user-images.githubusercontent.com/1498098/162086945-e7cfe23b-c5f9-4189-8c68-74029904d39a.png)

After this error occurs MP gets stuck and needs to be forcibly restarted.

**Comment by meee1** [comment]
can you try the latest beta.

**Comment by rmackay9** [comment]
@meee1 thank you very much!!
