### ISSUE TITLE
Fence Mission Items Not Supported Please Use Legacy Geofence

### ISSUE THREAD

**Issue by flybrianfly** [ArduPilot/MissionPlanner#2866]
#### Issue details
I'm trying to upload a polygon exclusion geofence to my [company's flight stack](https://github.com/bolderflight/spaaro). We are reporting the following capabilities:
   * MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT
   * MAV_PROTOCOL_CAPABILITY_MISSION_INT
   * MAV_PROTOCOL_CAPABILITY_MAVLINK2
   * MAV_PROTOCOL_CAPABILITY_MISSION_FENCE
   * MAV_PROTOCOL_CAPABILITY_MISSION_RALLY

And our autopilot is reported as MAV_AUTOPILOT_GENERIC.

I'm able to upload fences with QGC. In Mission Planner, when I write the fence, I get this exception:
Fence Mission Items Not Supported Please Use Legacy Geofence
![Capture](https://user-images.githubusercontent.com/7801107/169897253-b34bf36b-12fb-48d7-a7b2-83f7e30b0c4b.PNG)

#### Version
1.3.77 and 1.3.77 with Beta updates.

**Comment by meee1** [comment]
what you are sending looks ok, can you provide a tlog?

**Comment by flybrianfly** [comment]
@meee1, attached is a zip of the tlog.
[2022-05-23 19-22-12.zip](https://github.com/ArduPilot/MissionPlanner/files/8758900/2022-05-23.19-22-12.zip)

The mavlink_autopilot_version_t message is sent in response to a mav_cmd_request_message_t being received.

**Comment by flybrianfly** [comment]
Shoot, I think that's the disconnect, I'm using the command microservice for the GCS to send the MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES, which I don't see the autopilot getting, thanks for the hint.

**Comment by meee1** [comment]
MP uses mavlink_autopilot_version_request_t

**Comment by flybrianfly** [comment]
Thanks! That fixes it.
