### ISSUE TITLE
Mission Planner Android don't Speak Portuguese or other diff english

### ISSUE THREAD

**Issue by framosnt** [ArduPilot/MissionPlanner#2880]
after change language in list box of "planner" configuration, enable "Speak" check box and change text of each item to speak (check box) the Mission Planner don't speak in correct voice, using english or chinese speaker to read "portuguese" text.

observation: if differents types of voice alert using differents language, english, chinese and portuguese. I tried config my android setup to unique voice system, but isn't have effect !

version 1.3.77 didn't working: https://youtube.com/shorts/Qenld563YSw

version 1.3.74 did working correctly: https://youtu.be/TmGZf60uvWE

#### Version
1.3.76 until 1.3.77

#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by meee1** [comment]
sounds good, ill close
