### ISSUE TITLE
Incorrect voltage readout on HUD

### ISSUE THREAD

**Issue by CallanDaniel** [ArduPilot/MissionPlanner#2887]
#### Issue details
_There is a possible bug in the displayed voltage on the HUD - a 1 is appended to the front of the actual reading:_
![image](https://user-images.githubusercontent.com/43185766/174587612-d7ab39c7-9617-4faf-b8ca-579ab6da9ff6.png)

#### Version
_1.3.77.1 build 1.3.8206.14892_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_Quadplane_

#### Hardware type
_Tested on Cube Orange, Pixhawk 4 and SITL_

**Comment by meee1** [comment]
can you provide a tlog?

**Comment by meee1** [comment]
actualy, not needed, i tink i know why

**Comment by CallanDaniel** [comment]
Cool, thanks. Shout if you need a tlog @meee1

**Comment by CallanDaniel** [comment]
Thanks!

**Comment by CallanDaniel** [comment]
Built locally and it worked - how long until this build will be available via the "Beta Update" button? Sorry, I know this is a silly question, but this version has a fix that allows us to use Silvus radios over UDP - and I'm not quite at the stage of compiling to an installation file I can send to clients... @mee
