### ISSUE TITLE
MAVFTP failing when ADSB_ENABLE = 0

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2915]
We've got a few reports of MAVFTP failing to downloading of parameters and/or upload/download lua scripts in this issue: https://github.com/ArduPilot/ardupilot/issues/21246

**Comment by meee1** [comment]
might need a tlog or similar to see comms

**Comment by rmackay9** [comment]
I haven't seen this recently so closing.
