### ISSUE TITLE
Support Holybro 6X upload via MP

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2934]
It seems that the Holybro 6X boards aren't recognised by MP as an autopilot that it can upload to.

Relevant discussions are [here](https://discuss.ardupilot.org/t/copter-4-2-3-rc1-rc2-available-for-beta-testing/89506/9) and [here](https://discuss.ardupilot.org/t/copter-4-2-3-released/90230/12).

**Comment by tridge** [comment]
The issue only happens on new boards that are running the px4 firmware that is shipped on the board. MissionPlanner never gets to the step of asking the users to unplug and press OK, it just fails with:
![image](https://user-images.githubusercontent.com/831867/187560422-244cf1a9-7615-41e7-bbb9-94b177a06287.png)
Once ArduPilot is installed on the board then everything works fine. Also note that load custom firmware does work when it is running px4 firmware.
this is in the MissionPlanner log file:
```
  "name": "COM59",
  "description": "USB Serial Device",
  "board": "PX4 FMU v6X.x",
  "hardwareid": "USB\\VID_3185&PID_0035&REV_0101"
} (D:\a\MissionPlanner\MissionPlanner\ExtLibs\ArduPilot\APFirmware.cs:134) [Base Thread]
2022-08-31 09:20:59,700  INFO MissionPlanner.ArduPilot.APFirmware - device: {
  "name": "COM1",
  "description": "Communications Port",
  "board": null,
  "hardwareid": "ACPI\\VEN_PNP&DEV_0501"
} (D:\a\MissionPlanner\MissionPlanner\ExtLibs\ArduPilot\APFirmware.cs:134) [Base Thread]
2022-08-31 09:20:59,709  INFO MissionPlanner.ArduPilot.APFirmware - device: {
  "name": "COM59",
  "description": "USB Serial Device",
  "board": "PX4 FMU v6X.x",
  "hardwareid": "USB\\VID_3185&PID_0035&REV_0101"
```
full log file attached
[MissionPlanner.log](https://github.com/ArduPilot/MissionPlanner/files/9457168/MissionPlanner.log)

**Comment by meee1** [comment]
can we add this vid/pid to thefw  manifest?

**Comment by tridge** [comment]
@meee1 yes, I think we can, I'll have a go

**Comment by meee1** [comment]
@tridge and the bootloader string as well  "PX4 FMU v6X.x"

**Comment by meee1** [comment]
also, a possible workaround
open the FW screen
then disconnect and reconnect. the FW screen should attempt to hold it in bootloader mode

**Comment by tridge** [comment]
@meee1 this might fix it:
https://github.com/ArduPilot/ardupilot/pull/21581
note the duplicated USB IDs

**Comment by meee1** [comment]
ok, someone with the HW might need to test the specific outcome, one the manifest refresh's

**Comment by tridge** [comment]
@meee1 will do

**Comment by meee1** [comment]
i have a feeling the duplicate vid/pid might cause issues. but adding a new change to hopefully handle that

**Comment by tridge** [comment]
@meee1 I've tested with the updated manifest and it works, thanks!
