### ISSUE TITLE
Stuck, "Getting Params 250"

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2939]
For some reason when running Mission Planner connected via HereLink to the vehicle, MP got stuck displaying the message, "Getting Params 250".  It never seemed to give-up and the pop-up window was modal so the only solution was to restart MP.

![image](https://user-images.githubusercontent.com/1498098/188786201-7ce38244-8871-4c9c-b9c8-d57e21ec786d.png)

**Comment by meee1** [comment]
what device is sysid 250?

**Comment by rmackay9** [comment]
@meee1,

I'm not sure but if the "250" is a component ID then this is what I see.  The "vehicle 10" is probably the Gremsy gTuneDesktop application.
![image](https://user-images.githubusercontent.com/1498098/188793654-7d871885-2615-4725-ae7b-213f5ce03f8e.png)

So this may be a real edge-case that users will almost never see.  I was just surprised that MP would get stuck like this though because I guess that means a timeout is not being implemented properly somewhere right?

**Comment by rmackay9** [comment]
I think this is fixed now
