### ISSUE TITLE
Plan: allow Default Alt and SimpleGrid Alt to accept altitudes with decimal point

### ISSUE THREAD

**Issue by soleongmbh** [ArduPilot/MissionPlanner#3008]
#### Issue details
I miss the possibility to calculate the height with decimal point for missions? Currently, the decimal place is truncated for "Relative" in the value of the height. With "Absolute" the height is calculated correctly with decimal place.
Currently, the height is rounded to 1 metre. In addition, we would also like to be able to enter the default height to the centimetre when planning (currently only in metres). Is this possible?
![image](https://user-images.githubusercontent.com/42076677/203784281-fc419185-2f53-4ebe-9154-a3a7821b1d4b.png)

![image](https://user-images.githubusercontent.com/42076677/203784519-d4dce41c-c25a-4b38-be65-7efdca57ee5f.png)

#### Version
Mission Planner 1.3.77 build 1.3.8110.38294
ArduCopter V4.2.3

#### Platform
[  ] All
[  ] AntennaTracker
[X  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
all copter frames

#### Hardware type
Cube orange

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
I did a quick test and I think the Plan screen's altitude field accepts decimal points (e.g. 10.25m).  I wrote and re-read the mission and the decimal points remained and the vehicle correctly flew to the specified altitude.

**Comment by soleongmbh** [comment]
@rmackay9 Thanks for the test! Even if we import missions with decimal points, it works without any problems.  The decimal points must be enabled for the Plan screen's "Default Alt" and the "Auto WP" >> "Simple Grid"'s and "Survey Grid"'s "Altitude".

**Comment by soleongmbh** [comment]
I have found another problem. If the planning is done with "Absolute", then the height is calculated exactly in cm. However, if a WP point is moved, then the decimal places are lost.
This is very dangerous when flying at a low altitude.
With "Relative" the decimal places are also lost.
![grafik](https://user-images.githubusercontent.com/42076677/229028916-3e7380f9-f755-41f1-bf7d-63e2341096f0.png)


Clicked in the map (Absolute) without moving
Clicked in map (Absolute) and moved
Clicked in the map (Relative) without moving

Can someone please correct this urgently?
