### ISSUE TITLE
Simulation: running wrong version of stable Copter, beta does not work

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#3022]
How to reproduce:

- Open SIMULATION page
  - check Wipe checkbox (maybe not necessary)
  - click on Multirotor icon
  - when asked, select "stable"
  - check the version in the top left of the window <-- "ArduCopter V4.2.3 (6a694642)" appears
![image](https://user-images.githubusercontent.com/1498098/206828369-5288ac41-dec6-46b8-8f36-29c5cfa9fd62.png)

Repeat the above but after clikcing Multirotor, select "Latest(Dev)" and we see this failure:
![image](https://user-images.githubusercontent.com/1498098/206828392-14694639-3287-4c9b-a001-371780dfc49d.png)
![image](https://user-images.githubusercontent.com/1498098/206828394-868b1348-de26-4502-aacd-a06489d65c2b.png)

Surely the problem is related to PR https://github.com/ArduPilot/ardupilot/pull/22356

**Comment by tridge** [comment]
I've fixed the download script so it now does get 4.3 for stable, it gets the Copter-4.3 branch, which is currently 4.3.2-rc1

**Comment by rmackay9** [comment]
@tridge, Txs for that.  It seems that now choosing "stable" causes 4.3.2-rc1 to be loaded... so the beta is being used when the user has asked for stable.

**Comment by rmackay9** [comment]
I think this has been resolved now so closing.
