### ISSUE TITLE
multi-line @Bitmask parameters

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#3031]
we are switching to multi-line @Bitmask parameter markup. 
See first example here:
https://github.com/ArduPilot/ardupilot/pull/22505
the reason we are doing this is both to make the cpp clearer, and because we've noticed the MissionPlanner display of long @Description blocks is unreadable, whereas long @Bitmask fields is usable.
We made this PR to try and test if MissionPlanner would pick up the changes:
https://github.com/ArduPilot/ardupilot/pull/22519
the test seems to show that MissionPlanner param regen is not seeing the changes. I've been trying to work out why.

What would we need to do in order for MissionPlanner to not use its own parser and instead use the pre-parsed xml we autobuild?

**Comment by peterbarker** [comment]
It's also `@Values` - not used in master yet.

**Comment by meee1** [comment]
MP uses
https://autotest.ardupilot.org/Parameters/
as the primary source, and falls back to the old method if nothing is found
ie blimp would fall back atm... fixing atm
so i need to address any display issues as display issues

**Comment by tridge** [comment]
@meee1 what do I look for in MissionPlanner.log to see if it is falling back to the internal parser? Maybe we could remove the internal parser now so issues are clearer?

**Comment by meee1** [comment]
so pdef data is cached for 7 days, so you need to clean the cache in c:\programfiles\missionplanner\*.pdef.*

**Comment by tridge** [comment]
I deleted the pdef files and did the control-F param regen. The files re-appeared, but it is still the old data
![image](https://user-images.githubusercontent.com/831867/210021643-c138a36b-7728-41ce-9998-afc7a9b67681.png)

**Comment by meee1** [comment]
did you remove the .gz and xml?

**Comment by tridge** [comment]
@meee1 ahh, no I didn't remove the .gz, thanks!
with those removed and another regen I get the right bitmask:
![image](https://user-images.githubusercontent.com/831867/210021896-844a00d3-01bb-4f04-86fd-9d46b65a82d8.png)
can we auto-remove all the cache files when a user presses the regen button?
