### ISSUE TITLE
Remove stat from contextMenuStripMap on flighdata.cs

### ISSUE THREAD

**Issue by danilopmaciel** [ArduPilot/MissionPlanner#3054]
#### Issue details
I can't find where the stats button is being generated in the flightdata menu.

#### Version
1.3.75.1

I want to remove this content frow righ click on flight data.
Where is this item being created?

**Comment by robertlong13** [comment]
It's a plugin, hit Ctrl-P, deselect this, then hit "Save and Close" and then restart Planner

![image](https://user-images.githubusercontent.com/14059190/222278125-096c44a1-3e27-43f1-841d-ab9a0f0efaa2.png)
