### ISSUE TITLE
Mavlink Over Ethernet Development?

### ISSUE THREAD

**Issue by Willis-Aero** [ArduPilot/MissionPlanner#3121]
#### Issue details
_Please describe the problem, or desired feature_
Is Mavlink over Ethernet supported by Mission Planner?

Hardware Setup:
Flight Controller <--> UART-to-Ethernet <--> Ethernet Switch
Telemetry Radio <--> Ethernet Switch
Companion Computer  <--> Ethernet Switch

Software Setup:
ArduPilot
Mission Planner

Referencing Link:
https://discuss.ardupilot.org/t/ethernet-support/79770

Is there still an issue with heartbeat packets? I would use this to establish connection to Mission Planner. Thank you for the assistance.

![Mavlink_Ethernet](https://github.com/ArduPilot/MissionPlanner/assets/109181409/9b34b348-4ab7-41b1-89d8-d7c171a7680d)

**Comment by rmackay9** [comment]
I'm not sure that there is anything that MP needs to do.  I think the ethernet support implementation on the flight code is the current blocker an that development is progressing well and should be included in AP 4.5.

For reference here is a talk re [Ethernet support from the 2023 AP developer conference](https://www.youtube.com/watch?v=r4G2YIHobPo).
