### ISSUE TITLE
Full Parameter List Name column is slightly too narrow

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#3134]
The enhanced Full Parameter List has some nice features including the ability to set the individual bits of BitMask parameters but the Name column is too narrow meaning the user needs to expand it in order to see the full parameter name.  Below is an example of me attempting to view the gimbal/mount parameters.
![image](https://github.com/ArduPilot/MissionPlanner/assets/1498098/7521a0bd-708a-4599-bf44-62f71d2a883b)

**Comment by 4O6FPV** [comment]
this also is similar to the user parameters selection list not being large enough to view all the parameters. Issue here https://github.com/ArduPilot/MissionPlanner/issues/3114

**Comment by rmackay9** [comment]
This appears to be fixed in beta MP.

**Comment by xfacta** [comment]
I would suggest we reopen this as the Name column can not be resized in 
_MP/Config/Full Parameter List_ 
or in 
_Review A Log/Show Parameters_

Other columns can be resized.
I have done Beta updates and currently on 1.3.80 build 1.3.8644.43133

**Comment by rmackay9** [comment]
@xfacta,

OK, reopened.

It seems like both the "Name" and "Units" columns cannot be resized.

I guess you've found situations where the "Name" column is not wide enough?  For me it cannot be resized but it is always wide enough.

**Comment by xfacta** [comment]
Seems fixed again after a beta update

**Comment by rmackay9** [comment]
Yes, it seems fixed, closing!
