### ISSUE TITLE
Arduplane examples generate "Segmentation fault'

### ISSUE THREAD

**Issue by ebbblue** [ArduPilot/MissionPlanner#3171]
#### Issue details
In libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp  Seems that  _singleton is called before to be initialized  and that generate "Segmentation fault". I added an line to check :
 line  311
#if AP_RC_CHANNEL_ENABLED
//e
if (RC_Channels::get_singleton() != nullptr) //e line added 
//Check if LQ is to be reported in place of RSSI
_use_lq_for_rssi = rc().option_is_enabled(RC_Channels::Option::USE_CRSF_LQ_A
#endif
}

Worked with that , but someone who know the logic behind must verify if that is ok. 

#### Version
4.4.0

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Sub

#### Airframe type
fixed wing

#### Hardware type
beaglebone blue

#### Logs

./INS_generic
SBUS FD -1 115200 FD -1
AP_InertialSensor startup…
Segmentation fault

**Comment by EosBandi** [comment]
Wrong repository....
