### ISSUE TITLE
arming switch 

### ISSUE THREAD

**Issue by Neillives** [ArduPilot/MissionPlanner#3196]
#### Issue details
_Please describe the problem, or desired feature_
I have a Heewing T1 VTOL with a Radiomaster Zorro ELRS
The T1 comes with an FC and its setup to use stick arming, i have changed this to RC5_OPTION 153 to use arming on a switch, however it arms but won't disarm using the same switch, its on a two position switch. 

Can you advise what perimeters need to change to make this happen please 

 
#### Version
_What version was the issue encountered with_
Latest 
#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  1] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Fixed wing VTOL
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
It's probably best to raise support issues in the ArduPilot forum here https://discuss.ardupilot.org/c/arducopter/copter-44/169

Sorry to be strict but the issues list is really for confirmed bug reports and enhancement requests.  I'll go ahead and close this issue but I'll still see responses.
