### ISSUE TITLE
Param loading Green line does not go away

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#3198]
I think there may be an issue with the latest beta which means that the green parameter bar never goes away.

![image](https://github.com/ArduPilot/MissionPlanner/assets/1498098/f049c923-16ce-428d-ae4d-5a05360f1499)

I can push the Config Retry button but still the bar remains.
![image](https://github.com/ArduPilot/MissionPlanner/assets/1498098/20baef17-6110-4482-96d8-cf0d163396a9)

**Comment by rmackay9** [comment]
It seems the "Retry Now" button appears every time a parameter is changed.

**Comment by EosBandi** [comment]
Is it still happens with 1.3.81 ? I cannot repro it.

**Comment by rmackay9** [comment]
Hi @EosBandi,

Thanks for looking into this.  the exact way that I can reproduce this is to:

1. Start MP's copter simulator with "wipe" checked
2. Open config, Full Parameter list and set MNT1_TYPE = 10 (Xacti)

.. the green line should appear but never go away.

**Comment by EosBandi** [comment]
OK, got it. It seems to be a generic issue, when setting a parameter changes the number of parameters.
The quickest way to solve it to notify the user and do a forced parameter refresh.

Can you imagine a scenario when this forced refresh can cause an issue ?

**Comment by rmackay9** [comment]
On very slow links downloading all parameters could be very slow and could even timeout.  That's the only real problem I think.  I don't think the autopilot's performance (e.g. the main loop) will slow down during a parameter download.
