### ISSUE TITLE
Flightaxis SITL crashes at certain launch modes

### ISSUE THREAD

**Issue by isso11** [ArduPilot/MissionPlanner#3203]
The SITL between Mission Planner and (RF) RealFlight 9.5 Simulator (flightaxis) crashes when “Bungee” or “Discus” Launch methods are chosen in RF. 

SITL with FlightAxis only works with "Hand" and "Ground" launch methods.

is that issue known already? will there be a fix?

![image](https://github.com/ArduPilot/MissionPlanner/assets/11629174/326fd18f-18bc-4441-832f-298b05567e09)

**Comment by robertlong13** [comment]
RealFlight is crashing, not ArduPilot SITL or Mission Planner. Unfortunately, we can't fix any issues in RealFlight. You could report it on the RealFlight forums and there's a chance the devs will see it, and you can click the "Yes" box there to send the error report, but I wouldn't expect a fix any time soon.
