### ISSUE TITLE
安装的时候遇到了 未能找到C:\Users\UserName\Documents\Mission Planner\sitl

### ISSUE THREAD

**Issue by Sunrisies** [ArduPilot/MissionPlanner#3205]
问题详情
安装的时候
报错 C:\Users\123456\Documents\Mission Planner\sitl\ 
![image](https://github.com/ArduPilot/MissionPlanner/assets/103256281/3808e212-0323-4ce7-8455-91bd02c81def)

在以前使用的情况下没有问题，后来把c盘的文件夹删了，重新安装zip的安装包，这一次安装到D盘，安装的时候报错，进入之后也报错
![image](https://github.com/ArduPilot/MissionPlanner/assets/103256281/e344f3e3-d8b7-4362-98e4-49d6c22da868)

版本

1.3.80遇到的问题是什么版本

平台
[ X] 全部
[ ] AntennaTracker
[ ] 直升机
[ ] 飞机
[ ] 流动站
[ ] Sub

机身类型
什么类型的机身（飞翼、滑翔机、六角、Y6、八角等）
n/a

硬件类型
使用了什么自动驾驶硬件？（pixhawk、pixracer、PX4FMU 等）
不适用

日志
请提供显示问题的任何相关日志的链接
不适用

**Comment by EosBandi** [comment]
You don't have permissions to create the folder. Check with and admin user.
