### ISSUE TITLE
Some ui displays are abnormal 

### ISSUE THREAD

**Issue by cmmdwl** [ArduPilot/MissionPlanner#3206]
#### Issue details
_Please describe the problem, or desired feature_
![1697087321(1)](https://github.com/ArduPilot/MissionPlanner/assets/21263352/346dc5b9-6989-467e-9795-cec45947f3b3)
![1697087398(1)](https://github.com/ArduPilot/MissionPlanner/assets/21263352/d386c55b-69a6-4b1d-94f9-bcced6a768b5)

#### Version
_What version was the issue encountered with_
1.3.8479.20539
#### Platform
Not applicable
#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Not applicable
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
Not applicable
#### Logs
_Please provide a link to any relevant logs that show the issue_
Not applicable

**Comment by EosBandi** [comment]
The half-height buttons are intentional on the first screenshot to save screen real estate.
The issue on the second screenshot is caused by the fact that you set your system font to a monospaced font. MP UI is designed to use proportional fonts.
