### ISSUE TITLE
Gstreamer: update to most recent version

### ISSUE THREAD

**Issue by zeethas** [ArduPilot/MissionPlanner#3213]
I compared the results of video streaming on a 4G network using the same source stream (a Raspberry Pi + camera) and 2 different viewing clients on ground station (PC), the first client is version 1.14.4 internal to mission planner and the second gstream version is 1.22 .6 (the most recent to date). 
I noticed that the results with 1.22.6 are much better, in particular there are much fewer artefacts than v1.14.4 which are normally very visible when the 4G signal is not optimal.
My question is whether it is possible to plan an update of gstreamer internal to mission plammer to the most recent version in the next releases. 
Thank you

#### Version
1.3.80

#### Platform
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
copter

#### Hardware type
Omnibus F4 pro v3

**Comment by EosBandi** [comment]
There are still some compatibility issues on windows machines with the latest gstreamer and mission planner.
Normally MP will check if there is an already installed version of gstreamer (minGW) and if found it tries to use. So you can experiment with installing the new version (and delete the MP downloaded version from ProgramData/Mission Planner/gstreamer.
Note: you need the minGW version NOT the MSVC.

**Comment by ArthurPatriot** [comment]
> There are still some compatibility issues on windows machines with the latest gstreamer and mission planner. Normally MP will check if there is an already installed version of gstreamer (minGW) and if found it tries to use. So you can experiment with installing the new version (and delete the MP downloaded version from ProgramData/Mission Planner/gstreamer. Note: you need the minGW version NOT the MSVC.

Tested with latest version - it's not working.
