### ISSUE TITLE
Fly-to-Here-Alt does not work with AP 4.5.0-DEV (and perhaps earlier versions)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#3217]
On MP's Data screen's right-mouse-button menu there are two options, "Fly to Here" (which works fine) and "Fly to Here Alt" which does not appear to work with AP Copter-4.5.0-DEV (and perhaps other versions).  We should figure out why this doesn't work and either fix MP, the flight code or worse case remove the item from the menu.

**Comment by EosBandi** [comment]
Fly to Here Alt only changes the altitude and does not command the vehicle to a new position. It has worked like this since the beginning.
