### ISSUE TITLE
obstacle avoidance sliding problem 

### ISSUE THREAD

**Issue by MohdAbuRezeq** [ArduPilot/MissionPlanner#3231]
#### Issue details
Hello guys 
for obstacle avoidance in arducopter 
I notice that both options for stop and slide, acts like stop 
am using proximity sensor, and it works fine, but both options through arducopter parameter just stop the drone from obstacles and not slide over it. 

#### Version
4.4.2 
#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Quad 
#### Hardware type
pixhawk

**Comment by rmackay9** [comment]
Hi @MohdAbuRezeq,

This should be raised in [the forums](https://discuss.ardupilot.org/c/arducopter/copter-44/169) first I think and include an onboard log if possible.

I'll close this because this is the Mission Planner issues list and it's really a flight code question.
