### ISSUE TITLE
Dataflash Logs tab: Convert .Bin to .Log can't handle MSG messages

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#3235]
If a .bin log file is converted to a .log file using the Data screen's DataFlash Logs tab's "Convert .Bin to .Log" message the MSG log messages are not converted correctly.  Below is an excerpt of what appears in the .log file.

MSG, 1016137869, System.Byte[]
MSG, 1016137878, System.Byte[]
VER, 1016137884, 10, 5009, 4, 5, 0, 0, 1540729479, System.Byte[], 140, 2
MSG, 1016137897, System.Byte[]
MSG, 1016137906, System.Byte[]
MSG, 1016137914, System.Byte[]
MSG, 1016137929, System.Byte[]
MSG, 1016137935, System.Byte[]

**Comment by EosBandi** [comment]
Fixed in 1.81
