### ISSUE TITLE
MAVFTP: download broken?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#3242]
When attempting to download a file from the root directory of a CubeOrange autopilot I received the message, "File not found".  I right-mouse-button clicked on the file and selected "Download" so it seems unlikely that the file isn't actually there.
![mp-mavftp-download-error](https://github.com/ArduPilot/MissionPlanner/assets/1498098/a889c747-b1ec-4afd-9b7f-1f30eeb2105c)

**Comment by EosBandi** [comment]
Apparently fixed in 1.81. Checked with a CubeOrange+.
If it still don't work with you please reopen.
