### ISSUE TITLE
Latest version ArduPlane gives errors in Windows 11.

### ISSUE THREAD

**Issue by rizacelik** [ArduPilot/MissionPlanner#3253]
Latest version ArduPlane gives errors in Windows 11. When I want to change the options, it gives me the error shown in the screenshot below.
Error message: "Object reference not set to an instance of an object"

![image](https://github.com/ArduPilot/MissionPlanner/assets/19993109/3bc57e04-3557-4f2c-a510-f3926067534f)

This error occurs with all changes. Tested versions MissionPlanner-stable and MissionPlanner-1.3.81. There is the same error.

**Comment by EosBandi** [comment]
I guess you have only four serial ports.... right ?

**Comment by rizacelik** [comment]
Yes. USART1, USART2, USART4, USART6
