### ISSUE TITLE
Errors in Build

### ISSUE THREAD

**Issue by nivGevaAerotor** [ArduPilot/MissionPlanner#3255]
I cloned the code from git, but couldn't get Visual Studio (2022 `version)` to successfully build the program/
Thus far, I tried:
- using the "git submodule --init -- recursive" command in GitBash.
- pasting "copy "$(ProjectDir)ExtLibs\System.IO.Compression.dll" "$(ProjectDir)$(OutDir)" in Project Properties ->Build Events.
- updating and re-installing NuGet packeges.
- cloning the code in ExtLib\mono folder (which wasn't downloaded with the original git cloning), and using the "git submodule -- 
   init -- recursive" command in GitBash inside the said folder.
- re-cloning the code in git.

After doing all that, I still got the next errors:
![MissionPlanner errors - 13 12 23](https://github.com/ArduPilot/MissionPlanner/assets/153518851/832d625c-9a35-49e0-8747-82eb6df31f60)

CS0006	Metadata file 'C:\Users\User\Desktop\Aerotor\MissionPlanner_2.0\MissionPlanner\ExtLibs\Controls\bin\Debug\net472\MissionPlanner.Controls.dll' could not be found	MissionPlannerTests	C:\Users\User\Desktop\Aerotor\MissionPlanner_2.0\MissionPlanner\MissionPlannerTests\CSC	1	

CS0006	Metadata file 'C:\Users\User\Desktop\Aerotor\MissionPlanner_2.0\MissionPlanner\bin\Debug\net461\MissionPlanner.exe' could not be found	MissionPlannerTests	C:\Users\User\Desktop\Aerotor\MissionPlanner_2.0\MissionPlanner\MissionPlannerTests\CSC	1	

Please help if you can, and thanks in advance!

**Comment by EosBandi** [comment]
Build ONLY the Mission Planner project, not the whole solution.
