### ISSUE TITLE
Invalid number entered error

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/MissionPlanner#3278]
#### Issue details
New Install. 

Error when planning missions with no aircraft connected, repeats for every waypoint addition or change. 

The WP Radius default is 2.0m which causes the error, change to 10 resolves the error.

#### Version
v1.3.81 build 1.3.8741.25556 (New install)
#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Copter
#### Hardware type
N/A

#### Screenshot
![Screenshot 2024-01-21 191737](https://github.com/ArduPilot/MissionPlanner/assets/3287001/2d35e442-4ddd-47be-a877-78311c5853ca)

**Comment by EosBandi** [comment]
2.0 was entered by you or got from the vehicle, but your international setting is for decimal comma not point.
The last value in the field is 30, and it is populated from the vehicle connected.
The  last value is in the filed is saved at exit and reloaded at next start. So enter a valid number and exit MP (or you can delete the config,XML from the documents/Mission Planner folder to reset all settings.)
