### ISSUE TITLE
screen color

### ISSUE THREAD

**Issue by krpel** [ArduPilot/MissionPlanner#3285]
Why is the screen color of the Mission Planner white or how to change it to black
![asdasdassa](https://github.com/ArduPilot/MissionPlanner/assets/158812847/362bf98b-1be2-49e0-b2de-535c59720f20)

**Comment by robertlong13** [comment]
Config > Planner > Theme

**Comment by krpel** [comment]
Thank you so much Thanks to you, I got some good information
