### ISSUE TITLE
Log Browser: right-mouse-button menu includes odd "Properties MasterPane" option

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#3331]
![image](https://github.com/ArduPilot/MissionPlanner/assets/1498098/8868b18d-9d3a-4df6-b05f-dc96133833bf)

The Log Browser page's graphing window has an few odd looking right-mouse-button menu items:

- Properties MasterPane
- Properties YAxis
- Properties YAxis2

These look like debug and were perhaps accidentally left in place?

**Comment by rmackay9** [comment]
Sorry to be a nag but these 3 extra items are a bit annoying.  I don't think it's good that we have developer options like this exposed to the user.

**Comment by EosBandi** [comment]
Only Michael knows, the commit was supposed to allow custom Y axis, but it does indeed looks like a debug menu.
I added a PR to remove it, but it is up to Michael. https://github.com/ArduPilot/MissionPlanner/pull/3376

**Comment by EosBandi** [comment]
fixed in 18d17d4f936a6a4a5e85a623682cc5b4a6694b62

**Comment by rmackay9** [comment]
Ah, so happy that those are gone.
