### ISSUE TITLE
64bit Windows 11 + MP 1.3.81 Can't UDP connect 8266WiFi module (v1.2.3)

### ISSUE THREAD

**Issue by lida2003** [ArduPilot/MissionPlanner#3356]
#### Issue details

1. [On Windows PC] same computer QGC works fine with 8266 module  // Can't be the firewall or windows env issue

2. [On Windows PC] Close QGC and use MP 1.3.81  connect //both port 14550 or 192.168.4.1:14550 failed 

![图片](https://github.com/ArduPilot/MissionPlanner/assets/1296171/8b3bb72c-6b26-4211-8601-1499da1aeecc)

3. up to date version 8266 1.2.3

![图片](https://github.com/ArduPilot/MissionPlanner/assets/1296171/77907904-4a28-4684-8a0f-c989f64c7333)

4. status show communication with FC is OK

![图片](https://github.com/ArduPilot/MissionPlanner/assets/1296171/e49df7e0-ac87-41ec-9571-2e177f51dd6c)

5. popup error like below

![图片](https://github.com/ArduPilot/MissionPlanner/assets/1296171/2e99c7da-5718-497f-8cca-8267423113f8)

6. Pad Mission Planner 1.3.81 works fine

#### Version
1.3.81

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ x ] Rover
[  ] Sub

#### Airframe type
Rover

#### Hardware type
- Acoda-RC H743 Dual

Device name	Daniel-SurfacePro
Processor	Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz   2.71 GHz
Installed RAM	8.00 GB
Device ID	C5FC645F-69FA-4372-A8F8-CB8C596953A3
Product ID	00330-80000-00000-AA147
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

Edition	Windows 11 Pro
Version	22H2
Installed on	‎23/‎5/‎31
OS build	22621.3527
Experience	Windows Feature Experience Pack 1000.22700.1003.0

#### Logs
No

#### Ref

- [4.3 DEV can’t connect thru esp8266 wifi](https://discuss.ardupilot.org/t/4-3-dev-cant-connect-thru-esp8266-wifi/89546)

**Comment by meee1** [comment]
Are you using udpcl?

**Comment by lida2003** [comment]
> Are you using udpcl?

Tried, just the same as UDP. Android version works fine with UDP.

**Comment by lida2003** [comment]
Doesn't work with 1.2.2 also.

**Comment by lida2003** [comment]
There are two Mission Planner now. All checked then issue solved.

![图片](https://github.com/ArduPilot/MissionPlanner/assets/1296171/1312b619-90d2-4a11-9c64-21f8198259fc)

![图片](https://github.com/ArduPilot/MissionPlanner/assets/1296171/d15ce9d6-8a01-4d76-bb29-c6ef0f9fd4f7)
