### ISSUE TITLE
Dataflash Log Download is extremely slow

### ISSUE THREAD

**Issue by kakariki1** [ArduPilot/MissionPlanner#3387]
#### Issue details
Downloading a Dataflash Log via USB is extremely slow (8 Megabytes takes several hours).

#### Version
1.3.82 (1.3.81 works fine)

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
not relevant

#### Hardware type
SpeedyBee F405-Mini

**Comment by lcabon258** [comment]
I have the same problem. My FC is Pixhawk 6C with ArduCopter 4.5.5.

**Comment by Rodrigo-NH** [comment]
Same issue here. Described https://discuss.ardupilot.org/t/extremelly-slow-log-download-in-mp-1-3-82/124656/5

Problem is the same despite FC FW version 4.4.4 or 4.5.6

**Comment by meee1** [comment]
Please try beta, confirm if it's been fixed already

**Comment by kakariki1** [comment]
As far as I can tell the latest beta is working ...

**Comment by Rodrigo-NH** [comment]
Issue is fixed for me after applying beta updates
