### ISSUE TITLE
Mission Planner for mac is not loading properly: black screen

### ISSUE THREAD

**Issue by ben-xD** [ArduPilot/MissionPlanner#3393]
#### Issue details
After downloading and installing the latest mission planner for mac published 10 hours ago (`63c0595160ebde397edaa5600984e4ce56ffe89f`) on https://github.com/ArduPilot/MissionPlanner/releases/tag/osxlatest, I can only see a black screen:

![mp@2x](https://github.com/user-attachments/assets/ae250a0b-ad38-462b-a313-60fdb587bc1a)

#### Version
`63c0595160ebde397edaa5600984e4ce56ffe89f`

**Comment by ben-xD** [comment]
The latest one works

**Comment by meee1** [comment]
Yes this was traced to a skia version change. So it's been reverted. It broke android as well
