### ISSUE TITLE
Can not open .resx file

### ISSUE THREAD

**Issue by WangHan2014** [ArduPilot/MissionPlanner#3407]
#### Issue details
I can't open .resx file,unless use xml editor.

#### Version
lastest

when i use vs2022 and try to translate some strings,it cause:

![image](https://github.com/user-attachments/assets/98f46f9e-4d3c-45d7-b46a-875955923c8f)

The VS say Items with the same key have been added,how to resolve it.It's very uncomfortable to use a xml editor :-(

**Comment by EosBandi** [comment]
This is a VS Error.
User right Click Open With -> Managed Resource Editor (Legacy)

**Comment by WangHan2014** [comment]
OK
