### ISSUE TITLE
TabActionsSimple disable.. WHY?

### ISSUE THREAD

**Issue by danilopmaciel** [ArduPilot/MissionPlanner#3426]
How do I return the "Action" tab - Tabactionssimple?

**Comment by Godeffroy** [comment]
Also (i didn't about it earlier) you can simply change it with right clicking on the Tab action list and select "customize"
![image](https://github.com/user-attachments/assets/e37a398a-282a-44ca-8c4c-0262ba165e64)
then check the box "tabActionsSimple" to make it visible
![image](https://github.com/user-attachments/assets/e5b33840-5222-4ab2-ab53-e82fd4bffeb2)

**Comment by danilopmaciel** [comment]
Ohh god! aeiuHAUIEhUIAEh Thankyou!
