### ISSUE TITLE
3D map not working

### ISSUE THREAD

**Issue by LupusTheCanine** [ArduPilot/MissionPlanner#3441]
#### Issue details
3D map doesn't work, it stops rendering after at most two tiles with an artifact line going down
![image](https://github.com/user-attachments/assets/78eceb39-5641-4f2a-af27-99574152e7cc)

#### Version
Up to 1.3.82 build 1.3.9077.8924 on Windows

#### Platform
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Any 
#### Hardware type
SITL

**Comment by EosBandi** [comment]
Fixed in https://github.com/ArduPilot/MissionPlanner/pull/3442
