### ISSUE TITLE
adding a new flight mode

### ISSUE THREAD

**Issue by zbybill** [ArduPilot/MissionPlanner#346]
I have finish step1 to step5,Step #6: Raise a request in the Mission Planner’s Issue List if you wish the new flight mode to appear in the Mission Planner’s HUD and Flight Mode set-up.I don't know how to get new flight mode in Nission Planner.

**Comment by albersIntern** [comment]
Hello!

I'm trying to get a new flight mode into mission planner as well and am having similar issues. I've followed the documentation for copter that explains how to add a flight mode, but can't get it to work for the plane modes. Any help is appreciated!
