### ISSUE TITLE
Data, Action Mount mode blank

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#3462]
For some reason the Data screen's Action Tab's Mount drop-down appears to be blank.  I'm not sure how MP populates this drop-down but if it's from a flight code parameter I'm happy to fix asap.  In any case, it's quite important that users be able to change the mount mode

![image](https://github.com/user-attachments/assets/8f74d22f-d115-4176-bedc-4fd08f7a170c)

**Comment by robertlong13** [comment]
This is really weird:
1. I cannot reproduce
2. I know exactly what caused it

It's caused by the rename of `MNT_DEFLT_MODE` to `MNT1_DEFLT_MODE`. What I can't understand is why it's not happening to me.

**Comment by casrya** [comment]
FYI there is also a mount mode combo in class Joy_Mount_Mode for the joystick settings.
