### ISSUE TITLE
fix 3D accel calibration via MAVLink

### ISSUE THREAD

**Issue by tridge** [ArduPilot/MissionPlanner#38]
Hi Michael,
Randy and I have implemented a better MAVLink method for 3D accel calibration in both plane and copter using MAVLink STATUSTEXT and COMMAND_ACK packets.
You can see the implementation in MAVProxy here:
https://github.com/tridge/MAVProxy/commit/4e13efdab2fabfd62a68c0ee849322821b2f1e9b
Basically the flow is this:
- if in CLI, then old text based flow is used
- if connected with MAVLink then APM sends MAVLink STATUSTEXT messages starting with "Place APM "
- the ground station should show the text of these messages to the user, then should send COMMAND_ACK MAVLink response messages back to the APM when the user has acknowledged the message.
  If you could add this to MP that would be great! Currently accel cal over MAVLink is broken with the 3.0 beta

**Comment by zlite** [comment]
Although this is fixed in the stand-alone setup menu item, it's still broken in the Wizard.

**Comment by meee1** [comment]
Chris, what vehicle type where you testing with?

**Comment by zlite** [comment]
Plane (3.30)

On Tue, Jun 2, 2015 at 2:25 AM, Michael Oborne <notifications@github.com>
wrote:

> Chris, what vehicle type where you testing with?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/MissionPlanner/issues/38#issuecomment-107883951>
> .
>



-- 
Chris Anderson
CEO, 3D Robotics
chris@3drobotics.com

**Comment by meee1** [comment]
ive uploaded a new beta that should fix this issue in the wizard.

**Comment by zlite** [comment]
Thanks!
