### ISSUE TITLE
Add warning of nearby airports

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#455]
With the growing frequency of news reports about near misses with manned aircraft we should add warnings to the ground station software when the vehicle (or home location?) is within some certain distance of an airport.

I've found this open database of airport data that might be a good place to start.
http://openflights.org/data.html

Some other enhancements might be to adjust the size of the area around the airport dependent upon how much traffic it has.  So big airports have a larger zone (5km?)  and smaller airports have smaller zones (1km?).

It might be useful to have a mission check button that confirms that the mission does not stray into airport safety zones.

**Comment by dscassid** [comment]
Does anyone know if airport warning messages or exclusion zones were implimented??
