### ISSUE TITLE
Request: tlog playback controls that are accessible on other screens.

### ISSUE THREAD

**Issue by iskess** [ArduPilot/MissionPlanner#502]
I would like to be able to control the .tlog playback while viewing other screens like Quick, Status, or even the Flight Plan page. Either the controls can be broken out, or shortcut keys provided. the space-bar is a universal start/stop button for example

**Comment by iskess** [comment]
I know this issue is almost two years old, but I don't know if its ever been considered.

**Comment by meee1** [comment]
shortcut keys I can do. I'm not sure if I like space or not.

**Comment by iskess** [comment]
Can we just breakout the whole tlog tab into a separate window like we can with the HUD? It would be nice to have access to the speed controls too. Or maybe during tlog playback the controls appear on the menu bar. There is unused space there.

**Comment by meee1** [comment]
I did look into this in the past. and its more technically challenging than it sounds at this point in time.

**Comment by iskess** [comment]
Ok, let's just go with a shortcut key for now then. The Space Bar is the most intuitive, but if you don't like that, how about the letter P. It stands for both Pause and Play and can cycle between the two. Maybe the +/- keys could change the speed?

**Comment by meee1** [comment]
done, using space and + and -

**Comment by iskess** [comment]
This is really great! I especially like that we have better resolution for playback speeds. 
Thank you!
