### ISSUE TITLE
[Feature Request] Add Flight distance and Flight time estimation on flight planning screen

### ISSUE THREAD

**Issue by jmachuca77** [ArduPilot/MissionPlanner#568]
Inside of the survey grid plugin you can create a flight plan and it will estimate the distance traveled and the flight time required. It would be also beneficial to have this information on the regular flight planning screen when doing modifications manually to the grid.

**Comment by Jman841** [comment]
Any update on this?

**Comment by jmachuca77** [comment]
This is already implemented
