### ISSUE TITLE
Requests: 'Time to Next WP', 'Time to Home'

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/MissionPlanner#578]
On my consumer xxx GPS there are fields such as Time to Waypoint and Time to Destination taken from the average speed or instantaneous speed (or combination) and the remaining distance.

When flying with batteries or fuel it's almost compulsory to know how much longer you can get from a pack or tank. All RC pilots without telemetry fly according to TIME. Even if you know your voltage knowing the time to WP and time to home in a mission is invaluable.

GroundSpeed(m/s)/Distance(m) = secs (convert to mins)

So in the image below: 
37.8kmh = 10.39m/s / 7240m = 696 secs = 11mins 37secs to Home
37.8kmh = 10.39m/s / 3276m = 315 secs = 5mins 15secs to WP21

![mprequest](https://cloud.githubusercontent.com/assets/3287001/3916977/280ac9d0-2384-11e4-892f-b49f3c338568.gif)

**Comment by rsesa** [comment]
I also find "toh" very useful for long missions. @meee1 ,  could you please explain how is it calculated (with average, current, etc. speed)?

**Comment by meee1** [comment]
toh = DistToHome  / groundspeed
