### ISSUE TITLE
survey grid missing mono

### ISSUE THREAD

**Issue by fisholo** [ArduPilot/MissionPlanner#674]
hi all
thanks a lot for your work
I'm running mission planner 1.3.7 build 1.1.5307.24027 on a ubuntu 14.04 64 bit with mono 3.2.8
in the "Auto WP" menu I can't find Survey Grid and Survey Gird V2
what I'm doing wrong?

thanks in advance

Fabrizio

**Comment by HarrisonHeli** [comment]
Using Mission Planner 1.3.19 from firmware.diydrones.com on mono 3.28 on Ubuntu 14.04.

The survey grid and grid 2 options are still missing in the menu items.
I have run the same release on a windows VM and the option is present and working correctly.

Is the grid run as a plugin or built into the exe? 
Happy to do more testing if given some pointers.
