### ISSUE TITLE
Windows don't terminate promptly or reliably

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/MissionPlanner#704]
Just had this issue at a critical point in a mission, plane is currently 20km away and I tried to read the waypoints back. (Using RFD900's for telemetry and RSSI is a bit low at this range.)
After cancelling the read waypoints command the window won't close (see image below), in fact for many minutes the window stays open eventually requiring MP to be terminated and reopened and then had to attempt to reconnect to the plane. 
Quite a few of the small windows don't terminate immediately, staying open for many seconds/minutes after the cancel button is clicked or not closing at all. 
![nocancel](https://cloud.githubusercontent.com/assets/3287001/4990113/acae6992-698b-11e4-8de4-49ece14d2f6d.PNG)

**Comment by GrahamDyer** [comment]
Still getting this, can post a video to demonstrate?

**Comment by meee1** [comment]
please post a video yes.

**Comment by meee1** [comment]
the biggest delay I can see is 5 seconds. which is attempting to receive a wp 5 times and failing all 5 times.

**Comment by meee1** [comment]
please provide missionplanner.log as well

**Comment by GrahamDyer** [comment]
One video here, I'll get more of other instances.

http://tinypic.com/r/2ypaejb/8
