### ISSUE TITLE
Allow one-step upload of .bin files to droneshare

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#756]
We would like to improve the quality of the log files uploaded to droneshare to allow better datamining so that we can proactively catch hardware and software issues.

One part of that would be to make it easier for users to upload binary log files to droneshare by making it a one-step process, perhaps as part of downloading the binary log file.  Maybe have a checkbox, "Upload to droneshare" on the download screen.

Here is the related droneshare issue.  https://github.com/diydrones/droneshare/issues/141

**Comment by meee1** [comment]
wip 7ea2512c

**Comment by rmackay9** [comment]
I think this was done but now we've lost droneshare (at least for the moment).
