### ISSUE TITLE
Display all channel output in MP?

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/MissionPlanner#812]
The Pixhawk supports outputs to more than 8 channels but ever since APM2.x days the MP has always only shown ch 1-8 outputs. Please can the outputs to the additional channels be shown in Status?
![channels](https://cloud.githubusercontent.com/assets/3287001/6540808/31390cec-c4ba-11e4-9fe3-a4fcae80a5c5.GIF)

**Comment by robustini** [comment]
+1

**Comment by nicksargeant** [comment]
Yes please.

**Comment by meee1** [comment]
there is no message to send these extra channels via mavlink, it will require a change on the autopilot side before can do anything on this

**Comment by GrahamDyer** [comment]
Tridge says: "When there are more than 8 input channels ArduPilot will send the RC_CHANNELS message with up to 16 channels. That is in all current releases. The problem is that MissionPlanner doesn't display it.
Please open an issue with MissionPlanner."
https://github.com/diydrones/ardupilot/issues/1968#issuecomment-80198537

**Comment by meee1** [comment]
graham, where you after the 16 channels in? or the 16 channels out?

**Comment by rmackay9** [comment]
This is the message apparently that is sent by arducopter and arduplane
http://mavlink.org/messages/common#RC_CHANNELS

**Comment by meee1** [comment]
yes, that message is for rc inputs only, not outputs, ive added all 16 inputs in commit today d7e9ebdb28c17de2f239a6759d2add81215f1141

**Comment by GrahamDyer** [comment]
Personally I'm looking for the ch 9-12 outputs, using the extra channels for light switch and zoom on the camera.

**Comment by GrahamDyer** [comment]
Request for the outputs to be enabled for this issue to be resolved?

**Comment by meee1** [comment]
still requires copter/plane changes.
a new message created for all 18 channels similar to the rc input eg mavlink_msg_rc_channels_send, that adapts to 18 channels when needed

**Comment by GrahamDyer** [comment]
Nothing further on this?
