### ISSUE TITLE
Missions only display on Flight Data map after writing not reading.

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/MissionPlanner#813]
When one reads a mission from an aircraft, the mission waypoints and path are shown on the Flight Planner map but NOT on the Flight Data map, the mission has to be re-written to the aircraft for the waypoints and path to be shown on the Flight Data map.

Would it be possible to have them show up after being read from the aircraft?

**Comment by robustini** [comment]
+1

**Comment by meee1** [comment]
what version f MP where you running? I think this may already be resolved

**Comment by GrahamDyer** [comment]
The latest x.19, I think. Haven’t tried a beta.

**Comment by magicrub** [comment]
@grahamDyer when closing an issue, even a super old one, please give a reason.

**Comment by GrahamDyer** [comment]
Issue has been resolved.
