### ISSUE TITLE
APM:Plane: "ter_curalt" MP warning request

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/MissionPlanner#890]
Currently one can set a Mission Planner altitude warning for an aircraft when it goes below a set altitude above the take-off or home altitude. 

Wouldn't it be better to have a warning for altitude above "ter_curalt" (terrain current altitude) which is surely more relevant as that is the height that the aircraft is above the ground at that point? 

Or could an additional warning checkbox be added?

**Comment by meee1** [comment]
try the warning manager.
control-f > warning manager.

**Comment by GrahamDyer** [comment]
Yes, thanks, works great. Still think that a default warning for "altitude over terrain" is more relevant and important than one for "altitude over home" as the world ain't flat :))

**Comment by meee1** [comment]
look at  ter_curalt

**Comment by GrahamDyer** [comment]
Yes, that is what I'm asking for as a default warning, not alt over home

**Comment by GrahamDyer** [comment]
Request option to use "ter_curalt" (Alt of MAV over current terrain) if available as a _default_ low altitude warning rather than "altitude above home point" as it is currently configured. 

Low "altitude above home point" warning isn't of much use in any kind of undulating or varying terrain.
