### ISSUE TITLE
Accel Cal menu missing when Rover connected

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/MissionPlanner#907]
I was testing against MP using an APM2 and found that under MandatoryHardware the accel cal menu item is missing.  I connected a Pixhawk running rover and it was still missing.
Thanks, Grant.

**Comment by meee1** [comment]
releated https://github.com/diydrones/MissionPlanner/issues/905

**Comment by meee1** [comment]
https://github.com/diydrones/MissionPlanner/commit/4f6c9182cee82488c3e9508b213c18c38585ab59

**Comment by gmorph** [comment]
FIXED!  Thanks.
