### ISSUE TITLE
Enhancement request: Set Loiter Radius button.

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/MissionPlanner#932]
One of the parameters that we find needing frequent changes during some missions is Loiter Radius in APM:Plane. A button to set the radius instantly would ease the process greatly as the only way to do change it currently without rewriting the mission is to search for it in the full parameter list using a keyword like "loiter" and then type in the change and write the parameter. 

The button arrowed in the image below shows be how this could implemented. 

![rtl](https://cloud.githubusercontent.com/assets/3287001/8663199/77d2c094-29c8-11e5-9f20-2a7e12ffaa6d.GIF)

**Comment by GrahamDyer** [comment]
http://diydrones.com/forum/topics/changing-loiter-radius-during-flight?xg_source=activity

**Comment by GrahamDyer** [comment]
Bump, please. This would be so useful and time saving in APM:Plane missions.

**Comment by GrahamDyer** [comment]
Bump again, was requested July 2015

**Comment by meee1** [comment]
done
