### ISSUE TITLE
Avoiding user incorrect settings on Land

### ISSUE THREAD

**Issue by lvale** [ArduPilot/MissionPlanner#964]
GCS should try to prevent users from setting invalid locations for Land.

Ref: https://github.com/diydrones/ardupilot/commit/c87929e907d17d6f1a7dd5d753d6b84f29e7d9c5

**Comment by meee1** [comment]
this is where I believe plane and copter act differently. plane needs a location, copter will land at that stop if all the values are 0.

ie https://github.com/diydrones/ardupilot/blob/0ecebbd55f3c9196386b590fba1d88c8c31dd190/ArduCopter/commands_logic.cpp#L333
